City-of-Helsinki/hel-fi-drupal-grants

conf/cmi/openid_connect.settings.yml, public/sites/default/settings.php
Login form has disappeared from test environment. This adds it back so testers can get in without tunnistamo access.
=> Hotfix: Fix login form

conf/cmi/system.theme.global.yml, public/sites/default/all.settings.php
* Fixed favicon
* `git checkout AU-680-favicon`
* `make fresh`
[AU-680]: https://helsinkisolutionoffice.atlassian.net/browse/AU-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-680: fix favicon

public/modules/custom/grants_handler/translations/fi.po
Fix two broken Finnish translations in the .po file.
=> fix: AU-XX Corrent wrong translations in grants_handler .po

conf/cmi/block.block.announcements_2.yml, conf/cmi/block.block.hdbt_subtheme_breadcrumbs.yml, conf/cmi/block.block.hdbt_subtheme_messages.yml, conf/cmi/block.block.sivunotsikko.yml
* Moved around announcements and status messages
* `git checkout feature/AU-717-reorder-blocks`
* `make fresh`
[AU-717]: https://helsinkisolutionoffice.atlassian.net/browse/AU-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-717: reorder blocks

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme, public/themes/custom/hdbt_subtheme/templates/paragraph/paragraph--oma-asiointi.html.twig
* Show front page oma asiointi block only when company is selected
* `git checkout feature/AU-701-oma-asiointi-uusi`
* `make fresh`
[AU-701]: https://helsinkisolutionoffice.atlassian.net/browse/AU-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-701: show oma asiointi only when company selected

public/modules/custom/grants_oma_asiointi/grants_oma_asiointi.module, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiBlock.php, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-block.html.twig, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_oma_asiointi/translations/sv.po
* Limit shown messages and applications to two
* Show all messages -link when over two unread messages
* `git checkout feature/AU-591-oma-asiointi`
* `make fresh`
[AU-591]: https://helsinkisolutionoffice.atlassian.net/browse/AU-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-591: Limit messages and applications in Oma asiointi -block to two

public/modules/custom/grants_audit_log/src/EventSubscriber/GrantsAuditLogEventSubscriber.php
Removes mystery number from views.
* Fixed the thing.
* `git checkout feature/AU-714-remove-mystery-number`
* `make fresh`
[AU-714]: https://helsinkisolutionoffice.atlassian.net/browse/AU-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-714: remove mystery number echo

public/themes/custom/hdbt_subtheme/templates/webform/webform-submission-form.html.twig, public/themes/custom/hdbt_subtheme/translations/fi.po, public/themes/custom/hdbt_subtheme/translations/sv.po
* Change title in error notice
* `git checkout feature/AU-191-virheilmoitus-title`
* `make fresh`
[AU-191]: https://helsinkisolutionoffice.atlassian.net/browse/AU-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-191: change title in error notice

public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php
* `git checkout feature/AU-682-mandate-interruption`
* `make fresh`
[AU-682]: https://helsinkisolutionoffice.atlassian.net/browse/AU-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-682 Handle mandate process interruptions properly

public/modules/custom/grants_handler/grants_handler.module
* Remove default value from Community practices business -radio buttons
* `git checkout feature/AU-774-liiketoiminta-radio`
* `make fresh`
[AU-774]: https://helsinkisolutionoffice.atlassian.net/browse/AU-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-774: Remove default value from Community practices business -radio buttons

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Element/CompensationsComposite.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
There was error in subvention validations, where you had to have ALL fields in subventions filled or form errored. Desired functionality is that ONE of the fields is required, no matter what that is.
* Added validation for subvention fields that check empty or 0,00€ values
* `make fresh`
[AU-796]: https://helsinkisolutionoffice.atlassian.net/browse/AU-796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-796: Fix subvention validations.

public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php, public/modules/custom/grants_mandate/translations/fi.po, public/sites/default/development.settings.php, public/sites/default/staging.settings.php, public/sites/default/testing.settings.php
Nyt koodi tarkastaa valtuutusvaiheessa että käyttäjällä on asianmukainen pääsyoikeus.
Moduulissa on kovakoodattu lista sallituista rooleista mutta listaan voi lisätä rooleja konfiguraation kautta. Tässä on yritetty tasapainoilla työmäärän ja DX:n välillä.
* `feature/AU-695-allowed-roles`
* `make fresh`
* TMuokkaa local-settings.php tiedostoa ja lisää sinne `$config['grants_mandate.settings']['extra_access_roles'] = ['NIMKO'];` jolloin testiyrityksien valtuutusprosessi onnistuu.
Tämä muutos pitää tehdä tarvittaessa testipalvelimelle ja kaikkien kehittäjien koneille joten älä mergeä tätä ilman että kaikki ovat tietoisia muutos tarpeesta.
Huomaa että testidatassa roolit eivät vastaa tuotantoa. 
[AU-695]: …
=> feat: AU-695: allowed roles

public/modules/custom/grants_handler/grants_handler.services.yml, public/modules/custom/grants_handler/src/EventSubscriber/GuzzleHttpErrorExceptionSubscriber.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Add event handler to catch guzzle errors
* `git checkout feature/AU-792-http-errors`
* `make fresh`
Technically this works well. Practical issue that error message is not on top of the front page.
[AU-792]: https://helsinkisolutionoffice.atlassian.net/browse/AU-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-792: Add subscriber to handle guzzle errors

composer.lock
GDPR calls to ATV were authenticated incorrectly with JWT token, when they need to be authenticated with Apikey.
* ATV module was updated to 0.9.5 which uses apikey.
* [Link to other PR
](https://github.com/City-of-Helsinki/drupal-module-helfi-atv/pull/9)
[AU-820]: https://helsinkisolutionoffice.atlassian.net/browse/AU-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-820: Update ATV.

public/modules/custom/grants_profile/src/Form/GrantsProfileForm.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Fix translations for Omat tiedot edit
* `git checkout feature/AU-691-omat-tiedot-tekstit`
* `make fresh`
[AU-691]: https://helsinkisolutionoffice.atlassian.net/browse/AU-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fiX: AU-691: Omat tiedot edit translations and texts

conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.yleisavustushakemus.yml
* Translations to KH and Kasko Yleisavustushakemus
* `git checkout feature/AU-787-webform-translations`
* `make fresh`
[AU-787]: https://helsinkisolutionoffice.atlassian.net/browse/AU-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-787: add en and sv translations to webforms

conf/cmi/block_content.type.login_page_info.yml, conf/cmi/core.entity_form_display.block_content.login_page_info.default.yml, conf/cmi/core.entity_view_display.block_content.login_page_info.default.yml, conf/cmi/field.field.block_content.login_page_info.body.yml, conf/cmi/field.field.block_content.login_page_info.field_login_type.yml, conf/cmi/field.storage.block_content.field_login_type.yml, conf/cmi/language.content_settings.block_content.login_page_info.yml, public/modules/custom/grants_profile/grants_profile.module, public/themes/custom/hdbt_subtheme/templates/layout/page--401.html.twig, public/themes/custom/hdbt_subtheme/templates/layout/page--user--login.html.twig
Allows you to display blocks of content on login page(s).
Similar functionality to https://github.com/City-of-Helsinki/drupal-helfi-form-tool/pull/137
* Added new block type for login page content.
* `git checkout feature/AU-756_Login_page_blocks`
* `make fresh`
[AU-756]: https://helsinkisolutionoffice.atlassian.net/browse/AU-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-756: Display blocks on login page

conf/cmi/language/en/views.view.application_search.yml, conf/cmi/language/sv/views.view.application_search.yml, conf/cmi/views.view.application_search.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, public/themes/custom/hdbt_subtheme/translations/sv.po
* Translated application search
* Added application search a criteria that shows only current language items
* Changed kasko application period 
* `git checkout feature/AU-XX-viestintasivut2`
* `make fresh`
=> fix: AU-XX: Make some changes to viestintasivut

public/modules/custom/grants_handler/js/webform-additions.js, public/modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php
Missing bracket end to css selectors.
* `git checkout AU-XXX-css-selector-fix`
* `make fresh`
=> Fix: AU-XXX: Fix css selectors

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
User was redirected to compilation page even in rare case that integration fails to respond with 200 status.
Now user is left on the form with the values and they are shown an error message. Only succesful saves redirect to completion.
* Remove catch-all redirect
* Add error messages + translations.
* `git checkout feature/AU-747-application-errors-page`
* `make fresh`
* [x ] This PR does not need designers review
[AU-747]: https://helsinkisolutionoffice.atlassian.net/browse/AU-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-747: Remove redirect to compilation page in case of an error.

public/modules/custom/grants_metadata/grants_metadata.module
* Fix application time zones to show correct time
* `git checkout feature/AU-XX-timezones`
* `make fresh`
=> fix: AU-XX: fix application timezones

conf/cmi/language/fi/views.view.frontpage_news.yml, conf/cmi/language/fi/views.view.news_archive.yml, conf/cmi/language/sv/views.view.frontpage_news.yml, conf/cmi/language/sv/views.view.news_archive.yml, conf/cmi/views.view.frontpage_news.yml, conf/cmi/views.view.news_archive.yml, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiBlock.php
* Show only messages that are received from kasittelyjarjestelma in Oma asiointi -block
* Also translations to news page in this PR
* `git checkout feature/AU-848-uudet-viestit`
* `make fresh`
[AU-848]: https://helsinkisolutionoffice.atlassian.net/browse/AU-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU- 848: Show only messages that are received from kasittelyjarjestelma in Oma asiointi -block

public/modules/custom/grants_profile/grants_profile.services.yml, public/modules/custom/grants_profile/src/Controller/GrantsProfileController.php, public/modules/custom/grants_profile/src/Routing/RouteSubscriber.php
Users had a possibility to enter user page by accident e.g. clicking back button in the browser.
Alter relevant routes to redirect user to My Services page.
* `git checkout feature/AU-850-user-page`
* `make fresh`
=> fix: AU-850: Redirect user from user page to my service page

public/modules/custom/grants_handler/grants_handler.module
Add sanity check to prevent errors when javascript is being altered.
**You can test this before checking out**
Clear caches, after 2 page loads the errors will appear, this is due Drupal building javascript assets to cache etc. As we don't check if the key exists, we are adding barebone array with missing data.
* `git checkout AU-856-fix-php-warnings-undefined-group`
* `make fresh`
* [  ] Clear drupal caches and visit the site, no errors should appear on page loads 
[AU-856]: https://helsinkisolutionoffice.atlassian.net/browse/AU-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-856: Add check to javascript alter to prevent errors

public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php
* Display attachment validation errors inline.
* `git checkout AU-858-grant-attachment-inline-error`
* `make fresh`
[AU-858]: https://helsinkisolutionoffice.atlassian.net/browse/AU-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-858: Display grant attachment validation errors inline

conf/cmi/core.extension.yml, public/modules/custom/grants_handler/src/EventSubscriber/RedirectAfterLogoutSubscriber.php, public/modules/custom/openid_connect_logout_redirect/openid_connect_logout_redirect.info.yml, public/modules/custom/openid_connect_logout_redirect/openid_connect_logout_redirect.services.yml, public/modules/custom/openid_connect_logout_redirect/src/Service/RedirectService.php
Logout now applies also to tunnistamo in addition to Drupal.
I copied some magic by oskari and applied it in existing event subscriber.
* `git checkout AU-539-redirect-logout`
* `make fresh`
[AU-539]: https://helsinkisolutionoffice.atlassian.net/browse/AU-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-539 Redirect after logout

public/modules/custom/grants_handler/grants_handler.install
Update hook to remove configs of deleted modules
* `git checkout AU-770-remove-deleted-module-configs`
* `make fresh`
[AU-770]: https://helsinkisolutionoffice.atlassian.net/browse/AU-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-770: Add update hook to remove delete module configs

conf/cmi/field.field.node.service.field_bottom_content.yml, conf/cmi/user.role.grants_admin.yml
* Fix Grants Admin -rights and make Bottom content -field translatable
* `git checkout feature/AU-873-grants-admin`
* `make fresh`
[AU-873]: https://helsinkisolutionoffice.atlassian.net/browse/AU-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-873 & AU-876: fix Grants Admin -rights and make Bottom content -field translatable

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* Hide user links from login form
* `git checkout feature/AU-864-hide-user-links`
* `make fresh`
[AU-864]: https://helsinkisolutionoffice.atlassian.net/browse/AU-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-864: hide user links from login form

conf/cmi/block.block.grantsapplicationsfrontpageinfoblock.yml, conf/cmi/block.block.hdbt_subtheme_messages.yml
* Moves Status messages -block higher
* `git checkout feature/AU-870-messages-block`
* `make fresh`
[AU-870]: https://helsinkisolutionoffice.atlassian.net/browse/AU-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-870: move messages block higher

conf/cmi/language/fi/grants_metadata.settings.yml, conf/cmi/language/sv/grants_metadata.settings.yml
* Translate subvention types in confs
* `git checkout feature/AU-862-avustuslajien-kaannokset`
* `make fresh`
[AU-862]: https://helsinkisolutionoffice.atlassian.net/browse/AU-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-862: translate subvention types in confs

conf/cmi/core.extension.yml, conf/cmi/field.field.node.service.field_hakijatyyppi.yml, conf/cmi/field.field.node.service.field_industry.yml, conf/cmi/field.field.node.service.field_target_group.yml, conf/cmi/field.storage.node.field_hakijatyyppi.yml, conf/cmi/webform.webform.kuva_projekti.yml, public/modules/custom/grants_handler/src/EventSubscriber/CompanySelectExceptionSubscriber.php, public/modules/custom/grants_metadata/grants_metadata.module, public/modules/custom/grants_metadata/grants_metadata.services.yml, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/GrantsConverterService.php, public/modules/custom/grants_metadata/src/Plugin/DataType/DataFormatTrait.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
So yeah. No point doing custom component for these since they are normal form fields.
* Added activity fields as normal fields.
* Created data mappers for them
* Updated schema mapper a bit to use services as value callbacks as well
* `git feature/AU-993-activity-component`
* `make fresh`
[AU-923]: https://helsinkisolutionoffice.atlassian.net/browse/AU-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-993: Activity component that are normal fields

public/modules/custom/grants_applicant_info/src/ApplicantInfoService.php, public/modules/custom/grants_handler/grants_handler.module
* Removes page-specific hardcoded notifications and replaces them with dynamic ones.
* `git checkout feature/AU-899-kuva-projektihakemus-webform-hardcodes`
* `make fresh`
=> fix: AU-XX remove hardcoded notifications from forms

public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-asiointirooli-block.html.twig
* Changed asiointirooli-block's link to switch mandate in every role
* `git checkout feature/AU-795-asiointirooli-block`
* `make fresh`
[AU-795]: https://helsinkisolutionoffice.atlassian.net/browse/AU-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-795: Changed asiointirooli-block's link to 'switch mandate' in every role

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* When you logged in and didn't have asiointirooli selected, there was an error from trying to access index of `null`
* This changes that those errors don't happen.
* `git checkout feature/AU-XX-fix-errormessages-from-not-having-asiointirooli`
* `make fresh`
=> fix: AU-XX do some checking for arrays before accessing arrays

public/modules/custom/grants_handler/src/EventSubscriber/CompanySelectExceptionSubscriber.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
Grants handler did not force user applicant roles and the one selected on form. Now this is enforced, and only users with proper applicant roles can access given form.
* Add check to GrantsHandler to require matching applicant roles.
* `git checkout feature/AU-1000-grantshandler-roles`
* `make fresh` / `drush deploy` inside container
* Check that some form has only one role selected
* Select different role for user
* Try accessing the form that has not the user active role selected
* See that you're redirected to mandate form with an error message.
[AU-1000]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> feat: AU-1000: Make GrantsHandler respect applicant type for all users.

conf/cmi/core.extension.yml, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php
Hook to make language switch links work on edit application pages.
* `git checkout AU-847-application-edit-page-language-switch`
* `make fresh`
[AU-847]: https://helsinkisolutionoffice.atlassian.net/browse/AU-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-847: Allow language switcher to work on edit application pages

public/modules/custom/grants_handler/src/Form/MessageForm.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php, public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* `git checkout AU-994-tpr-link-fix?`
* `make fresh`
[AU-994]: https://helsinkisolutionoffice.atlassian.net/browse/AU-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-994: Service channel link cache , missing attachment description

public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
Sometimes the validation are not shown correctly to the user. This is due to the delta values for multi value address fields can be wrong (for example, often the first item has delta of `1`, not `0`)
Makes the deltas for multi value address fields consistent.
* `make fresh`
[AU-866]: https://helsinkisolutionoffice.atlassian.net/browse/AU-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-866: Validate addresses and display errors

conf/cmi/system.site.yml, public/modules/custom/grants_frontpage_info_block/templates/block--grants-frontpage-info-block.html.twig, public/modules/custom/grants_frontpage_info_block/translations/fi.po, public/modules/custom/grants_frontpage_info_block/translations/sv.po
* Remove dot from frontpage info block title
* Change site name to Avustusasiointi
* `git checkout feature/1019-etusivu`
* `make fresh`
[AU-1019]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1019: remove dot from frontpage info block title & change site name

conf/cmi/webform.webform.kuva_projekti.yml, public/themes/custom/hdbt_subtheme/templates/webform/webform-element-help.html.twig
* Fixed the tooltip to point at the correct element
* `git checkout feature/AU-950-tooltip-a11y-fix`
* `make fresh`
[AU-950]: https://helsinkisolutionoffice.atlassian.net/browse/AU-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-950: fix accessible tooltips

conf/cmi/language/fi/webform.settings.yml, conf/cmi/language/sv/webform.settings.yml
* Added translations to application preview warning message
* `git checkout AU-1014-warning-translations`
* `make fresh`
[AU-1014]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1014: Add translations to preview warning

public/themes/custom/hdbt_subtheme/src/scss/components/webform/_form_elements.scss
* Add max width to number element
* `git checkout AU-1005-number-fields`
* `make fresh`
[AU-1005]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1005: Add max width to number element

public/modules/custom/grants_mandate/grants_mandate.libraries.yml, public/modules/custom/grants_mandate/js/disable-mandate-submit.js, public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php, public/modules/custom/grants_mandate/templates/select-applicant-role.html.twig, public/modules/custom/grants_mandate/translations/sv.po
* Disabled submit-button in unregistered community if nothing is selected
* Change button text according to select value
* `git checkout feature/AU-1004-select-unregistered`
* `make fresh`
[AU-1004]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1004: fix Unregistered community in mandate

public/modules/custom/grants_handler/js/webform-additions.js, public/modules/custom/grants_handler/src/Element/BankAccountComposite.php, public/modules/custom/grants_handler/src/Plugin/WebformElement/BankAccountComposite.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php
Unregistered community has 2 fields in bank account data that other users do not have: Owner name & SSN. This adds those only for unreg community.
* Add account specs to data definition
* Add details to bank account composite
* Make things work
* `git checkout feature/AU-1034-account-details`
* `make fresh`
[AU-1034]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1034: Add support for bank account details for unreg community.

conf/cmi/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php
Anna arvo webformin boolean kentille perustuen toiseen kenttään. Tämä on tarpeen koska formilla on kenttiä joita ei talleteta ATV:hen.
Määritä webformextracter metodi ja tee siihen liittyen sopivat määrittelyt
* `git checkout feature/AU-1022-radiobuttons`
* `make fresh`
Kirjaudu sisään ja mene https://hel-fi-drupal-grant-applications.docker.so/fi/form/kuva-toiminta
Lomakkeen sivulla 2 paina kyllä Kyseessä on monivuotinen avustus radiobuttonille ja täytä kenttä  "Tulevat vuodet joiden ajalle monivuotista avustusta on haettu tai myönnetty".
Tallenna keskeneräisenä
Palaa lomakkeelle ja varmista että radiobutton on kyllä asennossa ja mainitussa kentässä on oikea arvo
Tyhjennä kenttä ja …
=> AU-1022 Handle dummy boolean fields in webform

public/modules/custom/grants_front_banner/templates/grants-front-banner.html.twig, public/modules/custom/grants_front_banner/translations/fi.po, public/modules/custom/grants_front_banner/translations/sv.po
* Added missing translation to front banner
* `git checkout feature/AU-935-translate-frontbanner`
* `make fresh`
[AU-935]: https://helsinkisolutionoffice.atlassian.net/browse/AU-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-935: add translations to front banner

public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaKehaDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php, tools/make/drupal.mk
* `git checkout AU-1033-budget-component-meta`
* `make fresh`
[AU-1033]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1033: Metadata to budget component generated data

conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/ApplicationHandler.php
Business purpose not required and is now editable. Prefill with profile data if found.
* `git checkout AU-865-businesspurpose-prefill-and-editable`
* `make fresh`
[AU-865]: https://helsinkisolutionoffice.atlassian.net/browse/AU-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-865: Make business purpose editable

public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/GrantsProfileService.php, public/modules/custom/grants_profile/src/TypedData/Definition/GrantsProfileRegisteredCommunityDefinition.php, public/modules/custom/grants_profile/templates/own-profile-registered-community.html.twig, test/tests/02__profile.robot
Deletes the company email in profile form for registered communities.
Deletes the company email field, definitions and tests.
* `make fresh`
[AU-1008]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1008: Delete company email

public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
* `git checkout AU-1045-premise-radio-translate`
* `make fresh`
[AU-1045]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1045: Fix premise radiobutton translations

public/modules/custom/grants_metadata/grants_metadata.module
* Show translations in webform third party settings
* `git checkout feature/AU-1028-third-party-translations`
* `make fresh`
[AU-1028]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1028: add translations to metadata

public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php, public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php, test/resources/common.resource, test/resources/dev-env-variables.resource, test/tests/02__profile.robot
Users should be redirected to oma asiointi on login
* Changed login redirects to point to oma asiointi
* Updated related tests
* `make fresh`
[AU-878]: https://helsinkisolutionoffice.atlassian.net/browse/AU-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-878: Login redirect user to oma asiointi

conf/cmi/grants_handler.settings.yml, public/modules/custom/grants_handler/config/install/grants_handler.settings.yml
* Translated status strings
* `git checkout feature/AU-1049-translate-status`
* `make fresh`
[AU-1049]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1049: translate status strings

conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml
* `git checkout AU-1059-budget-component-tooltips`
* `make fresh`
[AU-1059]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1059: Add tooltips to budget component fields on KUVA PROJ&TOIM

conf/cmi/webform.webform.yleisavustushakemus.yml
* Fixed misconfigured fileTypes (There was multiple fileType: 1 and some fileTypes was configured to wrong type
* `git checkout AU-922-fix-yleisavus-filetypes`
* `make fresh`
[AU-922]: https://helsinkisolutionoffice.atlassian.net/browse/AU-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-922: Fix misconfigured file types on yleisavus applcation

public/modules/custom/grants_handler/src/Element/CommunityOfficialsComposite.php
* remove parenthesis from contact person if no role
* `git checkout feature/AU-1083-remove-parenthesis`
* `make fresh`
[AU-1083]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1083: remove parenthesis if no role

conf/cmi/webform.webform.kuva_toiminta.yml
* Remove extra character from attachment description
* `git checkout feature/AU-1073-fix-liite`
* `make fresh`
[AU-1073]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1073: remove extra character from attachment description

conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
Disable premise type on KUVA PROJ & KEHA, as these won't use those fields.
* `git checkout AU-1087-disable-premisetype`
* `make fresh`
[AU-1087]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1087: Disable premise type from kuva proj and keha

public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php, public/modules/custom/grants_budget_components/src/Plugin/WebformElement/GrantsBudgetBase.php
Get compensation budget value from subvention values.
* `git checkout AU-1089-budget-compensations-field-automatic-value`
* `make fresh`
[AU-1089]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1089: Get budget compensation value from subventions

composer.json, composer.lock, public/modules/custom/grants_metadata/src/AtvSchema.php
"Select2" library is not loaded correctly, causing the DOM to get stuck.
The URL format "//dist" is interpreted as "http://dist", so the DOM tries to load the script from "http://dist" and causes it to hang because it can't find that URL.
The malformed URL is caused by "select2" contrib module, which can't find the "select2" js library.
* Loaded "select2" js library via composer (per the instructions here: https://www.drupal.org/project/select2 )
* Fixed duplicate "drupal/autologout" patch definitions in composer.json
* `make fresh`
=> Load Select2 library in composer, autologout patches

public/modules/custom/grants_handler/src/ApplicationHandler.php
Remove duplicate `application_language`, as there is already `language`
* `git checkout AU-1082-remove-duplicate-lang-field`
* `make fresh`
[AU-1082]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1082: Remove unused duplicate application language field

public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetOtherCost.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetOtherIncome.php, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
* Handle composite multi values errors little bit better
* `git checkout AU-1072-multivalue-errors`
* `make fresh`
[AU-1072]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1072: Fix multivalue fields error displays

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php
had been changed in form specs.
=> fix: AU-XX: Fix typo in definition

public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php, public/modules/custom/grants_profile/src/GrantsProfileService.php
Initially saved document got left hanging around if users cancels form. This is fixed here.
* Add initial save transaction id
* Delete document if transactionid is initially added one
* Redirect to mandate page
* Also limit validation errors on cancel button
* `git checkout feature/AU-1120-empty-profile-errors`
* `make drush-rebuild`
[AU-1120]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1120: Fix empty profile errors

conf/cmi/field.field.node.service.field_hakijatyyppi.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php, tools/make/project/avustusasiointi.mk
Block content goes through normal render process so it's translated properly. Title printed from title so the translation did not occur. This fixes it.
Also there was issue with field_hakijatyyppi which had been set to translatable, but it must not be so. We must have same selections for all servicepage nodes, no matter the language.
* Load translated block titles
* Remove translatability from field_hakijatyyppi
* `git checkout feature/AU-1136-ehtolohkon-title-kaannos`
* `make drush-rebuild`
[AU-1136]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1136: Fix block title translations

public/modules/custom/grants_handler/js/webform-additions.js
* DIsable form actions during ajax call.
* `git checkout AU-1133-disable-form-actions-during-ajax`
* `make fresh`
[AU-1133]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1133: Disable form actions during ajax call

public/modules/custom/grants_attachments/src/AttachmentHandler.php, public/modules/custom/grants_metadata/src/Plugin/DataType/GrantsAttachmentData.php
* Fix checkbox update selection not updating, if user changes this after draft saving.
* `git checkout AU-1161-fix-attachment-checkvalues-saving`
* `make fresh`
[AU-1161]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1161: Fix attachment checkbox updating

public/modules/custom/grants_handler/src/Plugin/WebformElement/CompensationsComposite.php
* Remove extra € from subventions in preview
* `git checkout feature/AU-1135-duplicate-euro`
* `make fresh`
[AU-1135]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1135: remove extra € from subventions in preview

conf/cmi/webform.webform.kuva_projekti.yml
* Remove conditional states that are from applicant types from the fields that have state changes that have to do with over/under `5000€` condition
* `git checkout feature/AU-1200-under-over-5000`
* `make fresh`
=> fix: AU-1200 - Under/over 5000E sums affect all hakijatyyppi

conf/cmi/language/en/views.view.application_search.yml, conf/cmi/language/sv/views.view.application_search.yml, conf/cmi/views.view.application_search.yml
* Change avustuslaji from entity reference filter to regular filter
* `git checkout feature/AU-1165-dropdown`
* `make fresh`
[AU-1165]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1165: fix Avustuslaji in application search

conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php, public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php, public/modules/custom/grants_budget_components/src/TypedData/Definition/GrantsBudgetInfoDefinition.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
* Changed static budget components from multivalue -> single
* This fixes huge margins on budget components
* `git checkout AU-1163-static-budget-components-to-non-multivalue`
* `make fresh`
[AU-1163]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1163: Change static budget components to non multivalue

public/modules/custom/grants_handler/src/Element/BankAccountComposite.php, public/modules/custom/grants_metadata/src/AtvSchema.php
Bank account owner info (name, ssn) did not have metadata attached to them.
* Added additional logic in `AtvSchema` to handle bank account owner info
* Added titles to bank account owner info, for displaying in metadata
* `make fresh`
[AU-1068]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1068: Handle bank account owner info metadata

conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, public/themes/custom/hdbt_subtheme/templates/webform/webform-element-base-html--date.html.twig
* Added Twig-file to format dates in application preview
* `git checkout feature/AU-1029-date-format`
* `make fresh`
[AU-1029]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1029: format date in preview

public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php, public/modules/custom/grants_metadata/tests/data/yleisavustushakemus.data.json, public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php
Hide unnecessary/confusing data from end users.
Include hidden status in metadata sent to ATV.
Take that into account in print phase
Update tests
* `make fresh`
[AU-1077]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1077: Hide fields in print

public/modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php
* Add roles back to yhteenveto
* `git checkout feature/AU-1198-fix-missing-roles`
* `make fresh`
[AU-1198]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1198: fix: AU-1198: Add missing roles back to submission display

public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Lisätään ohjeistus hakuprofiililomakkeen alkuun: Täytä kaikki kentät, tarkista tietojen oikeellisuus ja tallenna lopuksi.
* `git checkout feature/AU-1243-info-for-profile-form`
* `make fresh`
[AU-1243]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1243 add info in beginning of profile forms

public/modules/custom/grants_oma_asiointi/src/Plugin/Derivative/DynamicLocalTasks.php, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_oma_asiointi/translations/sv.po
* Change text in oma asiointi tabs
* Changed menu links in production
* `git checkout feature/AU-1241-omat-tiedot`
* `make fresh`
[AU-1241]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1241: change text in Oma asiointi tabs

conf/cmi/grants_handler.settings.yml, conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, public/modules/custom/grants_handler/translations/sv.po
* KH Yleisavustus changes:
* [Removed unnecessary text bit](https://helsinkisolutionoffice.atlassian.net/browse/AU-1235)
* [Changed the way character counter was displayed on page 4](https://helsinkisolutionoffice.atlassian.net/browse/AU-1237)
* [Fixed translations of states and state display](https://helsinkisolutionoffice.atlassian.net/browse/AU-1238)
* `git checkout feature/AU-1235-1237-1238-yleisavustus-changes`
* `make fresh`
* Disable config ignore for webform.webform.*
* `make drush-cim`
=> feat: AU-1235, AU-1237, AU-1238: Yleisavustuslomake changes

composer.lock, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Some fields were not translated in webform print view.
* Added custom logic to apply translations to title and descriptions
* `make fresh`
[AU-1213]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1213: Missing webform print translations

public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php
Use relative path.
Check that tests are run properly in server environments
[AU-1276]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1276: Use relative path for tietoliikenne schema in ATV tests

public/modules/custom/grants_frontpage_info_block/translations/sv.po
* Add correct sv traslation to kasko in info banner
* `git checkout feature/AU-1267-sv-kasko`
* `make fresh`
[AU-1267]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1267: Add correct sv traslation to kasko in info banner

public/modules/custom/grants_handler/templates/application-list.html.twig
* Remove duplicate title from drafts
* `git checkout feature/AU-1263-double-title`
* `make fresh`
[AU-1263]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1263: Remove duplicate title from drafts

public/modules/custom/grants_attachments/grants_attachments.routing.yml, public/modules/custom/grants_handler/grants_handler.routing.yml, public/modules/custom/grants_handler/src/Controller/MessageController.php, public/modules/custom/grants_metadata/grants_metadata.routing.yml, public/modules/custom/grants_webform_print/grants_webform_print.routing.yml
There was some endpoints with inadequate access checking. This adds access checks to those endpoints.
* Some routing.yml files was changed
* Only one endpoint needed changing.
* `git checkout feature/AU-1232-access-hook-check`
* `make fresh`
[AU-1232]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1232: Add access checks to custom endpoints.

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/en/webform.webform.nuorlomaleir.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/sv/webform.webform.nuorlomaleir.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaPerusDefinition.php
* Translate webform titles
* `git checkout feature/AU-1298-title-translations`
* `make fresh`
[AU-1298]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1298: translate webform titles

public/modules/custom/grants_premises/src/Element/PremisesComposite.php
* Premises Composite states fix
* `git checkout feature/AU-1290-states`
* `make fresh`
[AU-1290]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1290: Fix Premises States

conf/cmi/field.storage.node.field_hakijatyyppi.yml, conf/cmi/grants_metadata.settings.yml, conf/cmi/language/fi/grants_metadata.settings.yml, conf/cmi/language/sv/grants_metadata.settings.yml, public/modules/custom/grants_handler/config/install/field.storage.node.field_hakijatyyppi.yml, public/modules/custom/grants_mandate/js/disable-mandate-submit.js, public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php, public/modules/custom/grants_mandate/translations/fi.po, public/modules/custom/grants_mandate/translations/sv.po, public/modules/custom/grants_metadata/config/install/grants_metadata.settings.yml, public/modules/custom/grants_profile/js/profile_dialog.js, public/modules/custom/grants_profile/src/TypedData/Definition/GrantsProfileUnregisteredCommunityDefinition.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Change the way unregistered company is written on site in all three languages.
* `git checkout feature/AU-1281-unregistered-community-text`
* `make fresh`
* `make drush-gwi`
[AU-1281]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1281: Change Unregistered community to unregistered community or group

public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
This pull request implements changes to the `WebformImportCommands.php` file. These changes make it possible to import both English and Swedish Webform translations.
* `git checkout feature/AU-1272-webform-translations-import`
* `make fresh`
After your environment is up and running, go and make changes to any `webform.webform.*` files in either the `/cmi/language/en` or `/cmi/language/sv` directory. These changes should simulate a change in the translations. 
For example, change the values in `/cmi/language/en/webform.webform.kuva_projekti.yml`
from
```
elements: |
1_hakijan_tiedot:
'#title': '1. Applicant details'
'#prev_button_label': '< Previous'
'#next_button_label': 'Next >'
```
to
```
elements: | …
```
=> Feature/AU-1272: Webform translations import

conf/cmi/language/en/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* [AU-1361](https://helsinkisolutionoffice.atlassian.net/browse/AU-1361): Remove extra info text from grants
* [AU-1362](https://helsinkisolutionoffice.atlassian.net/browse/AU-1362): Move text from description to tooltip
* `git checkout feature/AU-XX-liikunnan-yleis`
* `make fresh`
[AU-1361]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1362]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1361, AU-1362: fix liikunnan yleisavustus

conf/cmi/language/en/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
* [AU-1364](https://helsinkisolutionoffice.atlassian.net/browse/AU-1364): fix grant text
* [AU-1365](https://helsinkisolutionoffice.atlassian.net/browse/AU-1365): fix text in verbal explanation field
* `git checkout feature/AU-XX-nuoriso-palkkaus`
* `make fresh`
[AU-1364]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1365]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1364, AU-1365: fix nuoriso palkkaennakko

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/templates/grants-handler-completion.html.twig, public/modules/custom/grants_handler/translations/sv.po
* Add print button to completion page
* `git checkout feature/AU-1289-kiitossivu`
* `make fresh`
[AU-1289]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1289: add print button to completion page

conf/cmi/webform.webform.kuva_projekti.yml, public/modules/custom/grants_applicant_info/src/ApplicantInfoService.php, public/modules/custom/grants_applicant_info/src/Plugin/WebformElement/ApplicantInfoComposite.php, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php, public/modules/custom/grants_profile/grants_profile.module, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php, public/modules/custom/grants_profile/src/GrantsProfileService.php, public/modules/custom/grants_profile/templates/own-profile-unregistered-community.html.twig, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
After toimintaryhmä changes, address data was left off from the JSON, this adds it back plus some other small fixes.
* Address info is taken from default address in profile
* ContactPerson is set to user details from communtiy officials. From "responsible person role"
* Grants profile for toimintaryhmä must include one "responsible person" role
* Email & phone number for application are taken from this responsible person
* `git checkout feature/AU-1369-toimintaryhma-ongelmat`
* `make fresh` && `drush gwi`
[AU-1369]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1369: Fix some toimintaryhma issues

conf/cmi/webform.webform.kasko_ip_lisa.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorlomaleir.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
Community official were not visible on preview pages. Probably due to applicant_type value is not present there. As fast and dirty fix I just swapped the conditions so that if applicant_type is NOT private_person, then we show the element. Should work?
* swapped the conditions so that if applicant_type is NOT private_person, then we show the element.
* manually hid the officials element for private person in theme hook
* `git checkout UHF-feature/AU-1358-missing-officials-preview`
* `make fresh` && `make drush-gwi`
[AU-1358]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1358: Update community officials element visibility.

public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Element/CommunityOfficialsComposite.php
There's some strange issues with applications going to get assigned for incorrect ytunnus, and this is a try to tackle that. By adding applicant info details to applications in init phase.
=> fix: AU-XX: Initialize applicant info when document is created.

composer.json, composer.lock
This should fix automatic tests and show green light. (Hopefully)
See: https://github.com/City-of-Helsinki/drupal-module-helfi-audit-log/pull/8
=> AU-xxx: Maybe fix automatic tests(?)

public/modules/custom/grants_handler/src/Element/CommunityAddressComposite.php
* Remove duplicate error display.
* `git checkout feature/AU-1383-fix-duplicate-error-message`
* `make fresh`
[AU-1383]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1383: Remove duplicate error message from the first page of application

conf/cmi/webform.webform.liikunta_tapahtuma.yml
* `git checkout feature/AU-1385-liikuntatapahtuma-years`
* `make fresh`
[AU-1385]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1385: Change liikunta tapahtuma acting years

public/modules/custom/grants_metadata/src/AtvSchema.php
Translate attachments fields for print view
Attachments must be handled in a special way in order for translations to work. Comments added between code.
* `git checkout feature/AU-1343-attachment-field-translations`
* `make fresh`
Fill an application in Finnish and save it as a draft. Include at least one attachment or bank account.
View the application in print view. Fields for attachments are now in Finnish. 
[AU-1343]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1343 Translate attachment field labels for print view

public/modules/custom/grants_handler/src/ApplicationHandler.php
There may be some situations where integration fails to save application data and it may even not be queued properly and so the data could be lost. This is not acceptable. 
This tries too-easy-to-believe method of just calling the ATV saving method before sending it to integration
So the fix is hopefully this simple, but we must test repercussions of this thoroughly. That's why this is left unmerged for now. 
* Simply save data to ATV before saving it via integration
* `git checkout feature/AU-1233-sate-first-to-atv`
* `make fresh` && `make drush gwi`
[AU-1233]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> fix: AU-1233: Save application to ATV before sending it to integration

public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
* Use webform's translation interface instead of symphony's in GrantsWebformPrintController
* `git checkout feature/AU-1411-printti-rikki`
* `make fresh`
[AU-1411]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1411: Use correct translationinterface in print page

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/templates/application-list-item.html.twig
* Allow application to be modified if status is withing parameters, but application is no longer open.
**(Further webform status checks to implemented later)**
* `git checkout feature/AU-1406-application-changes-while-period-over`
* `make fresh`
[AU-1406]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1406: Allow submitted application to be edited when application period is closed

conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml
* move a description in a form to a proper place
* `git checkout feature/AU-1377-description-location`
* `make fresh`
* `make drush-gwi`
[AU-1377]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1377: Move description to before in Liikunta yleis

conf/cmi/language/en/webform.webform.liikunta_tapahtuma.yml, conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml, conf/cmi/webform.webform.liikunta_tapahtuma.yml
* Tooltip fix
* `git checkout feature/AU-1380-tooltip-to-liikunnan-tapahtuma`
* `make fresh`
* Go remove webform confs from config ignore in the admin interface
* Run `make drush-cim`
[AU-1380]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1380: add tooltip to liikunnan tapahtuma

conf/cmi/language/en/field.storage.node.field_hakijatyyppi.yml, conf/cmi/language/sv/field.storage.node.field_hakijatyyppi.yml
* Add translations to applicant
* `git checkout feature/AU-1422-applicant-translations`
* `make fresh`
[AU-1422]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1422: add translations to applicant

public/modules/custom/grants_handler/grants_handler.module
* Added check if application is continous to the list view on profile page
* `git checkout feature/AU-1438-continous-expired-bug`
* `make fresh`
[AU-1438]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1438: Make so that continuous applications are not expired in list

public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Fixed a malformed swedish translation string and made the finnish version match the way the other languages were written.
* `git checkout feature/AU-XX-fix-translation-bug`
* `make fresh`
=> fix: AU-XX: fix malformed translation string

public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php, public/modules/custom/grants_metadata/src/AtvSchema.php
Hakijan tiedot komponentin käännökset tulostusnäkymässä
* Käsittele data ATVSchema luokassa
* `git checkout Ufeature/AU-1277-applicant-translations`
* `make fresh`
- Täytä lomake ja tallenna se draft-tilassa
- Avaa tulostusnäkymä
- Varmista että hakijan tiedot -osiossa kenttien nimet ovat käännetty
[AU-1277]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1277: Handle translations for applicant details

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaPerusDefinition.php
Wrong mapping caused realized premises to disappear after sending to avus2
* `git checkout feature/AU-1458-fix-kuva-perus-premise-mapping`
* `make fresh`
(Previously this data will disappear)
[AU-1458]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1458: Fix KUVA Perus realized premises mapping

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Change notification text about required fields
* `git checkout feature/AU-1427-notification-text`
* `make fresh`
[AU-1427]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1427: change notification text about required fields

composer.json, composer.lock
Helfi audit log module update.
* `git checkout feature/AU-1448-audit-log-update`
* `make fresh`
[AU-1448]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature: AU-1448: Audit module update for grants project

public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
This pull request implements a fix for the` WebformImportCommands.php` drush command. Previously, a Webform that did not have any existing translations would not get its translations imported when the command was run. Now, the translations get imported even if no translations exist from before.
* `git checkout fix/AU-1477-translation-import-fix`
* `make fresh`
Run the command `drush gwi `and check that all the translations get imported successfully.
[AU-1477]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1477: Fixed an issue with Webfrom translation importing

public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php
* FIx Registration Date on form
* `git checkout feature/AU-1472-registration-date-format`
* `make fresh`
[AU-1472]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1472: Correct format for date on application form

composer.json, composer.lock, conf/cmi/core.extension.yml
Somehow our custom endpoints for health checks respond with incorrect response code when in maintenance mode. This tries to fix that by installing contrib health_check module.
* Custom module disable
* Contrib module update & enable
* `make fresh`
[AU-1490]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1490: Disable custom health_check module

conf/cmi/language/en/webform.webform.liikunta_tapahtuma.yml, conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml
* Fixed button translations in liikunta tapahtuma
* `git checkout feature/AU-1391-buttons`
* `make fresh`
[AU-1391]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1391: fix liikunta tapahtuma buttons

public/modules/custom/grants_handler/grants_handler.module
* The lisätiedot ja liitteet error that happened when the new notification about required fields was displayed is fixed.
* `git checkout feature/AU-1475-fix-ajax-file-errors`
* `make fresh`
[AU-1475]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1475: fix the AJAX attachment thing with form_alter before the hierarchy is changed

public/modules/custom/grants_webform_summation_field/src/Element/GrantsWebformSummationField.php
* Avustukset Summa -field is now hidden if set to hidden
* `git checkout feature/AU-1474-hide-avustukset-summa`
* `make fresh`
[AU-1474]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1474 change hidden avustukset-summa to a hidden field instead of display:none

public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php
* Removed title from a hidden field to make it disappear from preview
* `git checkout feature/AU-1457-applicant-type-translation-in-preview`
* `make fresh`
[AU-1457]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1457: Hidden fields do not need titles if they are not to be displayed on preview

public/modules/custom/grants_handler/src/Element/CommunityOfficialsComposite.php
* Hardcode into the Community Official component that always forces it to be required when with Unregistered community and not required if not.
* `git checkout feature/AU-1256-required-field-for-unregistered`
* `make fresh`
[AU-1256]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1256: unregistered community always has required Community Officials and other roles don't

public/modules/custom/grants_handler/grants_handler.module
* Notification is no longer inside the checkbox element at the bottom of the preview page
* `git checkout feature/AU-1496-accept-terms-checkbox`
* `make fresh`
[AU-1496]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1496: Move notification outside of checkbox in preview page

public/modules/custom/grants_metadata/grants_metadata.module
This pull request implements a minor change to the `hook_webform_presave` hook in `grants_metadata.module`. The change makes it so that a new node revision is automatically created when a node is saved after Webform configurations have been imported.
* `git checkout fix/AU-1544-config-import-node-revision`
* `make fresh`
- Run `drush gwco`. Check that a service page whose Webform was updated has a new revision.
- Wait a minute or so and run `drush gwi`. Check that a service page whose Webform was updated has a new revision.
[AU-1544]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1544: Create node revision on Webform config import

public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
This pull request implements a minor change to the "**Grants premises**" component. The length of the postal code in said component was never check in any way. The implemented change checks the postal codes formatting and length.
* `git checkout fix/AU-1488-grants-premises-postal-code`
* `make fresh`
- Login as a test user and go to the "**Taide- ja kulttuuriavustukset, taiteen perusopetus**" form.
- Find the postal code field on pages 3 and 4, and check that you can only enter a valid postal code (FI-12345 or 12345). 
[AU-1488]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix/AU-1488: Added postal code checking to the grants premises component

conf/cmi/grants_metadata.settings.yml, conf/cmi/webform.webform.nuorlomaleir.yml, public/modules/custom/grants_handler/config/install/webform.webform.nuorlomaleir.yml, public/modules/custom/grants_metadata/config/install/grants_metadata.settings.yml
* "Nuorisotoimi, loma-aikojen leiriavustushakemus: Muutetaan hakemuksen nimi Nuorisotoiminta, loma-aikojen leiriavustushakemus"
* `git checkout feature/AU-1485-change-name-of-loma-aikojen-leiriavustushakemus`
* `make fresh`
[AU-1485]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1485: change name of Nuorisotoimi to Nuorisotoiminta

conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.nuorlomaleir.yml, public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php
and add check for required attachment field value
* Removed delivered later / included in other file selection for attachments in NUORISO forms.
* Made Attachment required in those form and added additional validation for such us case.
* `git checkout feature/AU-1552-nuoriso-attachment-requirements`
* `make fresh`
[AU-1552]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1552: Remove delivered later / in other file from NUORISO forms

conf/cmi/language/en/webform.webform.liikunta_tapahtuma.yml, conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml, conf/cmi/webform.webform.liikunta_tapahtuma.yml, public/modules/custom/grants_metadata/src/TypedData/Definition/LiikuntaTapahtumaDefinition.php
* Fixed radiobutton values to 0 / 1 instead of Kyllä / Ei
* `git checkout feature/AU-1562-boolean-field-values`
* `make fresh`
[AU-1562]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix. AU-1562: Fix Liikunta Tapahtuma radiobutton values to booleans

composer.json, patches/search_api_primary_key.patch
* Patch for search_api module. Platform is using Invisible Primary Keys if table is created without PKs and search_api is trying to add these afterwards.
=> fix: AU-xxx: Search api primary key patch

public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
This pull request implements a minor fix for "Application search" links on user profiles. 
* `git checkout fix/AU-1566-profile-link-fix`
* `make fresh`
[AU-1566]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1566: Fixed profile links for the application search

conf/cmi/webform.webform.liikunta_tapahtuma.yml, public/modules/custom/grants_metadata/grants_metadata.module, public/modules/custom/grants_metadata/src/Validator/EndDateValidator.php, public/modules/custom/grants_metadata/translations/override/fi.po, public/modules/custom/grants_metadata/translations/override/sv.po, public/themes/custom/hdbt_subtheme/dist/js/restrictedDatepicker.min.js, public/themes/custom/hdbt_subtheme/hdbt_subtheme.libraries.yml, public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme, public/themes/custom/hdbt_subtheme/src/js/restrictedDatepicker.js
This pull request implements date validation to the `Liikunta tapahtuma-avustushakemus` Webforms `alkaa` and `paattyy`  date fields. The selected dates can no longer be set to dates in the past, and the "end date" field has to have a date that is the same or greater than the start date.
* `git checkout feature/AU-1556-date-field-logic`
* `make fresh`
- Import the form configurations with `drush gwi`.
- Open up the forms with `drush gwco`.
- Test the `Liikunta tapahtuma-avustushakemus` Webforms `alkaa` and `paattyy` date fields.
[AU-1556]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat:AU-1556: Added date validation to the Liikunta tapahtuma-avustushakemus Webform

public/modules/custom/grants_place_of_operation/src/Element/PlaceOfOperationComposite.php, public/modules/custom/grants_place_of_operation/translations/fi.po, public/modules/custom/grants_place_of_operation/translations/sv.po, public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
This pull request changes the postal code error message displayed in the  "**Grants premises**" component.
* `git checkout fix/AU-1488-postal-code-error-message`
* `make fresh`
[AU-1488]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1488: Changes to the postal code error message

public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php
* `git checkout feature/AU-1568-registered-profile-form-change`
* `make fresh`
[AU-1568]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1568: Remove official requirement from registered profile form

public/modules/custom/grants_webform_import/src/Routing/JsonapiLimitingRouteSubscriber.php, public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
* GrantsWebformPrintController didn't translate select options, leading in Finnish text when printing select elements in urls like "/sv/tietoja-avustuksista/taide_ja_kulttuuriavustukset_tai/tulosta". Now they are translated.
* `git checkout feature/AU-XX-fix-preview-selects`
* `make fresh`
=> fix: AU-XX: Fix translation of select options on preview print page

conf/cmi/grants_metadata.settings.yml
* add translations to subvention types
* `git checkout feature/AU-1578-leiriavustus`
* `make fresh`
[AU-1578]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1578: add translations to subvention types

conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
* Dot was removed
* `git checkout feature/AU-1577-extra-dot`
* `make fresh`
[AU-1577]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1577: removed extra full stop from sentence

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_metadata/src/AtvSchema.php
Issuer name tieto ei latautunut näkyviin hakemusta katsoessa.
Tee kentän nimen muutos kun webform submission ladataan eikä form alter hookissa.
WebformDataExtracter käyttö on teknisesti mahdollista mutta koska ongelmakenttä on komposiitin sisällä ja ATVSchema hyödyntää kentän nimeä dataa mankeloidessa se vaatisi tätä toteutusta monimutkaisemman ratkaisun. 
* `git checkout feature/AU-1579-issuer-name-case`
* `make fresh`
Testaa lomakkeella jossa on 
[AU-1579]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1579: Handle issuer name case in submission load phase

conf/cmi/language/en/views.view.content.yml, conf/cmi/language/sv/views.view.content.yml, conf/cmi/views.view.content.yml, conf/cmi/views.view.kohderyhmat.yml
Sisällöntuottajien on helpompi löytää oikea sisältö
Lisää entiteettiviittausnäkymä kohdyryhmille ja käytä sitä kohderyhmäsuodattimen lisäämiseen SIsältö-näkymään.
* `git checkout AU-1581-target-group-filter`
* `make fresh`
Mene sisältönäkymään ja varmista että suodatin toimii järkevästi.
[AU-1581]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1581: Add target group filter for content view

public/modules/custom/grants_metadata/src/AtvSchema.php
IBM on tehnyt vähemmän kaunista koodia kuin on tarpeen.
Konfiguraatiomuutokset lomakkeille on tehty aiemmin ks. `git show 84a4fe597`
Poista tarpeeton koodi
* `git checkout feature/AU-1580-radios-code-removal`
* `make fresh`
Varmista että liikuntatapahtuma lomakkeet radionappulat toimivat edelleen.
[AU-1580]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1580 Remove unnecessary radios code

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_metadata/src/AtvSchema.php
This pull request implements a fix for the "**Oma asiointi**" application listing page. The pull request fixes an issue where corrupted ATV data would break the whole listing and not display any applications at all.
* `git checkout AU-1585-application-listing-fix`
* `make fresh`
To test this pull request you need to reach a state of "corrupted ATV data". If you data is already corrupted, then you can ignore these steps.
1. Checkout the branch `feature/AU-1465-nuoriso-toiminta-id63`.
2. Set the `APP_ENV` value to `localo` in the` local.settings.php` file.
3. Run `make fresh`.
4. Fill in and submit the form "**Nuorisopalvelu: toiminta- ja palkkausavustushakemus**" with the `210281-9988` & `Maanrakennus Ari …
=> fix: AU-1585: Application listin fix

public/modules/custom/grants_webform_summation_field/grants_webform_summation_field.module
* Added applicant_type to root of the webform so it can always be found where it should
* `make fresh`
[AU-1586]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1586: make applicant_type appear programmatically

conf/cmi/webform.webform.liikunta_tapahtuma.yml
* Removed javascript datepicker from liikunnan tapahtuma-avustus
* `git checkout feature/AU-1589-calender-liikunta`
* `make fresh`
[AU-1589]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1589: Remove datepicker from liikunnan tapahtuma-avustus

.github/workflows/update-config.yml
We have an issue with form configs & automatic updates since we use config ignore for webforms and the latest-sql creation does not really support that. 
This bypasses the latest-sql and installs site from scratch every config creation. 
This will slow down configs but should work with webforms.
=> AU-XX: Update config with site install commands

conf/cmi/webform.webform.kasko_ip_lisa.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/webform.webform.liikunta_tapahtuma.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.ymparistopalvelut_yleisavustus.yml, public/modules/custom/grants_handler/js/compensation-element.js
Add setting to enable JavaScript enforcement of 1 subvention per application to forms where there is a instruction text for that.
Also fixed a small problem with keyup event on read-only elements, which caused subvention element go out of sync state, while pressing buttons on such fields.
* `git checkout feature/AU-1591-limit-subventions`
* `make fresh`
[AU-1591]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1591: Limit subventions by javascript. 

public/modules/custom/grants_handler/src/Element/CompensationsComposite.php
Add a pattern to compensation element, so user can't add negative number etc.
* `git checkout feature/AU-1561-subvention-character-validation`
* `make fresh`
[AU-1561]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1561: Pattern to compensation component

public/modules/custom/grants_handler/templates/grants-handler-print-atv-document.html.twig
* Hakijan tyyppi was visible on print page, not anymore.
* `git checkout feature/AU-1606-nuorproj-hakemuksentyyppi`
* `make fresh`
[AU-1606]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1606: hide applicant type from print form

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php
* Remove duplicate/wrong VOS mappings.
* `git checkout feature/AU-1609-fix-duplicate-vos`
* `make fresh`
[AU-1609]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1609: Remove duplicated/wrong VOS mappings from KUVA Toiminta

conf/cmi/core.extension.yml, public/modules/custom/grants_logger/grants_logger.info.yml, public/modules/custom/grants_logger/grants_logger.services.yml, public/modules/custom/grants_logger/src/Logger/GrantsLogger.php
* Add overriden dblog class / service to include helsinki profiili ID to log messages.
* `git checkout feature/AU-1620-hpuid-to-logs`
* `make fresh`
[AU-1620]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1620: Add DbLog override class and service

conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/en/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/en/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/en/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/en/webform.webform.nuorlomaleir.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.ymparistopalvelut_yleisavustus.yml
* Changed text on buttons to match what it should be
* `git checkout feature/AU-1629-save-as-draft`
* `make fresh`
[AU-1629]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1629: change unfinished to saved

public/modules/custom/grants_handler/src/ApplicationHandler.php
Sekakieliset hakemukset tulostusnäkymässä
Tallenna hakemuksen kieli lomaketta tallennettaessa.
* `git checkout feature/AU-1590-application-language`
* `make fresh`
Aloita lomakkeen täyttäminen yhdellä kielellä ja viimeistele se toisella. Tallennuksen jälkeen koko lomake on tulostusnäkymässä viimeistelykielellä.
[AU-1590]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1590: Update application language during save phase

public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php, public/modules/custom/grants_profile/templates/own-profile-form-unregistered-community.html.twig, public/modules/custom/grants_profile/templates/own-profile-unregistered-community.html.twig, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Add help-text to community name field
* Add info text under title
* Change community -> community or group
* `git checkout feature/AU-1625-ohjeteksti`
* `make fresh`
[UHF-1625]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-1626]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1625]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1626]: …
=> fix: AU-1625, AU-1626: edit unregistered community profile texts

public/modules/custom/grants_profile/src/GrantsProfileService.php
This pull request adds a few decoding methods to the `GrantsProfileService.php` service class. The methods are used to decode various fields on a users profile.
* `git checkout fix/AU-1623-profile-name-fix`
* `make fresh`
[AU-1623]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1623: Decode profile content

public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
This pull request implements changes to the user profile forms. Previously, warnings were being thrown in situations where the forms tried to access either array indexes or variables that did not exist. These issues have been fixed.
* `git checkout fix/AU-1636-profile-page-fix`
* `make fresh`
- Login with a test user and test the profile form with all three user roles (registered, unregistered and private). Experiment with adding and deleting Addresses, Persons responsible for operations, and Bank account details. Check the Drupal logs and make sure that no warnings are thrown during your testing.
- Review the code.
[AU-1636]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1636?atlOrigin=eyJpIjoiNWRk …
=> fix: AU-1636: Profile page errors

public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Select in grants handler is now translated
* `git checkout feature/AU-1652-toiminnasta-vastaava-select`
* `make fresh`
=> fix: AU-1652 add context to translation of "Select"

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_projekti.yml
* A field in KUVA: Projekti was missing a counter.
* `git checkout feature/AU-1647-counter`
* `make fresh`
[AU-1647]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1647 add missing counter to kuva projekti

public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po, public/modules/custom/grants_oma_asiointi/src/Controller/ApplicationsListController.php, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_oma_asiointi/translations/sv.po
* Translation of "My applications" was in oma asiointi module, but used in grants_handler as well, moved the translation upwards in food chain to handler module that is a requirement for oma asiointi
* `git checkout feature/AU-XX-My-applications-translation`
* `make fresh`
[AU-1676]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1676: move translation of My applications from oma asiointi to handler (oma asiointi requires handler)

public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php, public/modules/custom/grants_profile/templates/grants-profile--basic-info--private-person.html.twig
* `git checkout feature/AU-1658-omat-tiedot-translate`
* `make fresh`
[AU-1658]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1658: remove context from unversal texts in unregistered community info

public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Add missing translation
* `git checkout feature/AU-1651-check-sender-translation`
* `make fresh`
[AU-1651]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1651: Missing translation for Applications Helsinki

public/modules/custom/grants_handler/src/ApplicationHandler.php
* `git checkout feature/AU-1649-budgetinfo-copy`
* `make fresh`
[AU-1649]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1649: Check copyable budget fields from definition class.

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
KuvaProjektiDefinition class was missing a webformDataExtractor for the premises field, this caused information to be displayed as "true/false" strings to the end user.
Added the missing setting, to fix this problem
* `git checkout feature/AU-1666-kuva-premise-missing-webform-extractor`
* `make fresh`
[AU-1666]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1666: Add webformDataExtracter to KuvaProjektiDefinition

conf/cmi/language/en/webform.webform.liikunta_suunnistuskartta_avustu.yml
* Suunnistuskartta had the default "save as unfinished" text, fixed to "save as draft"
* `git checkout feature/AU-1629-save-as-draft-to-one-more-form`
* `make fresh`
[AU-1629]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1629: Save as draft to suunnistuskartta

public/modules/custom/grants_handler/src/ApplicationHandler.php
* Sort applications lists that are sorted by status also by date
* `git checkout feature/AU-1684-draft-order`
* `make fresh`
[AU-1684]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1684: Sort DRAFT status list

conf/cmi/language/en/webform.settings.yml
* Previews are showing empty fields as `{Empty}` when browsing on EN side.
* Changed the empty string to be `-`.
* `git checkout feature/AU-1695-empty-string-change`
* `make fresh`
[AU-1695]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1695: Change EN empty_string setting to -

conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml
* Limit was configured by a mistake to Liikunta laitos webform, removed this.
* `git checkout feature/AU-1702-fix-subvention-limit`
* `make fresh`
[AU-1702]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1702: Liikunta laitos: Allow multiple subventions

public/modules/custom/grants_handler/templates/application-list-item.html.twig
* Add Application Number to Drafts in application list on profile page
* `git checkout feature/AU-1693-draft-id-to-list`
* `make fresh`
[AU-1693]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1693: Add application number to DRAFTs in List

public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Tyhjän lomakkeen näkymässä budjettikentät eivät näkyneet.
Kovakoodaa kentät GrantsWebformPrintController luokkaan.
* `git checkout feature/AU-1662-preview-fields`
* `make fresh`
Täältä näkee other income / other cost kentät vierekkäin:
https://hel-fi-drupal-grant-applications.docker.so/fi/tietoja-avustuksista/liikunta_tapahtuma/tulosta
Ja static kentät täältä:
https://hel-fi-drupal-grant-applications.docker.so/fi/tietoja-avustuksista/kuva_projekti/tulosta
[AU-1662]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1662 Budget components in print preview

conf/cmi/webform.webform.liikunta_tapahtuma.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.nuorlomaleir.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.yleisavustushakemus.yml
We have some forms that users have been editing in production, we also have many changes to published forms in pipeline. But we have opted not to update forms in production. 
This will lead some information loss when updating production forms. This will copy relevant configurations (3rd party settings) from production to version controlled configs.
[Here's ](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/811/files)PR created for discussion about changes and all changes [here](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/811/files) were approved as the ones we want to override in production, and this PR is for 3rd party settings.
After this is merged & deployed to production we can import all forms with gwia command.
* [Link to other …
=> AU-1683: Update form configs from production.

public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_place_of_operation/src/PlaceOfOperationService.php, public/modules/custom/grants_premises/src/GrantsPremisesService.php
Ei lähetellä epävalidia JSONia ympäriinsä
Laita json_encode-funktiolle sopiva flägi. Ääkköset pysyvät ääkkösinä eikä erityisiä enkoodauksia tarvita. 
* `git checkout feature/AU-1694-invalid-json`
* `make fresh`
Tällä ei ole suoraa vaikutusta Drupalin toimintaan. PHP on käsitellyt aiemmin itse luomansa JSONin kitinöittä.
JSONia voi tarkastella ATVSchemassa, tulostusvaiheessa tai vaikkapa suoraan ATV:ssä.
[AU-1694]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1694: Do not escape json for ATV

conf/cmi/webform.webform.kaupunginkanslia_tyollisyysavust.yml
* Työllisyysavustus can have multiple subvention types
* `git checkout feature/AU-1706-työllisyysavustus-multiple-subventions`
* `make fresh`
[AU-1706]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1706: Allow multiple subventions on Työllisyysavustus

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAuthBlock.php, public/modules/custom/grants_handler/templates/grants-service-page-block.html.twig, public/modules/custom/grants_preview_link/grants_preview_link.module, public/modules/custom/grants_preview_link/src/Plugin/Block/GrantsPreviewLinkBlock.php, public/modules/custom/grants_preview_link/templates/grants-preview-link.html.twig
* Moved the preview link from the link list to the new application box in the left panel of TPR page.
* `git checkout feature/AU-1701-preview-link-to-blue-box`
* `make fresh`
[AU-1701]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1701: move preview link to the blue box

public/modules/custom/grants_handler/js/compensation-element.js, public/modules/custom/grants_handler/src/Element/CompensationsComposite.php, public/modules/custom/grants_metadata/src/TypedData/Definition/LiikuntaTilankayttoDefinition.php
* Fix javascript logic with Liikunta tila application, that caused wrong fields to be blocked when there is a value in "Muiden liikuntaa edistävien yhteisöjen avustus".
* Add missing mapping for Hakijan tyyppi
* Validation fix.
* `git checkout feature/AU-1711-liikuntatila-fixes`
* `make fresh`
[AU-1711]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1711: Liikunta tilankäyttö fixes.

public/modules/custom/grants_handler/js/webform.form.unsaved.js, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* The modals when exiting form did not translate when context was set, removed context to get translations.
* `git checkout feature/AU-XX-fix-exit-form-translation`
* `make fresh`
=> fix: AU-XX: remove context from javascript prompts

public/modules/custom/grants_oma_asiointi/grants_oma_asiointi.module, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/AsiointirooliBlock.php, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-asiointirooli-block.html.twig
* Removed unused variables from asiointirooli-block
* Add class that indicates current role to asiointirooli-block
* `git checkout feature/AU-1714-asiointirooli-class`
* `make fresh`
[AU-1714]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1714: Add info on the role of the user to asiointirooli-block

conf/cmi/language/en/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.ymparistopalvelut_yleisavustus.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml, conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.ymparistopalvelut_yleisavustus.yml
* Add counter and character limit to yleisavustushakemus business purposes
* `git checkout feature/AU-1707-yleisavustus-toiminnan-kuvaus`
* `make fresh`
[AU-1707]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1707: yleisavustuksiin toiminnan kuvaus

public/modules/custom/grants_handler/src/Processor/NumberProcessor.php
* Fix PHP warning notices caused by NumberProcessor class on some webforms
* `git checkout feature/AU-xxx-fix-php-notices`
* `make fresh`
=> fix: AU-xxx: Fix PHP warning notices

public/modules/custom/grants_place_of_operation/src/Element/PlaceOfOperationComposite.php, public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_profile/grants_profile.libraries.yml, public/modules/custom/grants_profile/js/pattern_error.js, public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php, public/modules/custom/grants_profile/src/Plugin/Validation/Constraint/ValidPostalCode.php, public/modules/custom/grants_profile/src/Plugin/Validation/Constraint/ValidPostalCodeValidator.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
This pull request implements "pattern" validation to postal code fields on registered- and unregistered community user profiles. Since the `#pattern_error` attribute is functionality provided by the Webform module and not natively supported by HTML5, a custom `patternError` behavior has been created. The behavior scans for inputs with a `data-pattern-error` attribute, and displays an error message contained in said attribute if the input in question fails to validate against its pattern.
In addition to this, a static `$postalCodePattern` attribute has been added to the `ValidPostalCodeValidator` class. This attribute is now used across all postal code fields when performing the pattern validation.
* `git checkout …
=> fix: AU-1078: Postal code validation

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/templates/webform-submission-messages.html.twig, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Drafts were showing empty messages-box which can be confusing
* Added text to clarify
* `git checkout feature/AU-1727-messages`
* `make fresh`
[AU-1727]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1727: add text when you cant send messages

conf/cmi/grants_metadata.settings.yml, public/modules/custom/grants_orienteering_map/src/Element/OrienteeringMapComposite.php, public/modules/custom/grants_orienteering_map/src/TypedData/Definition/OrienteeringMapDefinition.php
* Fixed orienteering map component to allow decimals on the size field.
* Fixed data types
* `git checkout feature/AU-1703-fix-orienteering-application`
* `make fresh`
[AU-1703]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1703: Change size field to allow decimals and fix data types

public/modules/custom/grants_handler/js/webform-additions.js
Extend JavaScript logic a bit, to handle checkbox state when returning to edit attachments. Previously if 1 of the check boxes were checked and user returned to attachment section, the non-selected box didn't get disabled upon page load.
* `git checkout feature/AU-1206-attachment-checkbox-fix`
* `make fresh`
=> fix: AU-1206: Fix attachment checkbox states when editing draft

public/modules/custom/grants_metadata/grants_metadata.module
In some cases saving empty values will cause crash, when we try to sync updated settings to service page. (Due null not being right value to use DateTime with).
Added null checks and allowed updateing applicationPeriod to empty values, if both dates are empty.
* `git checkout feature/AU-1754-empty-date-crash`
* `make fresh`
You can validate the crash in Develop:
In this branch:
[AU-1754]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1754: Fix empty date field crashing webform configration saving in some cases

public/modules/custom/grants_metadata/src/TypedData/Definition/NuorisoToimintaDefinition.php
* Additional information field was disappearing after sending through integration due wrong mapping. Fixed this.
* `git checkout feature/AU-1775-fix-nuor-field-mapping`
* `make fresh`
[AU-1775]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1775: Fix incorrect mapping in NuorisoToimintaDefinition

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/templates/webform-submission-messages.html.twig, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Added text to message field so it wouldn't be so confusing
* `git checkout feature/AU-1780-message-text`
* `make fresh`
[AU-1780]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1780: add text in message field to closed and cancelled applications

public/modules/custom/grants_profile/templates/own-profile-private-person.html.twig
* Remove contexts from where contexts are not required.
* `git checkout feature/AU-1753-private-form`
* `make fresh`
[AU-1753]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1753: Translate private profile display page headers to Finnish

public/modules/custom/grants_premises/src/Element/RentedPremiseComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
* Fixed fields on NuorToimPalk to match excel
* `git checkout feature/AU-1788-vuokra-fields`
* `make fresh`
[AU-1788]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1788: Vuokra-avustus fields

public/modules/custom/grants_handler/js/webform.form.unsaved.js
* made the "target" into a "currentTarget" in the javascript that controls the navigate-away-from-forms-when-there-are-changes behaviour.
* `git checkout feature/AU-1795-undefined-response-url`
* `make fresh`
[AU-1795]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1795: Make it so that link forwarding works with links that have inner elements

conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
* Add missing tilankäyttöliite field
* Add some conditionals to the added field
* `git checkout feature/AU-1762-conditional-tilankaytto-liite`
* `make fresh`
[AU-1762]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1762: Tilankäyttö liite conditionality for tilankäyttöavustus

conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_projekti.yml, public/modules/custom/grants_premises/src/Element/PremisesComposite.php
* Made postal code in premises composite not be required by hardcode and made sure that forms have the correct required fields.
* `git checkout feature/AU-1785-postalcode`
* `make fresh`
[AU-1785]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1785: make post-code not required in Premises Composite

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/webform.webform.nuortoimpalkka.yml, public/modules/custom/grants_metadata/src/Plugin/DataType/NuorisoToimintaPalkkaData.php
* Nuortoimpalk now has correct title in all three languages
* `make fresh`
[AU-1826]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1826: nuortoimpalk titles (all languages)

conf/cmi/webform.webform.nuortoimpalkka.yml
* Remove unused Street Address from page 3 of nuortoimpalk
* `git checkout feature/AU-1822-remove-street-address-nuortoimapalk`
* `make fresh`
[AU-1822]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1822: Remove unused street address

conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/webform.webform.nuortoimpalkka.yml
* Add tooltip as per ticket
* `git checkout feature/AU-1823-tooltip-to-nuortoimpalk`
* `make fresh`
[AU-1823]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1823: Add tooltip to digital only on nuortoimpalk

public/modules/custom/grants_handler/grants_handler.module
* `git checkout feature/AU-1835-remove-target-blank`
* `make fresh`
[AU-1835]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1835: Remove target blank from own applications list

public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Add missing tranlsation
* `git checkout feature/AU-1815-grants-profile-creation-cancel-message`
* `make fresh`
[AU-1815]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1815: Add translations to Cancel Grants Profile Creation

conf/cmi/webform.webform.nuortoimpalkka.yml
* Make front page of Nuortoimpalk match other front pages
* `git checkout feature/AU-1829-nuortoimapalk-unregistered-frontpage`
* `make fresh`
[AU-1829]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1829: Bring first page of nuortoimpalk to match the other forms

conf/cmi/language/en/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/en/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml
* fixed missing previous translation from a couple of forms
* `git checkout feature/AU-1836-translation`
* `make fresh`
[AU-1836]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1836: translate "previous" to finnish and swedisn on form

public/modules/custom/grants_profile/grants_profile.module, public/modules/custom/grants_profile/src/Controller/GrantsProfileController.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/templates/grants-profile--basic-info--private-person.html.twig, public/modules/custom/grants_profile/templates/own-profile-private-person.html.twig, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Added new texts to private person own profile
* `git checkout feature/AU-1764-yksityishenkilo-profiili`
* `make fresh`
[AU-1764]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1764: new texts to private person profile

public/modules/custom/grants_handler/src/Form/MessageForm.php
* Validation error messages (Like empty messages, weren't show immediately and caused them to appear in another pages)
* Handle error messages in ajaxcallback
* `git checkout feature/AU-1813-lingering-message-validation-error`
* `make fresh`
**Validate the current problem** // Develop branch
**Validate the fix** 
[AU-1813]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1813: Fix ajax message errors lingering till new page load

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
* Fix kasko toiminta-avustushakemus title translations
* `git checkout feature/AU-1827-kasko-translations`
* `make fresh`
[AU-1827]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1827: fix kasko toiminta-avustus names

public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetOtherCost.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetOtherIncome.php, public/modules/custom/grants_handler/src/Element/CompensationsComposite.php
* Add maxlength limits to compensation and budget fields.
* `git checkout feature/AU-1799-budget-length-limit`
* `make fresh`
[AU-1799]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1799: Limit Budget and Compensation field lengths

public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php, public/modules/custom/grants_profile/translations/fi.po
Jos lisää vahingossa saman tilin profiilia muokatessa niin saa virheilmoituksen mutta tilinumeroa ei voi korjata.
* Mahdollista duplikaattiarvojen muokkaus.
* `git checkout feature/AU-1818-duplicate-bank-account-handling`
* `make fresh`
[AU-1818]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1818 Improve error handling of duplicate bank accounts

conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, public/modules/custom/grants_metadata/src/AtvSchema.php, public/themes/custom/hdbt_subtheme/translations/sv.po
* Translations
* `git checkout feature/AU-1820-fix-translations`
* `make fresh`
[AU-1820]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1820: fix translations on nuortoimpalk

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Form/CopyApplicationModalForm.php
* Copy application feature doesn't take into account if the application is open or not
* Add checks for that.
* `git checkout feature/AU-1847-disallow-copying-if-inactive`
* `make fresh`
[AU-1847]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1847: Add isApplicationOpen checks to copying

conf/cmi/webform.webform.ymparistopalvelut_yleisavustus.yml
* Remove single subvention type
* Change subvention type to excel spec:
Toiminta-avustus
Vuokra-avustus
Muu
* `git checkout feature/AU-1857-kymp-subvention-fix`
* `make fresh`
[AU-1857]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1856]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1857: Subvention type fixes for ymp: yleisavustus, remove single subvention limit

public/modules/custom/grants_handler/src/ApplicationHandler.php
* Sentry https://sentry.hel.fi/organizations/city-of-helsinki/issues/15388/?project=163&referrer=project-issue-stream is throwing a unhandled exception notifications.
When user has been logged automatically and then performs the login action in edit page 403, Drupal will memorize the url and redirect there, even though the user hasn't done a role selection.
* Throw CompanySelectException, so the subscriber can pickup the exception and redirect user to the mandate selection page.
* `git checkout feature/AU-1824-profile-unhandled-exception?`
* `make fresh`
[AU-1824]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
=> fix: AU-1828: Throw an exception if selectedCompany is empty during access check

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_projekti.yml
* Fixed translations in kuva projekti
* `git checkout feature/AU-1866-kuva-translations`
* `make fresh`
* IF NEEDED:
* Go to [Ignore](https://hel-fi-drupal-grant-applications.docker.so/fi/admin/config/development/configuration/ignore)
* Remove webform-line and save
* Run `drush cim` in shell
[AU-1866]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1866: fix kuva projekti translations

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_projekti.yml
* Fix kuva projekti budget translations
* `git checkout feature/AU-1885-kuva-projekti-budget`
* `make fresh`
[AU-1885]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1885: fix kuva projekti budget translations

public/modules/custom/grants_members/translations/fi.po, public/modules/custom/grants_members/translations/sv.po, public/modules/custom/grants_premises/src/Element/RentedPremiseComposite.php
* Translation fixes for nuortoimpalkka
* `git checkout feature/AU-1883-toiminta-ja-palkkausavustus-translations`
* `make fresh`
[AU-1883]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1883: nuortoimpalk translation fixes

conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
* Fixed missing Translations from Wizard Page labels
* `git checkout feature/AU-1889-page-numbers`
* `make fresh`
[AU-1889]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1889: page numbers

public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
Näytä lisätiedot hakemusta tulostaessa
Tee lisätietoja varten oma paikka tulostusnäkymään huolehtien että data on käyttökelpoista ilman riippuvuuksia webformiin.
* `git checkout feature/AU-1789-additional-information-in-print`
* `make fresh`
[AU-1789]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1789: Show additional information data in print view

public/modules/custom/grants_applicant_info/src/ApplicantInfoService.php
* No idea how AtvSchema::extractDataForWebForm with the correct keys gives an answer without ApplicantType for a profile, but this ignores the issue.
* `git checkout feature/AU-XX-fix-error-in-applicantinfo`
* `make fresh`
=> fix: AU-XX: Add key-exists type check to ExtractDataForWebform

conf/cmi/language/en/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml
* New Description to Liikunnan yleisavustus
* `git checkout feature/AU-1800-liikunta-help-text-for-startti`
* `make fresh`
[AU-1800]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1800: Add description to Liikunnan yleisavustus

conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, public/modules/custom/grants_metadata/src/TypedData/Definition/LiikuntaTilankayttoDefinition.php
* We [previously removed ](https://helsinkisolutionoffice.atlassian.net/browse/AU-1773)some fields from the form, but the definitions still exist and causes validation error when trying to send the final submit.
* Removed these definitions
* Removed vuosikokouksen pöytäkirja - attachment field
* `git checkout feature/AU-1899-fix-validation-error-on-submit`
* `make fresh`
[AU-1899]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1900]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1899: Remove definitions of previously removed fields and remove pöytäkirja attachment field

public/modules/custom/grants_premises/src/GrantsPremisesService.php
Korjaa käännösongelma liittyen premises-komponenttiin
Käsittele label tieto GrantsPremisesService-luokassa.
* `git checkout feature/AU-1851-handle-premises-translation-issue`
* `make fresh`
[AU-1851]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1851: Add label translations for premises component

conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/LiikuntaTilankayttoDefinition.php
* Make `Liikuntatiloista maksetut vuokrat` fields required, if applying for Tilankäyttöavustus
* Fixed missing input masks and some mappings
* `git checkout feature/AU-1759-liikunta-tila-conditional-requirement`
* `make fresh`
⚠ PHPCS virhe korjattu toisessa pullarissa, joten en viiti sitä jokaseen kopioida.
[AU-1759]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1759: Liikunta tilankäyttö: Make fields required if applying for tilankäyttöavustus

conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml
* Remove fields from laitosavustus
* `git checkout feature/AU-1875-liikunta-laitos-remove-field`
* `make fresh`
[AU-1875]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1875: remove fields from liikunta laitos

conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
* Added bold info to maksetut vuokrat in liikunta toiminta and tilankäyttö
* `git checkout feature/AU-1917-toiminta-infotext`
* `make fresh`
[AU-1917]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1917: Missing infos added to liikunta toiminta

conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml
* Previous button fixed for fi/sv in Asukasosallisuus, pienavustushakemus
* `git checkout feature/AU-1914-previous`
* `make fresh`
[AU-1914]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1914: fix missing translations asukaspien

conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml
* Fix applicant details -view for private person 
* `git checkout feature/AU-1915-asukaspien-yksityishenkilo`
* `make fresh`
[AU-1915]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1915: fix hakijan tiedot in asukaspien

public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php, public/modules/custom/grants_budget_components/src/Element/GrantsBudgetStaticBase.php, public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php, public/modules/custom/grants_budget_components/src/Plugin/WebformElement/GrantsBudgetBase.php, public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_handler/src/Element/CompensationsComposite.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KaskoToimintaDefinition.php
* Reorder personel side costs below salaries
* Fix print view to show all budget component fields that were fillable in form view.
* `git feature/AU-1910-budget-component-order-and-print`
* `make fresh`
**Re-order:** 
**Print view:**
⚠️ Case default code smells are fixed in different PR.
[AU-1910]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1909]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1910 Budget component order and print fixes

.github/workflows/update-config.yml
Automatic config updates wanted to override our forms, this is because we ignore forms from basic cim. This adds forced update for all forms.
[AU-1927]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1927: Add forced form import

composer.lock
ATV Module update to fix profile attachment uploading 
* `git checkout feature/AU-1928-atv-version-update`
* `make fresh`
[AU-1928]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1928: Update ATV to 0.9.16

public/modules/custom/grants_metadata/src/TypedDataToDocumentContentWithWebform.php
extractLabel  method signature tells that return type is string, but this might also be null in some edge-cases. Update signature.
* `git checkout feature/AU-1905-fix-label-crash`
* `make fresh`
[AU-1905]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1905: Change method signature to prevent crashes when label extraction fails

public/modules/custom/grants_metadata/src/TypedDataToDocumentContentWithWebform.php
We are now (after the major refactor) adding some empty elements, which we should not - as the integration doesn't like this. Add some empty array handling.
* `git checkout feature/AU-1931-filter-empty-array-fields`
* `make fresh`
[AU-1931]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1931 filter empty array fields from atv doc.

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
* Fix definition condition statement to check if value is 5001 or greater, as we show these fields only then amount is 5001 or higher, but currently we include the fields to atv doc when it's 5000 or higher.
* `git checkout feature/AU-1941-fix-kuva-toiminta-fields-atv-doc`
* `make fresh`
[AU-1941]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1941: Fix conditional toiminta fields appearing to atv doc on amount 5000

public/modules/custom/grants_handler/src/GrantsHandlerNavigationHelper.php
* Fixed error messages showing plaintext "html" in error messages
* Removed some dead code
* `git checkout feature/AU-1944-fix-html-in-error-messages`
* `make fresh`
[AU-1944]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1944: Fix error messages containing plain text html

public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php, public/modules/custom/grants_metadata/src/CompensationService.php
* A wrong if statement caused description to not show up for muu_liite attachments. Fixed this
* Fixed PHP warnings in NUOR TOIMPALKKA
* `git checkout feature/AU-1779-attachment-description`
* `make fresh`
[AU-1779]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1779: show attachment description in application view

conf/cmi/webform.webform.nuortoimpalkka.yml
* Add missing required attribute to `Käyttötarkoitus` subelement.
* Hid computed twig in submission page.
* `git checkout feature/AU-1946-nuor-palkka-fixes`
* `make fresh`
[AU-1946]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1948]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1946: AU-1948: Fix missing required field and hide computed twig 

public/modules/custom/grants_handler/src/ApplicationHandler.php
* Add try catch to getCompanyDocuments, so the application listing won't disappear due singular failure.
* `git checkout feature/AU-1950-fix-application-listing`
* `make fresh`
(Otherwise you may test LOCALOTEST & Default Nordea & Maanrakennus Ari Eero T:mi combination)
[AU-1950]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1950: Add try catch to getCompanyApplications and log error cases

conf/cmi/webform.webform.nuortoimpalkka.yml
* `git checkout feature/AU-1947-states-for-nuortoimpalkka`
* `make fresh`
[AU-1947]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1947: Fix states for paikat digital only nuortoimpalkka

public/modules/custom/grants_attachments/src/AttachmentHandler.php
Changed attachment comparison to fileType instead of description.
* `git checkout feature/AU-1958-fix-multiple-attachment-info`
* `make fresh`
---
[AU-1958]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1958: Fix attachment info multiplying on different language saves

public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php
It seems that our schema left out additionalInformation field altogether when it is left empty on the form. This is not specified as required field and it passes all validations @Avus2. Still, the field needs to be present or it won't show on some printed report in Avus2.
* Added empty default value for additionalInformation field so even when left empty on a form, the empty value will be used.
* Removed labels and unnecessary comments to satisfy SonarLinter.
* `git checkout feature/AU-1970-missing-additional-info`
* `make fresh`
[AU-1970]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1970: Missing empty additional Information field

public/modules/custom/grants_handler/templates/application-list.html.twig, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Add no applications -text
* `git checkout feature/AU-1963-no-applications`
* `make fresh`
[AU-1963]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1963: add no applications -text

conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.yleisavustushakemus.yml
* Add tooltip to kh yleisavustus
* `git checkout feature/AU-1236-kh-tooltip`
* `make fresh`
[AU-1236]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1236: add tooltip to kh yleisavustus

public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php
This pull request fixes an issue where an old bank account confirmation file would be displayed at the "Vahvista, esikatsele ja lähetä" page when the applications selected bank account had been changed.
The issue can be reproduced by the following steps:
1. Login with a test user.
2. Start filling in an application and select a bank account.
3. Save the application as a draft.
4. Edit the application and change the selected bank account.
5. Go to the page "Vahvista, esikatsele ja lähetä" and notice that the old confirmation file is displayed under the "Muu liite" section.
The problem exists because of the way attachments are handled; Attachments are only ever uploaded to ATV when the application is either saved as a draft, or when the application is submitted. Thus, the old confirmation …
=> fix: AU-1962: Hide old bank account confirmation files

public/modules/custom/grants_premises/translations/sv.po, public/modules/custom/grants_webform_print/grants_webform_print.module, public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php, public/modules/custom/grants_webform_print/templates/rented-premises-composite-print.html.twig
Näytä vuokrattavan tilan tiedot esikatselu näkymässä.
* Lisää komposiitille oma käsittely webform prints -moduulissa.
* `git checkout feature/AU-1955-rent-premise-in-print`
* `make fresh`
[AU-1955]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1955 Show rented premise component in print view

public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php
…
Currently if node is being update, the anon block clear cache in given service page, this causes some cache issues where preview link doesn't show up or update if a webform relation has been added / updates.
Add current node to cache tags so the block cache will invalidate when node is updated. 
* `git checkout feature/AU-1990-fix-anonblock-cache`
* `make fresh`
`
//$settings['cache']['bins']['render'] = 'cache.backend.null';
//$settings['cache']['bins']['page'] = 'cache.backend.null';
//$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
`
You can check the orignal in develop branch with same steps, but this time cache clear is required between saves. …
=> AU-1990: Add current node to cache tags in ServicePageAnonBlock to fix cache issues

public/modules/custom/grants_metadata/src/TypedDataToDocumentContentWithWebform.php
Old implementation of adding input mask data to meta field caused some problems with composite elements, where the input data would stay in later iterations of property item loop and cause values transform to incorrect ones.
**You can validate the problem in develop branch:**
* Open `TypedDataToDocumentContentWithWebform` class file
* Uncomment `InputmaskHandler::addInputmaskToMetadata` calls on lines 132 & 688
* Open a new [Nuorisopalvelu, toiminta- ja palkkausavustushakemus](https://hel-fi-drupal-grant-applications.docker.so/fi/form/nuortoimpalkka)
* Page 2 select Haen vuokra-avustusta
* Page 5: Enter data to `Vuokrattu tila`
* Save as draft
* Now the fields should contain incorrect data
* `git checkout …
=> AU-1961: Fix inputmask metadata

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Fix translation in closed application
* `git checkout feature/AU-1994-translation`
* `make fresh`
[AU-1994]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1994: fix translation in closed application

public/themes/custom/hdbt_subtheme/package-lock.json, public/themes/custom/hdbt_subtheme/package.json, public/themes/custom/hdbt_subtheme/src/js/common.js
* Updated Stylelint as per the snyk
* and dependents to make sure things still install and you can run stylelint
* `git checkout feature/AU-2011-snyk-03012024`
* `make fresh`
[AU-2011]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2011: SNYK update 3rd january (stylelint in theme)

public/modules/custom/grants_handler/grants_handler.module
* After reducing ATV calls, we won't parse messages in the message list (Object is missing messageStatus). Added parseMessages to message list, so we can get the up to date statuses
* `git checkout feature/AU-2010-fix-message-list-message-status`
* `make fresh`
[AU-2010]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2010: Parse messages in message list preprocess to get current statuses

public/modules/custom/grants_handler/src/FormErrorHandler.php, public/modules/custom/grants_handler/src/GrantsHandlerServiceProvider.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
* Webforms default behavior is to use Messenger to display errors, but as we have our own error handling / displaying system in place the default behaviour will cause 2 message boxes to appear, when the user clicks the "Preview" button.
Created an override FormErroHandler class, which will check existance of `#disable_inline_form_error_messages` and skip message display if needed.
* `git checkout feature/AU-1387-hide-inline-messanger-messages`
* `make fresh`
[AU-1387]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1387: Override FormErrorHandler, so we can remove errors added via messenger

public/modules/custom/grants_attachments/grants_attachments.libraries.yml, public/modules/custom/grants_attachments/grants_attachments.module, public/modules/custom/grants_attachments/js/pending-bank-account-confirmation.js
This pull request implements a feature that displays an "Upload pending" message under the "Other attachments" section on the confirmation page of any application. The message is displayed in the scenario where a user has selected a bank account on the first page of the application, but the bank accounts confirmation file has not yet been uploaded to ATV.
I've chosen to implement this feature using js. It was surprisingly difficult to implement this on the back-end without having to worry about any "dummy data" ending up in ATV. If you come up with a better approach/solution, then please feel free to share.
* `git checkout feature/AU-1988-initial-bank-account-confirmation`
* `make fresh`
1. Login with a …
=> feat: AU-1988: Initial bank account confirmation file message

conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
* Swedish/English wasn't working for all selects in the preview print view
* `git checkout feature/AU-2025-STEA-EU-translation-fixes`
* `make fresh`
[AU-2025]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2025: Select translations

conf/cmi/language/en/webform.webform.hyte_yleisavustus.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/en/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/en/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.ymparistopalvelut_yleisavustus.yml, conf/cmi/language/sv/webform.webform.hyte_yleisavustus.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml
* English and swedish translations for dropdowns fixed
* `git checkout feature/AU-2039-translation-additions`
* `make fresh`
[AU-2039]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2039: change confs translate non-translations

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/remove_http_headers.settings.yml
* Added and configure `remove_http_headers` module
* `git checkout feature/AU-789-remove-http-headers`
* `make fresh`
[AU-789]: https://helsinkisolutionoffice.atlassian.net/browse/AU-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-789: Add remove_http_headers module and config

public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php
* Currently the budget subvention sum field will drop decimal point and the field will display wrong number. (eg. 343,22 becomes 34322)
* Format the form value to satisfy inputMask
* `git checkout feature/AU-2054-calculated-sum-format-fix`
* `make fresh`
[AU-2054]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2054 Budget page calculated subvention sum fix

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Korjaa Teron raportoimat ongelmat hakemuksen esikatselunäkymässä. Tämä vuosilukuongelma on ainoa jonka löysin.
`acting_year`-kentän vaihtoehdot tuotetaan dynaamisesti ja esikatselunäkymässä tätä ei aiemmin huomioitu.
Ongelma ei siis liittynyt välimuisteihin.
* `git checkout feature/AU-2023-form-preview-issues`
* `make fresh`
[AU-2023]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2023: Form preview issues

public/modules/custom/grants_metadata/translations/sv.po
* Fix malformed translation file in grants_metadata
* `git checkout feature/AU-2065-grants_metadata-translation`
[AU-2065]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2065: Fix Swedish translation in grants_metadata

public/modules/custom/grants_place_of_operation/src/TypedData/Definition/PlaceOfOperationDefinition.php, public/modules/custom/grants_profile/src/Plugin/Validation/Constraint/ValidPostalCodeValidator.php
* Removed NotBlank constraint, as this field is not marked as required always (Example: KASKO: Toiminta-avustushakemus koululaisten iltapäivätoiminnan järjestäjille).
* Added if case for `""` string, as webform values might be null or empty string
* `git checkout feature/AU-2080-fix-postcode-validation`
* `make fresh`
[AU-2080]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2080: Remove constraint, as the postcode is not always required

conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
* Fixed typo on title and changed description
* `git checkout feature/AU-2082-tilankaytto`
* `make fresh`
[AU-2082]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2082: fix typo and change description

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/src/WebformSubmissionNotesHelper.php, public/modules/custom/grants_handler/tests/src/Kernel/DataConversionTest.php, public/modules/custom/grants_handler/tests/src/Kernel/WebformSubmissionNotesHelperTest.php
* We have some custom data saved to submissions notes field. Change this data handling to it's own helper class.
* `git checkout feature/AU-2052-submisison-notes-field-helper`
* `make fresh`
Maybe bit hard to test: but
[AU-2052]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2052: submisison notes field helper

conf/cmi/disable_messages.settings.yml
* Filter out default webform submission saved message on EN forms.
* `git checkout feature/AU-2107-disable-webform-submission-message?`
* `make fresh`
[AU-2107]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2107: Filter submission saved message in EN forms

conf/cmi/grants_handler.settings.yml, conf/cmi/grants_metadata.settings.yml
Translations for new statuses were missing, this adds them.
[AU-1056]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1056: Add translations for statuses

conf/cmi/block.block.sivunotsikko.yml
* news_item title in english was restored
* `git checkout feature/AU-2130-english-new-title`
* `make fresh`
[AU-2130]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2130: news item title

public/modules/custom/grants_club_section/src/TypedData/Definition/GrantsClubSectionDefinition.php, public/modules/custom/grants_metadata/src/GrantsConverterService.php
This pull request fixes an issue with the `Sport dropdown` selector in the `Club section composite element`. The element saves the translated version of a selected sport name in ATV. If a user goes back to an application that was previously saved as a draft and then changes languages, then the previously selected value won't work, since the stored value is in the wrong language.
After this change, the stored ATV value is converted back to the original, English version, and then returned to the select dropdown through the t() function, which translates the selected sport to the correct value.
* `git checkout feature/AU-2135-club-section-composite-bug`
* `make fresh`
- Start filling in the form `Liikunta, …
=> fix: AU-2135: Fixed sport name translations in the Club section composite element

conf/cmi/language/en/webform.webform.leiriselvitys.yml, conf/cmi/language/sv/webform.webform.leiriselvitys.yml
* `git checkout feature/AU-2137-translation-leiriselvitys`
* `make fresh`
[AU-2137]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2137: missing translations

public/modules/custom/grants_applicant_info/src/ApplicantInfoService.php, public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php
* Add checks to remove warnings in private person profile
* `git checkout feature/AU-2147-private-person-errors`
* `make fresh`
[AU-2147]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2147: add checks to remove error messages

docker/openshift/entrypoints/90-deploy.sh, public/modules/custom/grants_budget_components/src/TypedData/Definition/GrantsBudgetInfoDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/NuorisoLeiriSelvitysDefinition.php
* Remove default mappings, so the copy application function doesn't duplicate budget fields.
* Add little more logging to deployment script
* `git checkout feature/AU-2151-duplicate-budget`
* `make fresh`
[AU-2151]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix :AU-2151 Fix budget field from duplicating after copying an application.

conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.kuva_toiminta.yml
* Edit festival-field in KUVA toiminta
* `git checkout feature/AU-1175-toiminta-field`
* `make fresh`
[AU-1175]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1175: edit festival-field in KUVA toiminta

public/themes/custom/hdbt_subtheme/templates/views/views-view--application-search-search-api.html.twig
* Add Engel theme to the search page
* `git checkout feature/AU-2207-blue-search-page`
* `make fresh`
[AU-2207]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2207-blue-search-page

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php, public/modules/custom/grants_handler/templates/grants-service-page-block.html.twig, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Change service page block text when logged out
* `git checkout feature/AU-2126-service-page`
* `make fresh`
[AU-2126]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2126: change service page block text when logged out

e2e/playwright.config.ts, e2e/tests/global.setup.ts, e2e/tests/init.setup.ts, e2e/utils/data/application/application_data_29.ts, e2e/utils/data/application/application_data_48.ts, e2e/utils/data/application/application_data_52.ts, e2e/utils/data/application/application_data_53.ts, e2e/utils/data/application/application_data_54.ts, e2e/utils/data/application/application_data_56.ts, e2e/utils/data/application/application_data_57.ts, e2e/utils/data/application/application_data_58.ts, e2e/utils/data/application/application_data_60.ts, e2e/utils/data/application/application_data_61.ts, e2e/utils/data/application/application_data_62.ts, e2e/utils/data/application/application_data_63.ts, e2e/utils/data/application/application_data_64.ts, e2e/utils/data/application/application_data_65.ts, e2e/utils/data/application/application_data_66.ts, e2e/utils/data/application/application_data_68.ts, e2e/utils/data/application/application_data_69.ts, e2e/utils/data/application_data.ts, e2e/utils/debugging_helpers.ts, e2e/utils/env_helpers.ts, e2e/utils/form_variant_helpers.ts
This pull request implements the possibility to _disable form variants_ (e.g. `success`, `draft`, `wrong_values`) in the `.test_env` file. This allows for dynamic exclusion of specific tests based on configuration, avoiding the need to manually comment out tests in the application data files.
No need for this anymore!
- A `globalSetup` key has been added to the `playwright.config.ts` file. The key points to a `init.setup.ts` file, which allows us to run code before initializing any tests.
- The `readEnvFile` function has been moved to its own `env_helpers.ts` file.
- The logic for filtering out disabled form variants has been implemented in `form_variant_helpers.ts`. All application data is being run through `filterOutDisabledFormVariants` in `application_data.ts` before it is passed on …
=> feat: AU-2047: E2E - Added possibility to disable form variants

conf/cmi/language.negotiation.yml, conf/cmi/system.site.yml
* `git checkout feature/AU-2230-default-lang`
* `make fresh`
[AU-2230]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2230: default language back to fi

conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.kasko_ip_lisa.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/sv/webform.webform.liikunta_suunnistuskartta_avustu.yml, conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.nuorlomaleir.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml
* Translate Hakija in SV applications
* `git checkout feature/AU-2221-hakija`
* `make fresh`
[AU-2221]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2221: translate Hakija in SV applications

public/modules/custom/grants_handler/templates/grants-handler-completion.html.twig, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Change confirmation page text
* `git checkout feature/AU-2090-confirmation`
* `make fresh`
[AU-2090]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2090: change confirmation page text

public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php, public/modules/custom/grants_metadata/src/TypedData/Definition/NuorisoLomaDefinition.php
* Allow multivalue budget components to be saved without a value if explanation / label is filled.
* `git checkout feature/AU-2213-budget-component-fix`
* `make fresh`
[AU-2213]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2213: Allow budget explantion to be saved without a value

docker/openshift/entrypoints/20-deploy.sh, docker/openshift/entrypoints/90-deploy.sh
* Added check for ENV variable which allows skipping the deployments scripts
[AU-2234]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature: AU-2234: skip deployment script

public/modules/custom/grants_handler/templates/grants-handler-print-atv-document.html.twig, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* `git checkout feature/AU-2228-print-issues`
* `make fresh`
[AU-2228]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2228: Make javascript load after content has loaded

conf/cmi/user.role.grants_admin.yml
* Permission changes to allow grants_admins to access resend- & submitted applications pages.
* `git checkout feature/AU-2257-resend-permissions`
* `make fresh`
[AU-2257]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2257: Allow grants_admins to access resend page and submitted applications page

public/modules/custom/grants_oma_asiointi/translations/fi.po, public/themes/custom/hdbt_subtheme/translations/fi.po
* Remove outdated asiointikansio text from site
* `git checkout feature/AU-2297-remove-avustuskansio`
* `make fresh`
[AU-2297]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2297 remove asiointikansio -text from site

public/modules/custom/grants_profile/translations/sv.po
* Omissa tiedoissa tooltipissa Community purpose and forms of action - tämä on ruotsipuolella. Vaihdettiin tämä muotoon Gemenskapens syfte och handlingsformer  
* In omat tiedot edit, fixed the max 500 characters text for swedish
* `git checkout feature/AU-2254-change-translations`
* `make fresh`
[AU-2254]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2254: change swedish transation

public/modules/custom/grants_handler/grants_handler.module
* Add dummy setting via alter hook,  this could we our AJAX problems by making settings object always available in the AJAX response. 
* `git checkout feature/AU-2081-ajax-settings-problem`
* `make fresh`
[AU-2081]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2081: Add js_settings_build hook to force a setting to allways be available

public/modules/custom/grants_handler/templates/message-list.html.twig
* Removed an empty `<ul>` element from application view page ("/katso") if message list is empty.
* `git checkout feature/AU-2281-empty-ul`
* `make fresh`
[AU-2281]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2281: remove empty UL from messages list in /katso page

public/modules/custom/grants_place_of_operation/src/Element/PlaceOfOperationComposite.php
This pull request fixes an issue with the "Place of operation" components "free" field. Previously, a selected value of "No" would be de-selected when editing an application that was previously saved as a "draft". Now, the value stays selected.
* `git checkout feature/AU-2331-component-state-bug`
* `make fresh`
- Login with a registered community role and go to a [form](https://hel-fi-drupal-grant-applications.docker.so/fi/form/kasvatus-ja-koulutus-toiminta-av) that has the component.
- Go to page three (3), Fill in the section "Toimintapaikkojen perustiedot" and select "Ei" in the field "Toimintaa järjestetään kaupungin opetus-, sosiaali- tai nuorisotoimelta saaduissa maksuttomissa tiloissa".
- Save the form …
=> fix: AU-2331: Place of operation "free" state fix

conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.yleisavustushakemus.yml
* Remove useless info from khyleis
* `git checkout feature/AU-2313-khyleis`
* `make fresh`
[AU-2313]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2313: remove useless info from khyleis

public/modules/custom/grants_handler/src/GrantsHandlerNavigationHelper.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
Virheiden puutteellinen näkyminen lomaketta täytettäessä.
* Käytä ensimmäistä sivua oletuksena
* `git checkout feature/AU-2307-navigation-helper-bug`
* `make fresh`
[AU-2307]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2307: Fix navigation handler bug

public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php
Funktio-kutsu aiheuttaa booleanille virheen
* Siirrä funktiokutsu parempaan kohtaan koodissa.
* `git checkout feature/AU-2325-function-call-error`
* `make fresh`
* En keksinyt miten sentryssä nähdyn ongelman saisi toistettua oikeasti.
[AU-2325]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2325: Avoid function call without actual object

public/modules/custom/grants_place_of_operation/src/Plugin/WebformElement/PlaceOfOperationComposite.php
* Dates were shown wrong if dates added were before turning clocks
* Simplified date formatting, works now as expected
* `git checkout feature/AU-2330-dates`
* `make fresh`
[AU-2330]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2330: fix dates in Place of operations

public/modules/custom/grants_metadata/translations/fi.po, public/modules/custom/grants_metadata/translations/sv.po
Tulostusnäkymässä on File name aina englanniksi.
* Lisää merkkijonolle käännös oikealla kontekstilla.
ATVScheman uudelleenkirjoituksessa koodiin on lisätty konteksti ilman lisättyä käännöstä.
* `git checkout feature/AU-2345-translation-fix`
* `make fresh`
[AU-2345]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2345 Add translations for file name

conf/cmi/webform.webform.kaupunginkanslia_tyollisyysavust.yml
* Fixed people responsible for operations -fields logic
* `git checkout feature/AU-2348-vastuuhenkilo`
* `make fresh`
[AU-2348]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2348: fix vastuuhenkilo in tyollisyyshakemus

public/modules/custom/grants_metadata/src/GrantsConverterService.php
This pull request fixes an issue where copying an application with an empty date field would cause an ajax error:
* `git checkout feature/AU-2355-application-copy-fix`
* `make fresh`
- Login with a registered community role and start a new application. Make sure the application has a date field somewhere, for example, [Taide- ja kulttuuriavustukset: projektiavustukset](https://hel-fi-drupal-grant-applications.docker.so/fi/form/kuva-projekti).
- Save the application as a draft and copy it by clicking "Kopioi hakemus". Make sure the application is copied.
- If you want to, you can run `make test-pw-p PROJECT=forms-48-registered` to make sure the application still works normally.
[AU-2355]: …
=> fix: AU-2355: Copying applications with empty date fields

e2e/utils/copying_helpers.ts, public/modules/custom/grants_handler/src/Form/CopyApplicationModalForm.php
This pull request fixes an issue where copying an application that has disabled copying would make the tests fail. Now, the copying test is skipped if an application has disabled copying.
- Added an ID to the copy application modal button.
* `git checkout feature/AU-2367-e2e-copy-test-open-application`
* `make fresh`
- Go to the [settings page](https://hel-fi-drupal-grant-applications.docker.so/fi/admin/structure/webform/manage/kuva_projekti/settings) of the **Taide- ja kulttuuriavustukset: projektiavustukset** form and `disable copying` at the bottom of the page.
- Set `ENABLED_FORM_VARIANTSS="copy"` in your `.env` file. 
- Run `make test-pw-p PROJECT=forms-48-registered` and make sure you get an output like …
=> feat: AU-2367: E2E, Skip application copying test if copying is disabled

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* HDBT subtheme had a stray $url. It was fixed.
* `git checkout feature/AU-2386-themefix`
* `make fresh`
[AU-2386]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2386: Fix phpcs for theme

e2e/utils/form_helpers.ts, e2e/utils/helpers.ts, e2e/utils/validation_helpers.ts
This pull request implements soft assertion for the `verifySubmit` function that is called right after an application has been submitted.
When an application is submitted, the tests start waiting for a "Vastaanotettu" text to appear on the page, which indicates that an application has been received by Avustus2. Sometimes this text doesn't show up, which would cause our old test implementation to fail and skip other tests inside the same test file.
Now, the `verifySubmit` function calls `waitForTextWithInterval`, which looks for the "Vastaanotettu" text for a total of 60 seconds. If the text is never found, we simply return instead of throwing and error. A warning text is also displayed.
- `validation_helpers.ts:` Added validation to submitted applications.
Make sure your instance is up …
=> feat: AU-2384: E2E, Implemented soft assertion for verifySubmit

public/themes/custom/hdbt_subtheme/templates/field/field--field-lead-in.html.twig
* Moved the hidden aria label to come after the text so that it won't get parsed in front of our text-only displays when the markup is stripped from the field.
* `git checkout feature/AU-2366-etsi-avustusta-johdanto`
* `make fresh`
[AU-2366]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2366: Fix application search card lead-in text display

conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_metadata/src/InputmaskHandler.php
* Add euro input masks to nuortoimpalkka text-fields
* Added logic to add possible input mask suffix to the webform value, if that is available from metada.
* `git checkout feature/AU-2343-input-mask-prefix-to-submission-view?expand=1`
* `make fresh`
[AU-2343]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2343: Nuortoimpalkka input masks to euro fields

public/modules/custom/grants_oma_asiointi/src/Plugin/Block/AsiointirooliBlock.php
* Remove empty link from asiointiroolin valinta page
* `git checkout feature/AU-2428-empty-asiointirooli-link`
* `make fresh`
[AU-2428]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2428: Fix empty asiointirooli link

conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.hyte_yleisavustus.yml, conf/cmi/language/sv/webform.webform.kasko_ip_lisa.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.leiriselvitys.yml, conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/sv/webform.webform.liikunta_suunnistuskartta_avustu.yml, conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.nuorlomaleir.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml
* Fixed a letter in webform actions
* `git checkout feature/AU-2371-oavslutad`
* `make fresh`
[AU-2371]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2371: fix a letter in webform actions

public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-front.html.twig
* Fixed "New message" string by adding context to oma asiointi
* `git checkout feature/AU-2375-oma-asiointi-sv`
* `make fresh`
[AU-2375]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2375: add context to string in Oma asiointi

public/modules/custom/grants_place_of_operation/src/Plugin/WebformElement/PlaceOfOperationComposite.php
The `Place of operation` components has the field `Toimintaa järjestetään kaupungin opetus-, sosiaali- tai nuorisotoimelta saaduissa maksuttomissa tiloissa`. This field was displaying the value "false/true" when viewing a submitted application on the "/katso" page. This issue has been fixed.
* `feature/AU-2454-place-of-operation-bu`
* `make fresh`
Run `make test-pw-p PROJECT=forms-52` and make sure it passes. 
You can also test a [form](https://hel-fi-drupal-grant-applications.docker.so/fi/form/kasvatus-ja-koulutus-toiminta-av) manually if you feel like it. Submit the form and make sure either Yes or No is displayed on the "/katso" page after submitting the form.
[AU-2454]: …
=> fix: AU-2454: Boolean values in the place of operations component

conf/cmi/language/sv/webform.webform.kuva_toiminta.yml
* Fixes to KUVA toiminta SV translations
* `git checkout feature/AU-2376-kuva-toiminta`
* `make fresh`
[AU-2376]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2377]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2376, AU-2377: fixes to KUVA toiminta SV translations

public/modules/custom/grants_handler/src/Plugin/Block/ApplicationTimeoutMessageBlock.php, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po, public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php, public/modules/custom/grants_mandate/translations/fi.po, public/modules/custom/grants_mandate/translations/sv.po
* Fix translations that were broken after phpstan fixes
* `git checkout feature/AU-2459-translations`
* `make fresh`
[AU-2459]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2459: fix broken translations

public/modules/custom/grants_attachments/src/AttachmentHandlerHelper.php
* Fix an issue where isDeliveredLater / isIncludedInOtherFile checkbox values were disappearing if user doesn't visit attachment page after returning to edit mode.
* `git checkout feature/AU-2457-fix-attachment-selections-disappearing`
* `make fresh`
[AU-2457]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2457: Fix attachment selections disappearing

public/modules/custom/grants_attachments/src/AttachmentRemover.php, public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php, public/modules/custom/grants_handler/src/Form/MessageForm.php, public/modules/custom/grants_profile/grants_profile.module
The goal of this pull request was to:
**A)** Fix the code inside `purgeAllAttachments` that gets called every cron run.
**B)** Figure out why we're no longer deleting application attachments after an application has been saved/submitted.
**Fix for A):** The `purgeAllAttachments` function has been fixed an refactored. Previously, the function would always delete everything inside the `/private` directory whenever it was called, since session ID comparison was being done incorrectly. Changes also had to be made inside `GrantsAttachments.php` and `MessageForm.php`, since these were creating the attachment directories with the wrong hashing algorithm (sha1 instead of Crypt::hashBase64) in the first place. The code inside `grants_profile_cron` was also removed, since it is just duplicating the …
=> fix: AU-2057: Application attachment purging fix

e2e/README.md, e2e/tests/forms/registered_community_52.ts, e2e/utils/data/application/application_data_52.ts, e2e/utils/data/application/application_data_67.ts
This pull request implements a field value swap test for application 52. This has been done in order to test that checkbox values selected on the applications attachment page stay "ticked" after the form has been edited a second time. This is done by:
1. Filling in the form normally with the form test. Here we make sure to tic a few checkbox on the attachment page.
2. Going back to the form during the field swap test, while making sure that we don't visit the attachment page.
3. Validating the content of the form after the field swap test has finished.
- Added `expectedErrors` to the 67 forms `copyForm` test (they were missing and causing the tests to fail). Also removed the field `edit-business-purpose`, since this field isn't currently being copied correctly.
- Added to the .readme. …
=> feat: AU-2453, E2E, Test attachment checkboxes

public/modules/custom/grants_metadata/grants_metadata.module
Modifies suggested form ID format when duplicating webform.
* `git checkout AU-2267-duplicate-webform-id`
* `make fresh`
* Does the ID logic work as intended in the original ticket and does it seem future proof?
* Are there any industry and type combinations that would potentially cause ID collisions? For example if the industry name is long enough that the type gets completely truncated.
* Is the timestamp logic good enough for handling collisions if for some reason the same form gets duplicated multiple times in a row? This should only be a problem if someone tries to duplicate the form multiple times within one minute, but there might be other edge cases.
* One option could be to check the ID field …
=> AU-2267: Format suggested ID for duplicated webforms.

public/modules/custom/grants_metadata/src/TypedDataToDocumentContentWithWebform.php
Hakemuksesta vastaavat henkilöt -kentän metadatan generoinnin.
* Poista turha metadatan generointi rivi
* `git checkout feature/AU-2462-metadata-field-issueh`
* `make fresh`
[AU-2462]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2462: Remove unnecessary metdata generation

conf/cmi/language.negotiation.yml
* Change default language back to FI.
* `git checkout feature/AU-2468-default-lang`
* `make fresh`
[AU-2230]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2468]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2468: Change language back to FI

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* We had an older hdbt_subtheme preprocessing hook in our system that defined the path to icons. This has since been removed from the way hdbt subtheme works (most likely in v3 update), but the function still existed and got called a lot. Now it is gone and nothing has changed in the way the site works.
* `git checkout feature/AU-2474-icon-path`
* `make fresh`
[AU-2474]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2472]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2472: remove unused hdbt_subtheme preprocessing hook for icon path

public/modules/custom/grants_admin_applications/src/Form/AtvFormBase.php, public/modules/custom/grants_admin_applications/src/Form/ResendApplicationsForm.php, public/modules/custom/grants_admin_applications/src/Form/SubmittedApplicationsForm.php
Linked this to documentation ticket because found this here.
* Configs were imported incorrectly for SubmittedApplicationsForm which broke the form. Fixed this.
* `git checkout feature/AU-635-fix-resend-form`
* `make fresh`, only if needed, but possibly no need and can test with your current state
[AU-635]: https://helsinkisolutionoffice.atlassian.net/browse/AU-635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-635: Fix application resend form.

public/themes/custom/hdbt_subtheme/templates/webform/webform-progress-tracker.html.twig
* The page stepper's first line breaks in a silly place (right after the number) if the first word of the stepper title is long. This adds a nonbreaking space in beween the number and the first word to make the word fit on the first line.
* `git checkout feature/AU-2470-nbsp-to-stepper`
* `make fresh`
[AU-2470]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2470: Fix stepper first line

conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
* Add text to KUVAKEHA subventions
* `git checkout feature/AU-2494-kuvakeha`
* `make fresh`
[AU-2494]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2494: add text to KUVAKEHA subventions

conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
* [AU-2490](https://helsinkisolutionoffice.atlassian.net/browse/AU-2490): Fix SV tooltips in attachments
* [AU-2491](https://helsinkisolutionoffice.atlassian.net/browse/AU-2491): Change Suunnitellut menot tooltip to description
* `git checkout feature/AU-2491-kuva-keha`
* `make fresh`
[AU-2490]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2491]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2490, AU-2491: small fixes to KUVAKEHA

conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.kuva_toiminta.yml
* Fix tooltip in kuva toiminta
* `git checkout feature/AU-2942-kuva-toiminta`
* `make fresh`
=> fix: AU-2942: fix tooltip in kuva toiminta

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* [AU-2481](https://helsinkisolutionoffice.atlassian.net/browse/AU-2481): Fix warning message translation
* [AU-2482](https://helsinkisolutionoffice.atlassian.net/browse/AU-2482): Fix status message translation
* `git checkout feature/AU-2481-translation`
* `make fresh`
[AU-2481]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2482]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2481, AU-2482: fix message translations

public/modules/custom/grants_handler/js/webform.form.unsaved.js, public/modules/custom/grants_handler/templates/application-list.html.twig
* On formpage, the unsaved confirmation script was interfering with internal links (links that point to the same page), this fixes that.
* `git checkout feature/AU-2420-jumplink-javascript-fix`
* `make fresh`
[AU-2420]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2420: Fix jumplink at the start of a form page

public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
* Some headers were of wrong depth on Edit Profile page of private person and unregistered community. This is fixed now.
* `git checkout feature/AU-2473-omat-yhteystiedot`
* `make fresh`
[AU-2473]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2473: Fix profiles

public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAuthBlock.php
Scheduling of applications is broken because of the caching setup.
* Add hard cache for 10 mins. This means that ServicePageBlock will always be cached for 10 minutes. So at most, the block should show / hide maximum of 10 mins after the scheduled time.
* `git checkout feature/AU-2478-publish-timings`
* `make fresh`
* Open any application with admin access, and set the closing time for some minutes in advance. Make sure the service page is linked to form.
* If waiting is not your thing, you can change the cache [time in here for smaller value](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/blob/b94225cc59a568d2b3b99b5dcc4ad451c5190f88/public/modules/custom/grants_handler/src/Plugin/Block/ServiceP …
=> fix: AU-2478: Fix applications scheduling

e2e/tests/forms/private_person_64.ts, e2e/tests/forms/registered_community_64.ts, e2e/tests/forms/unregistered_community_64.ts, e2e/utils/verify_draft_button_helpers.ts, public/modules/custom/grants_admin_applications/src/Form/DeleteApplicationsForm.php, public/modules/custom/grants_admin_applications/src/Service/HandleDocumentsBatchService.php
This pull request implements a test for verifying that an already existing draft application has a "Save as draft" button on the applications "edit" page. The test has been implemented for all 64 forms.
* `feature/AU-2488-service-page-blocks`
* `make fresh`
- Set ENABLED_FORM_VARIANTS="draft" in the `.env` file.
- Run `make test-pw-p PROJECT=forms-64`. Make sure the test passes and that you see this:
[AU-2488]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2502]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> feature: AU-2502: E2E, Verify draft button test

conf/cmi/language/fi/views.view.content.yml, conf/cmi/language/sv/views.view.content.yml, conf/cmi/views.view.content.yml
* Add content editor to content listing
* `git checkout feature/AU-2508-content-editor`
* `make fresh`
[AU-2508]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2508: add content editor to content listing

composer.json, composer.lock
* `git checkout feature/AU-2503-gdpr-fixes`
* `make fresh`
See:
https://github.com/City-of-Helsinki/drupal-module-helfi-gdpr-api/pull/8
[AU-2503]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2503: Update gdpr api module update

conf/cmi/openid_connect.settings.yml
This pull request sets the `connect_existing_users` to TRUE in the OpenID settings. This should allow AD-users to log into Drupal if a Drupal user with the matching email already exists in the system.
* `feature/AU-2357-connect-ad-email-to-drupal-user`
* `make fresh`
This change should be **thoroughly** tested by AD-users on the [staging](https://avustukset.stage.hel.ninja/fi/user/login?login=admin) server.
[AU-2357]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2314]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> feat: AU-2357: Set connect_existing_users to TRUE in OpenID

e2e/utils/form_helpers.ts, e2e/utils/form_variant_helpers.ts
This pull request implements an "is application closed" check for the main form filling test. The check is needed in order to ensure that an application is actually closed in a situation where we don't reach the applications URL when trying to access it.
**Previously**:
The form filling test assumed that an application was closed if we ended up on any other URL than the form's URL while trying to access the application, which would skip the test.
**Now**:
An application is only assumed to be closed if:
- The user gets redirected to a URL starting with /fi/tietoa-avustuksista/.
- The "Tämä avustushaku ei ole avoimena" error message is present on the page.
This check provides a more accurate determination of whether the application is actually closed or not.
Make sure your instance is up …
=> feat: AU-2528: E2E, Added a isApplicationClosed check

public/sites/default/all.settings.php
Fixed a AD-role <-> Drupal role mapping typo in all.settings.php.
* `feature/AU-2357-ad-role-fix`
* `make fresh`
Nothing to test. Verify that the roles in all.settings.php are the same as in helfi_helsinki_profiili.settings.yml.
[AU-2357]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2357: Fixed a AD-role mapping typo

public/sites/default/all.settings.php
This pull request is a "shot in the dark" attempt to fix AD-role <-> Drupal role mappings. The `helfi_tunnistamo` module advises to implement the mappings like this:
After some testing I discovered that the `[` and `]` (square brackets) that come before and after the AD-role might not be needed. I also noticed that the `Helfi Etusivu` project doesn't use these brackets in their mappings:
I have therefore removed them fro the `all.settings.php` file, so that we can at least test the implementation like this.
* `feature/AU-2357-fix-ad-role-drupal-role-mapping`
* `make fresh`
- Needs to be tasted in the staging environment by Tero and Pirjo. 
[AU-2357]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2357?at …
=> feat: AU-2357: Attempting to fix AD-role <-> Drupal role mapping

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Error text was pretty vague when seding an application with empty fields, so it has been changed to more descriptive
* `git checkout feature/AU-2537-error-message`
* `make fresh`
[AU-2537]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2537: change error text when sending application with empty fields

public/modules/custom/grants_handler/templates/application-list.html.twig, public/modules/custom/grants_oma_asiointi/js/application-draft-list.js
* Added paginator to drafts
* `git checkout feature/AU-2388-drafts-paginator`
* `make fresh`
[AU-2388]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2388: add paginator to drafts

public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAuthBlock.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Fix translation in service page auth block
* `git checkout feature/AU-2529-translation`
* `make fresh`
[AU-2529]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2529: fix translation in service page auth block

e2e/utils/data/application/application_data_48.ts, e2e/utils/data/application/application_data_53.ts, e2e/utils/data/application/application_data_62.ts, e2e/utils/data/profile_data_private_person.ts, e2e/utils/data/profile_data_registered_community.ts, e2e/utils/data/profile_data_unregistered_community.ts, e2e/utils/form_helpers.ts, public/modules/custom/grants_place_of_operation/src/Plugin/WebformElement/PlaceOfOperationComposite.php
This pull request implements a check to ensure that the profile form tests reach the correct profile form. The test verifies this by checking for a specific class on the page that corresponds to the profile type for which the form is being filled.
[Refactors of the /katso page](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1416) recently broke the E2E tests (some values we're not printed at all, and some lost their wrappers). This issue has also been fixed.
* `feature/AU-2535-e2e-log-profile-form-type`
* `make fresh`
- Set `ENABLED_FORM_VARIANTS="draft"` in the `.env` file.
- Run `make test-pw-p PROJECT=forms-48-registered forms-62-registered forms-53 forms-52`. Make sure the tests pass, and …
=> feat: AU-2535, E2E: Confirm that the tests reach the correct profile form and bug fixing

e2e/.env.example, e2e/README.md, e2e/playwright.config.ts, e2e/utils/form_helpers.ts, e2e/utils/helpers.ts
This pull request implements the possibility to set timeouts for `waitForTextWithInterval` function in the `.env` file. The following new environment variables are described in the `env.example` file:
```
WAIT_FOR_TEXT_TIMEOUT="10000"
WAIT_FOR_TEXT_INTERVAL="5000"
```
* `feature/AU-2533-e2e-set-wait-for-text-variable-to-env`
* `make fresh`
- Set `ENABLED_FORM_VARIANTS="success"` and the new `WAIT_FOR_TEXT_TIMEOUT` and `WAIT_FOR_TEXT_INTERVAL` values in the `.env` file:
```
WAIT_FOR_TEXT_TIMEOUT="10000"
WAIT_FOR_TEXT_INTERVAL="2500"
```
- Run `make test-pw-p PROJECT=forms-53`. Make sure the tests pass, and that the "Vastaanotettu" text is only waited for for 10 seconds (10000ms) and queried with 2.5 second …
=> feat: AU-2533, E2E: Implemented the possibility to set timeouts for the waitForTextWithInterval function in the .env file.

public/modules/custom/grants_handler/src/ApplicationHandler.php
* isApplicationOpen was using wrong comparison string for prod flag.
* `git checkout feature/AU-448-fix-prod-status`
* `make fresh`
[AU-448]: https://helsinkisolutionoffice.atlassian.net/browse/AU-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-448: Change correct status to production check

public/modules/custom/grants_handler/src/Plugin/WebformElement/GrantsCompositeBase.php
This pull request fixes a bug in the `formatFieldValue()` function inside `GrantsCompositeBase.php`. The function would throw a fatal error in situations where a `NULL` value was passed into the function as the `$fieldValue` parameters value. This could happen in a situation where someone left an empty field in a form.
* `feature/AU-2533-e2e-set-wait-for-text-variable-to-env`
* `make fresh`
- Set `ENABLED_FORM_VARIANTS="missing_values"` in the `.env` file:
- Run `make test-pw-p PROJECT=forms-60` (this test was broken in the pipeline). Make sure the tests pass. You can also run other tests to make sure everything still works. I ran every test:
[AU-2533]: …
=> feat: AU-2541: Fixed a bug in GrantsCompositeBase.php

public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php
* Hide attachment field values which have only description field filled (As we filter these out anyways when submitting / saving to ATV)
* `git checkout feature/AU-2342-hide-description-only-attachment`
* `make fresh`
[AU-2342]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2342: Hide attachments with only a description in preview page

e2e/utils/data/application/application_data_52.ts, e2e/utils/error_validation_helpers.ts
This pull request attempts to fix inline form error validation in our pipelines. For some reason the tests seem to work locally, but fail when executed in the staging environment. Still, I've attempted to eliminate any flakiness with these changes. Inline error validation has also been added to form 52.
* `git checkout feature/AU-2542-e2e-fix-inline-form-error-validation`
* `make fresh`
- Set `ENABLED_FORM_VARIANTS="wrong_values,missing_values"` values in the `.env` file.
- Run `make test-pw-p PROJECT=forms-51 forms-52 forms-62`. Make sure that all the tests pass, and that you see various "Validating inline form error:" messages during the form filling test:
[AU-2542]: …
=> feature: AU-2542: Attempting to fix inline form error validation in the pipelines

public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
Näytä enemmän dataa loppukäyttäjälle tulostusnäkymässä kun kaikkia kenttiä ei ole täytetty
* Käytä tyhjää default-arvoa 
* Ei ole varmuutta hyväksyykö Avus2 tyhjät arvot numerokentissä. Näihin voi muuttaa 0:t tarvittaessa.
* `git checkoutfeature/AU-2317-print-view`
* `make fresh`
Lokaalin freshauksen jälkeen testeilläkin sujuu paremmin.
[AU-2317]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2317 Show data of kuvaproj application in print view

public/sites/default/all.settings.php
This pull request implements a few new AD-group <-> Drupal-role mappings according to the instructions in the ticket.
* `git checkout feature/AU-2544-new-ad-group-drupal-role-mappings`
* `make fresh`
- Take this to the staging environment and let Tero / Pirjo test it.
[AU-2544]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature: AU-2544: Added new ad-group <-> drupal-role mappings

public/modules/custom/grants_industries/grants_industries.module, public/modules/custom/grants_metadata/grants_metadata.module, public/sites/default/all.settings.php
This pull request implements a few new AD-group <-> Drupal role mappings according to the instructions in the ticket. It also implements AD-group <-> INDUSTRY mappings according to the AD-group names.
Fixed and issue in `grants_metadata.module` where no users other than the ones with the `grants_admin` role could edit anything on a Webforms third-party settings page.
* `git checkout feature/AU-2544-new-ad-group-drupal-role-mappings`
* `make fresh`
[AU-2544]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-2548]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> feat: AU-2548: Added new AD-group <-> Drupal role mappings.

e2e/utils/data/test_data.ts
This pull request implements the last parts of the E2E test documentation. The code is documented pretty well overall. Only the types and interfaces lacked any documentation in the `test_data.ts` file, so I added a few comments.
* `git checkout feature/AU-2545-e2e-documentation`
* `make fresh`
- Review the added documentation in the `test_data.ts` file. Also look through the [Confluence](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8481833123/Regressiotestit) page and make sure it look alright.
[AU-2545]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2545: E2E documentation

e2e/Dockerfile
Regression tests broke because of some docker image rate limits, this tries to use custom image from Coty-of-Helsinki repo.
* Updated image in Dockerfile
[UHF-10344]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: UHF-10344: update e2e node image to custom one

public/modules/custom/grants_industries/grants_industries.module, public/modules/custom/grants_metadata/grants_metadata.module, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaPerusDefinition.php, public/sites/default/all.settings.php
There is incorrect field definition for realizedPremisesArray -field. Avus2 can't handle these 2 fields: isOthersUse & isOwnedByApplicant and process fails with error. 
* Removed 2 errorenous fields.
* `git checkout hotfix/UHF-10357`
* `make fresh`
[UHF-10357]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix: UHF-10357: Remove fields that break Avus2.

e2e/utils/data/application/application_data_29.ts, e2e/utils/data/application/application_data_48.ts, e2e/utils/data/application/application_data_49.ts, e2e/utils/data/application/application_data_51.ts, e2e/utils/data/application/application_data_52.ts, e2e/utils/data/application/application_data_53.ts, e2e/utils/data/application/application_data_54.ts, e2e/utils/data/application/application_data_56.ts, e2e/utils/data/application/application_data_57.ts, e2e/utils/data/application/application_data_58.ts, e2e/utils/data/application/application_data_60.ts, e2e/utils/data/application/application_data_61.ts, e2e/utils/data/application/application_data_62.ts, e2e/utils/data/application/application_data_63.ts, e2e/utils/data/application/application_data_64.ts, e2e/utils/data/application/application_data_65.ts, e2e/utils/data/application/application_data_66.ts, e2e/utils/data/application/application_data_67.ts, e2e/utils/data/application/application_data_68.ts, e2e/utils/data/application/application_data_69.ts, e2e/utils/data/profile_data_registered_community.ts, e2e/utils/data/profile_input_data.ts, e2e/utils/field_helpers.ts
Avus2 apparently sends all emails outwards from their system, and there's no way to stop that. And we discovered that faker creates email addresses that can be in use, like irmeli49@gmail.com.
* Email addresses creation was moved to custom function
* That function returns faker.exampleEmail() return value in lower case.
* `git checkout feature/UHF-10362-fix-faker-mails`
* `make fresh`
[UHF-10362]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: UHF-10362: Fix faker created testing emails to use example.com domain

public/modules/custom/grants_handler/src/ApplicationStatusService.php
It seems that at some SUBMITTED status has slipped to application statuses that were allowed to be edited. This is definitely something we don't want. This PR fixes it.
* Removed SUBMITTED from allowed statuses for editing form.
[UHF-10813]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: UHF-10813: Remove SUBMITTED status from editable list.

public/modules/custom/grants_admin_applications/src/Form/AtvFormBase.php, public/modules/custom/grants_handler/src/ApplicationStatusService.php, public/modules/custom/grants_handler/src/ApplicationUploaderService.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
We used to show "Edit" button for user even if saving process to ATV / Avus2 wasn't finished. We allowed user to access form, but every field & submit button was disabled.
This behavior was considered confusing for end user, so we removed the "Edit" button from application view page. Now user gets to see the form only if the process is completed.
* Removed SUBMITTED status from allowed edit statuses.
* Fixed error message that was shown if underlying form had newer version. This functionality relied on SUBMITTED status being on allowed list.
* `git checkout feature/UHF-10813-submitted-editable`
* `make fresh`
This again is very difficult to test without disabling sending of applications manually from …
=> fix: UHF-10813: Hide edit button for application if saving process is not completed

public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php
There was a bug in the delete button code for RECEIVED applications that hid the button when user is navigating from one page to another and back to attachment page.
This PR allows that button to be shown, but also makes sure that the button is shown ONLY for justUploaded files. If files are sent to Avus2 they are not allowed to be deleted.
Pretty much this bugfix is useless until [ATV-181](https://helsinkisolutionoffice.atlassian.net/browse/ATV-181) gets resolved. So even after this PR we fix Webform related issues, the file still is left on the ATV Document in production since the content policies do not allow files to be deleted from documents where `draft: false`
* Conditions for showing delete button were updated to use isSubmissionEditable() functionality
* An extra check was added …
=> fix: UHF-10142: Allow "Delete" button to show on RECEIVED applications when navigating on the form.

conf/cmi/core.extension.yml, public/modules/custom/grants_admin_applications/src/Form/AtvFormBase.php, public/modules/custom/grants_attachments/grants_attachments.info.yml, public/modules/custom/grants_attachments/grants_attachments.services.yml, public/modules/custom/grants_attachments/src/AttachmentHandler.php, public/modules/custom/grants_attachments/src/Controller/GrantsAttachmentsController.php, public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php, public/modules/custom/grants_events/grants_events.info.yml, public/modules/custom/grants_events/grants_events.module, public/modules/custom/grants_events/grants_events.services.yml, public/modules/custom/grants_events/src/EventException.php, public/modules/custom/grants_events/src/EventsService.php, public/modules/custom/grants_handler/grants_handler.install, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/grants_handler.services.yml, public/modules/custom/grants_handler/src/Controller/MessageController.php, public/modules/custom/grants_handler/src/Form/CopyApplicationModalForm.php, public/modules/custom/grants_handler/src/MessageService.php, public/modules/custom/grants_handler/tests/src/Kernel/DataConversionTest.php, public/modules/custom/grants_metadata/grants_metadata.services.yml, public/modules/custom/grants_metadata/src/ApplicationDataService.php, public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php, tools/make/project/install.mk, tools/make/project/zzavustusasiointi.mk
Some of the latest refactorings created a circular dependency that wasn't issue when `make fresh` was run, but `make new` failed with missing services error. 
This breaks automatic testing because the dump cannot be created when make new fails.
* Fixed circular dependency by refactoring Event handling to separate module and updating all code to use the new module.
* This fixes the make new issue, but make fresh fails because the new module is not installed yet when something needs it.
* I did build the testing artifact with this branch, and the fact that the tests action finishes fine, shows that this fixes the underlying issue with make new.
* Don't really know how Sonar finds the refactoring to be a duplicate code, but it is what it is.
* Make sure your instance is up and running on …
=> feat: UHF-XXXX: Fix failing tests by fixing dependency-related errors.

conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml
Had incorrect translations.
* Add missing translations for issuer_name
* Change config value from #text to #markup to show translations.
* `git checkout feature/UHF-10656`
* `make fresh`
[UHF-10656]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: UHF-10656: Add missing translations. Fix incorrect config name for help texts.

e2e/utils/input_helpers.ts
Sorry, no ticket..
But the tests fail on Azure for duplicate filenames. This SHOULD be fixed with better file handling PR done a while back. And while everything works locally and on other servers, on the test env for some reason we see random errors with duplicate files. [Like so](https://dev.azure.com/City-of-Helsinki/avustusasiointi/_build/results?buildId=206558&view=ms.vss-test-web.build-test-results-tab).
* We add timestamp suffix to uploaded files.
* `git checkout fix-test-uploads`
* `make fresh`
=> Add suffix for filenames to force unique files.

public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php, tools/http/ATV.http
- Added ATV update request after mandate has been granted.
- Small refactor / code cleanup
* `git checkout UHF-10826`
* `make fresh`
- Log in as an actual user
- Go through all the required steps
- You should not get any errors in error log
- ATV profile should have been updated
[UHF-10826]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10826 Update ATV-profile after mandate has been requested

conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml
These texts were copied from incorrect place. This fixes that.
* issuer_name fields' tranlations were copied from correct place.
[UHF-10656]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: UHF-10656: Fix incorrectly copied transaltions

public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Fields under Seuran/yhdistyksen saamat vuokrat edellisen kalenterivuoden ajalta 1.1. - 31.12 were not visible ´
* Added rent income composite to webform print controller so that the fields are visible
* `git checkout UHF-10629 `
* `make fresh`
[UHF-10629]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10629: Added rent income composite to webform print controller

public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php
* Modify the order where questions are asked in budget_cost_static webform element
* `git checkout UHF-10571`
* `make fresh`
[UHF-10571]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10571: Change the order of questions on kuva_projekti webform

public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Removed the useless visibility text block from the print form: "You don't need to fill this because field Y is false"
[UHF-10722]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10722: remove the visibility helper text

pipelines/drupal-dev.yml, pipelines/drupal-test.yml
Change pipeline triggers:
- Commits in `dev` branch trigger deploy to `dev` environment.
- Test branch must be triggered manually (do not deploy between 10.00-16.00)
- e2e tests are run on dev environment by default.
* https://dev.azure.com/City-of-Helsinki/avustusasiointi/_git/avustusasiointi-pipelines/pullrequest/10273
[UHF-11041]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11041: Change pipeline triggers

public/modules/custom/grants_handler/src/ApplicationGetterService.php
Old applications created before form_uuid was added do not load and they throw an error.
This affecta ALL applications created before the form_uuid was implemented.
* The handling was fixed so that the missing uuid does not skip old applications.
[UHF-11127]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11127: Fix thrown error when user tries to get form with out uuid

phpstan.neon, public/modules/custom/grants_handler/src/ApplicationUploaderService.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_metadata/src/AtvSchema.php
Editing and saving an application which is already received by avus2 can lead into a situation where saving the form overrides messages and/or events saved to integration. (since both Avus2 and Drupal writes to ATV)
Added a flag which prevents overriding latest ATV changes when saving through integration.
* `git checkout UHF-11273`
* `make fresh`
- Create a new application and wait until it has been received
- Edit the application and save it
- Save should not override messages or events
[UHF-11273]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11273: Prevent overriding messages and events

conf/cmi/language/fi/views.view.content.yml
* Add missing translations for content listing view
* `git checkout UHF-11222`
* Run `make drush-cr drush-cim`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/890
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1166
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1630
[UHF-11222]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11222: Add missing translations for content listing view

public/modules/custom/grants_handler/templates/grants-service-page-block.html.twig, public/modules/custom/grants_preview_link/templates/grants-preview-link.html.twig
* Removed two icons that are not functional in production and after HDS-update the empty icons turned to black boxes.
* `git checkout UHF-11393`
* `make fresh`
[UHF-11393]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11393: Remove disfunctional icons

public/modules/custom/grants_handler/src/Controller/AtvPrintViewController.php
Try fixing problem where opening the printing view for already sent application was empty
* `git checkout UHF-11297`
* `make fresh`
- Try with multiple browsers, this bug is hard to recreate
- Only bug I managed to produce was a white screen caused by trying to json decode null.  
- Log in as end user
- Try opening the print view on all the sent applications
- The application print should be filled with the data always
[UHF-11297]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11297: empty string on field meta caused a crash

conf/cmi/webform.webform.liikuntaharrastamisen_avustus.yml, public/themes/custom/hdbt_subtheme/templates/webform/webform-submission-information.html.twig
* Copy was supposed to be disabled for this grant application. This issue was raised in [Jira comment](https://helsinkisolutionoffice.atlassian.net/browse/UHF-11419?focusedCommentId=134270). 
* `git checkout UHF-11419-disable-copy`
* `make fresh`
* Run `drush grants-tools:webform-import`
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1653
[UHF-11419]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11419: disable copy

public/modules/custom/grants_handler/js/grants-dialog.js, public/modules/custom/grants_profile/js/profile_dialog.js
Allow user to leave the profile page on first time without closing the browser.
Added a button to the dialog which redirects user to role switch page.
* `git checkout UHF-11289`
* `make fresh`
- Create a new end user (login using different test-hetu)
- Select rekisteröity yhdistys as your asiointirooli
- Instead of filling the information, try clicking any link on the page
- The dialog should now have 2 buttons instead of 1.
-  The second button should be "Vaihda rooli" or "Switch role" or something like that
- The switch role -button should redirect the user to role switching page.  
[UHF-11289]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> UHF-11289: add new button to hakuprofiili page which allows user to go back

public/modules/custom/grants_handler/src/ApplicationInitService.php
Prevent duplicates on budget component when copying existing application.
- Removed the part which caused the duplication. 
- Not sure if some other application copying breaks after this change.
* `git checkout UHF-11018`
* `make fresh`
- If you have prefilled segregation application, copy it
- If not, fill a segregation form and add data to all field (especially the "talous" section)
- Copy the application
- Check that the "talous" fields won't have duplicate values (tulon tyyppi, meno)
[UHF-11018]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11018: prevent duplicate when copying

public/modules/custom/grants_place_of_operation/src/Element/PlaceOfOperationComposite.php, public/modules/custom/grants_place_of_operation/src/PlaceOfOperationService.php, public/modules/custom/grants_place_of_operation/src/Plugin/DataType/PlaceOfOperationData.php, public/modules/custom/grants_place_of_operation/src/TypedData/Definition/PlaceOfOperationDefinition.php
* Fixed the PlaceOfOperationData "free" element setters to match yes/no radio button option values.
* Converted radio button option values from integers to strings as webform struggles to convert falsy values back to integers.
* Added a convertBooleanToString method and used it as a "webformValueExtracter" extractor service when processing the PlaceOfOperationComposite's "Free" element.
[UHF-11394]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11394 Free element

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
Redirect to oma asioiti after saving an application as a draft.
* `git checkout UHF-11631`
* `make fresh`
- Start creating an application, save it as a draft
You should be redirected to oma-asiointi page.
[UHF-11631]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11631: redirect to oma-asiointi after saving as draft

public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php
* This feature implemeneted https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1692 in caused a bug in editing already submitted forms
* `git checkout UHF-11684-disable-profile-attachment-cleaning`
* `make fresh`
[UHF-11684]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11684: Disable form attachment cleaning

conf/cmi/csp.settings.yml, conf/cmi/oembed_providers.settings.yml
The active content security policy didn't allow iframe embeds from Youtube, Helsinki-kanava or PowerBI.
* `frame-src` and `object-src` -directives were updated with relevant domains. Only video embeds require the `object-src`-directive as Drupal embeds them via a local iframe path where `<object>`-tag is eventually used for the actual embedding. This is why the two directives aren't identical.
* `git checkout UHF-11529_csp`
* `make fresh`
* Test embedding content from Youtube, Vimeo, Helsinki-kanava and PowerBI
* Edit an existing regular page or create a new one
[UHF-11529]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> UHF-11529: Updating CSP configuration

public/sites/default/all.settings.php
Apparently avustukset sometimes checks for role name instead of permission, so developer accounts do not get all permisions:
https://github.com/search?q=repo%3ACity-of-Helsinki%2Fhel-fi-drupal-grants%20%27grants_admin%27%2C&type=code
- Setup tunnistamo locally
- Log in as a admin
- You should get grants_admin role.
=> Add grants admin role to developers

public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php
Update company name after every mandating request (when you select rekisteröity yhdistys-asiointirooli)
* `git checkout UHF-11688`
* `make fresh`
- Select rekisteröity yhdistys as asiointirooli
- Create a new draft application, no need to fill it completely
- Check the company name on the first page of the draft-application
- Uncomment the company name override -code which was added in the PR
- Log out
- Log in as same user, same asiointirooli
- Open the same application
- On the first page, the company name should be updated
[UHF-11688]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> UHF-11688: update company name on login

conf/cmi/views.view.application_search_search_api.yml
* Changed search cards to use field_lead_in or field_content (if lead in isn't available) instead of the search excerpt
* `git checkout UHF-11603`
* `make fresh`
[UHF-11603]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11603: Changed configs for search api

e2e/playwright.config.ts, e2e/utils/data/application/application_data_48.ts, e2e/utils/data/application/application_data_50.ts, e2e/utils/data/application/application_data_52.ts, e2e/utils/field_swap_helpers.ts, public/modules/custom/grants_webform_import/src/Commands/WebformConfigOverrideCommands.php
* Removed obsolete saveAsDraft function and fixed the form validation after this redirection change: https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1705
* Added the bank account number selection to field swap form, as it was not found when running tests for field swap validation.
* Excluded the 68:hyte_yleisavustus form test from forms-all.
* Allow the webform override method to override forms with a same ID, for example: webform.webform.asukasosallisuus_pienavustushake.yml and webform.webform.terveys_hyvinvointi_pienavustus.yml
* `git checkout UHF-11857`
* `make fresh`
[UHF-11857]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> UHF-11857 E2E tests

composer.json, composer.lock
* Removed a local `content_lock` patch that was blocking automatic updates (https://github.com/City-of-Helsinki/hel-fi-drupal-grants/actions/runs/16569125935/job/46856420005#step:6:917)
=> UHF-X: Removing a local content_lock patch to allow automatic updates

composer.json, composer.lock
The dependency to `drupal/csp` was added to `helfi_platform_config` and the local version here was conflicting with that.
* This PR updates the direct dependency to `drupal/csp` to not have version restrictions to allow installing the version set in `helfi_platform_config`.
* See install and test instructions in https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1038
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1038
[UHF-11973]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-11975]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> UHF-11975: Updating local drupal/csp to allow the dependency version from helfi_platform_config

public/modules/custom/grants_handler/src/ApplicationAccessHandler.php, public/modules/custom/grants_handler/src/Controller/ApplicationController.php
One user is unable to edit applications and only visible thing is 403-response in kibana (hakemus/7050/muokkaa with message: "").
Handle the unhandled exceptions in application access checks.
Added logging to catch possibly bad access-check cases (for example user's business id doesn't match application's business id sounds more like an erroneous situation than anything else)
* `git checkout UHF-12151`
* `make fresh`
The code should not break anything.
- Create a new application or edit existing
- It should work as before
[UHF-12151]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> UHF-12151: Application custom access check code changes
