composer.lock, docker/openshift/docker-entrypoint.sh, tools/make/drupal.mk, tools/make/project/install.mk
Updated tools, composer dependencies and openshift drush commands.
=> Translation updates

conf/cmi/webform.webform.yleisavustushakemus.yml, public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
Add support for fileType settings in webform handler + UI.
Note the base branch!
=> AU-282: Add support for fileType variable in attachment configuration.

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
=> Initialize attachmentID array in constructor

public/sites/default/settings.php
=> Fix settings variable name

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_handler/src/Controller/ApplicationsListController.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_profile/grants_profile.module, public/modules/custom/grants_profile/src/Controller/GrantsProfileController.php, public/modules/custom/grants_profile/src/GrantsProfileService.php
Small fixes, will deploy to dev and see fixes there.
=> 12082022 bugfixes

composer.lock, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/templates/application-list-item.html.twig, public/modules/custom/grants_handler/templates/application-status-tag.html.twig
fix status ifs and move status tag outside of list item.
=> AU-192: move status tag to outside of the list item

public/modules/custom/grants_handler/grants_handler.module
Get statusstring back into application list item to make the proper ifs working.
Still needs the delete link inside the twig.
=> fix status-based ifs

conf/cmi/webform.webform.yleisavustushakemus.yml
lomakkeen muutaman kentän järjestys pitäisi olla toinen.
Jos tämä vaikuttaa jotenkin muualle, niin ota koppi, jos ei, niin sit vaan mergeillään.
=> päivitetty .yml yleishakemusavustukseen

public/modules/custom/grants_handler/grants_handler.module
Add submitted timestamp to the "tarkastele hakemusta" page
* `git checkout feature/AU-602-formsubmitted-timestamp`
=> AU-602: add form_timestamp_submitted

composer.json, composer.lock
We need audit logging.
* Installs helfi_audit_log module
* `make fresh`
[AU-517]: https://helsinkisolutionoffice.atlassian.net/browse/AU-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-671: Add Audit logging functionality

composer.lock
Update apibase module to fix naming convention errors.
=> AU-719: Update apibase module

composer.lock
Update HP module version
* To version 0.9.4
* Includes new env variable.
=> fix: AU-719: Helsinki profiili version bump

public/modules/custom/grants_profile/src/Form/GrantsProfileForm.php
* Changed form submit redirect to profile
* `git checkout feature/AU-707-tallenna-omat-tiedot`
* `make fresh`
[AU-707]: https://helsinkisolutionoffice.atlassian.net/browse/AU-707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-707: set redirect to profile page after submit

conf/cmi/block.block.grantsomaasiointihero.yml, public/modules/custom/grants_oma_asiointi/grants_oma_asiointi.module, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiHeroBlock.php, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-hero-block.html.twig, public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme, public/themes/custom/hdbt_subtheme/src/scss/components/grants-profile/_oma-asiointi.scss, public/themes/custom/hdbt_subtheme/src/scss/styles.scss
* Created a hero block for Oma Asiointi pages
* `git checkout feature/AU-702-hero-oma-asiointi`
* `make fresh`
* build styles
[AU-702]: https://helsinkisolutionoffice.atlassian.net/browse/AU-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-702: create hero block for oma asiointi pages

conf/cmi/block.block.hdbt_subtheme_footertopnavigation.yml, conf/cmi/language/en/block.block.footertopnavigationsecond_2.yml, conf/cmi/language/fi/block.block.hdbt_subtheme_footertopnavigation.yml, conf/cmi/language/sv/block.block.footertopnavigationsecond_2.yml, conf/cmi/language/sv/block.block.hdbt_subtheme_footertopnavigation.yml
* Translated footer titles
* `git checkout feature/AU-XX-footer-titles`
* `make fresh`
=> translate footer titles

public/modules/custom/grants_oma_asiointi/grants_oma_asiointi.module, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiBlock.php, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiHeroBlock.php
* Disable cache in Oma asiointi hero
* `git checkout feature/AU-702-hero-cache`
* `make fresh`
[AU-702]: https://helsinkisolutionoffice.atlassian.net/browse/AU-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-702: disable cache in Oma asiointi hero block

public/modules/custom/grants_profile/grants_profile.module, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po, public/themes/custom/hdbt_subtheme/translations/fi.po, public/themes/custom/hdbt_subtheme/translations/sv.po
* Add translations to profile block
* `git checkout feature/AU-XX-login-translate`
* `make fresh`
.
=> fix: AU-738: add translations to profile block

composer.lock
Reverts City-of-Helsinki/hel-fi-drupal-grants#227
=> Revert "Automatic update"

public/modules/custom/grants_oma_asiointi/src/Plugin/Block/AsiointirooliBlock.php, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-asiointirooli-block.html.twig, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_oma_asiointi/translations/sv.po
* Add context to translations because for some reason test gets the wrong ones somewhere
* `git checkout feature/AU-XX-fix-translations`
* `make fresh`
=> fix: AU-XX: Add context to Asiointirooli-block translations

CHANGELOG.md, composer.json, composer.lock, public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAuthBlock.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/AsiointirooliBlock.php, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-asiointirooli-block.html.twig, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_oma_asiointi/translations/sv.po
=> Release 2023.7

hel-fi-drupal-grants-run-robot-tests.yml
Creates a new Azure devops pipeline, based on the same format as in [drupal-helfi-form-tool](https://github.com/City-of-Helsinki/drupal-helfi-form-tool/)
New pipeline definition file was created.
Can't really be tested, since it needs to be merged first before Azure Pipelines notices it. Maybe you can check if it's valid YAML :) 
[AU-574]: https://helsinkisolutionoffice.atlassian.net/browse/AU-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-574: Robot test pipeline

public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Fix malformed translation syntax
* `git checkout feature/AU-XX-fix-handler-translation`
* `make fresh`
=> fix: AU-XX fix translation syntax in grants_handler

public/modules/custom/grants_attachments/src/AttachmentHandler.php, public/modules/custom/grants_handler/src/Form/MessageForm.php, public/modules/custom/grants_handler/src/MessageService.php
There was some issues with message attachments: It did not support env changes done with integration so the attachments did not go through. Also attachments were uploaded in form submit so no errors could be shown inline. This fixes both of those.
* Refactor message attachments to be saved to ATV in validate call. This allows us to show errors to user before submitting the form itself.
* Add environment part to attachment integrationID so Fuse can deliver correct attachment to Avus2
* Some code style things now that we have SonarLint working.
* `git checkout feature/AU-804-integration-messages`
* `make fresh`
[AU-804]: https://helsinkisolutionoffice.atlassian.net/browse/AU-804?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> fix: AU-804: Fix message attachment integration

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/disable_messages.settings.yml
Installed and configured Disable Messaged module
* `git checkout AU-776-disable-messages`
* `make fresh`
[AU-776]: https://helsinkisolutionoffice.atlassian.net/browse/AU-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-776: Install and configure disable_messages module

CHANGELOG.md, conf/esimerkki_47.json, conf/esimerkki_49.json, conf/esimerkki_50.json, conf/esimerkki_kuvaproj.json, public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/GrantsHandlerSubmissionStorage.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KaskoYleisavustusDefinition.php, public/modules/custom/grants_premises/grants_premises.info.yml, public/modules/custom/grants_premises/grants_premises.module, public/modules/custom/grants_premises/grants_premises.permissions.yml, public/modules/custom/grants_premises/grants_premises.services.yml, public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/src/GrantsPremisesService.php, public/modules/custom/grants_premises/src/Plugin/DataType/GrantsPremisesData.php, public/modules/custom/grants_premises/src/Plugin/WebformElement/PremisesComposite.php, public/modules/custom/grants_premises/src/TypedData/Definition/GrantsPremisesDefinition.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/override/fi.po, public/modules/custom/grants_premises/translations/sv.po
Add wf component for handling premise details on application forms.
* Add new component for premises
* Add DataType + mapper and service class to support mapping
* Update ATV Schema 
* `git checkout feature/AU-883-tilakomponentti`
* `make fresh`
This can properly be tested only when form is sort of ready. Now we can see that the component works and data is added to ATV. 
`"activityInfo": {
"plannedPremisesArray": [
[
{
"ID": "premiseName",
"label": "description",
"value": "yurtyurtyu",
"valueType": "string"
},
{
"ID": "postCode",
"label": "description",
"value": "55555",
"valueType": "string"
},
{
"ID": "isOwnedByCity",
"label": "description",
"value": false,
"valueType": "bool"
}
]
]
}`
Also, a datatype …
=> feat: AU-883: Add tilakomponentti

public/modules/custom/grants_applicant_info/src/Element/ApplicantInfoComposite.php, public/themes/custom/hdbt_subtheme/src/scss/components/grants-profile/_grants-profile.scss
* Styled application info composite
* `git checkout feature/AU-933-hakijan-tiedot-ui`
* `make fresh`
[AU-933]: https://helsinkisolutionoffice.atlassian.net/browse/AU-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-933: style hakijan tiedot

hel-fi-drupal-grants-run-robot-tests.yml
Fixes the setup for running robot tests on Azure Pipelines
Can't be ran locally, other than check the syntax of the yaml file.
[AU-930]: https://helsinkisolutionoffice.atlassian.net/browse/AU-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-930: Azure pipelines setup

conf/cmi/language/sv/views.view.locked_services.yml, conf/cmi/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_metadata/src/AtvSchema.php
=> Add support for booleans.

conf/cmi/webform.webform.kuva_projekti.yml
* Fixed missing field values in submission view
* `git checkout feature/AU-997-esikatselu`
* `make fresh`
[AU-997]: https://helsinkisolutionoffice.atlassian.net/browse/AU-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-997: fix KUVA projekti preview fields

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/grants_handler.services.yml, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_metadata/src/TypedData/Definition/ApplicationDefinitionTrait.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
Issues with random fields, this makes validation messages better with fields that cannot be validated with webform.
[AU-1031]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1031: Fix validations & data mappings.

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_profile/src/Plugin/DataType/ApplicationOfficialData.php, public/modules/custom/grants_profile/src/Plugin/Validation/Constraint/RequiredIfRegistered.php, public/modules/custom/grants_profile/src/Plugin/Validation/Constraint/RequiredIfRegisteredValidator.php, public/modules/custom/grants_profile/src/TypedData/Definition/ApplicationOfficialDefinition.php
1st try to get conditional requirement to work with forms.
* Added required validator for registered community
* Added said validator for official role field, since this is required ONLY to registered community
* `git checkout feature/AU-XX-conditional-validator`
* `make fresh` / drush deploy. Not necessary to run fresh.
=> feat: AU-XX: Conditional validator

public/modules/custom/grants_handler/grants_handler.services.yml, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
Pull request for minor code style / documentation issues.
=> Fix code styles in grants handler module

conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaKehaDefinition.php
* Kehitysavustus webform
* also, one missing help from projekti
* `git checkout feature/AU-911-kuva-kehittamisavustus-update-for-design`
* `make fresh`
[AU-911]: https://helsinkisolutionoffice.atlassian.net/browse/AU-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-911 kuva kehittamisavustus update for design

conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, public/modules/custom/grants_metadata/grants_metadata.module, tools/make/override.mk, tools/make/project/avustusasiointi.mk
* `git checkout AU-1044-other-attachment-config-fix`
* `make fresh`
[AU-1044]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1044: Correct configuration to other attachment fields

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
Updates field mappings to work with Avusts2
* Mappings were tested and updated to work
[AU-1086]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1086: Update prject mappings

public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php
=> AU-xxx: Fix unexpected error

composer.json, composer.lock
Update ATV version to support service integration.
[AU-1143]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1143: ATV module version to feature branch

public/modules/custom/grants_handler/grants_handler.module
There was incorrect print link onoma asiointi pages. This fixes it.
* Update print link to a working one.
[AU-1144]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1144: Fix print link on oma asiointi pages.

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/fi/grants_metadata.settings.yml, conf/cmi/language/sv/grants_metadata.settings.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
Add new compensations to metadata configuration and changed KUVAKEHA to use these.
* `git checkout AU-1147-kuvakeha-compensation-types`
* `make fresh`
[AU-1147]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1147: KUVA KEHA Compensation types.

public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php
Piilota tyhjät rivit asiointiroolin valinnassa.
* `git checkout feature/AU-1120-hide-empty-rows`
* `make fresh`
Lisää käyttäjälle toimintaryhmä ja palaa asiointiroolin valintaan. Nyt toimintaryhmän valinnassa on tyhjä rivi.
Vaihda tähän bränchiin.
Tyhjä rivi on kadonnut.
[AU-1120]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1120 Hide unregistered companies without name

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaKehaDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php, public/modules/custom/grants_premises/src/GrantsPremisesService.php
* Add metadata to premise fields
* `git checkout AU-1070-premises-metadata`
* `make fresh`
[AU-1070]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1070: Add metadata to premises fields

conf/cmi/webform.webform.kuva_toiminta.yml
* Remove one conditional logic from KUVA toiminta, based on excel
* `git checkout feature/AU-1195-toiminnan-lahtokohdat`
* `make fresh`
[AU-1195]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1195: remove one conditional logic from KUVA toiminta

conf/cmi/language/en/system.site.yml, conf/cmi/language/sv/system.site.yml
* Translate title
* `git checkout feature/AU-1217-translate-title`
* `make fresh`
[AU-1217]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1217: translate title

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml, conf/cmi/language/sv/webform.webform.kasko_ip_lisa.yml, conf/cmi/webform.webform.kasko_ip_lisa.yml, public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_metadata/src/Plugin/DataType/KaskoIltapaivaLisaData.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KaskoIltapaivaLisaDefinition.php
[AU-978]: https://helsinkisolutionoffice.atlassian.net/browse/AU-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-978: Kasko Iltapäivätoiminnan harkinnanvarainen lisäavustushakemus 53

conf/examples/esimerkki_47_KUVATOIM.json, conf/examples/esimerkki_48_KUVAPROJ.json, conf/examples/esimerkki_49_KUVAKEHA.json, conf/examples/esimerkki_54_KANSLIATYO.json, conf/examples/esimerkki_55_KANSLIAKOTOUTUS.json, conf/examples/esimerkki_60_LIIKUNTATILANKAYTTO.json
=> Update ALL examles to latest versions.

public/modules/custom/grants_oma_asiointi/translations/sv.po
* Add missing translation to sv thank you -page
* `git checkout feature/AU-537-thankyou-page`
* `make fresh`
[AU-537]: https://helsinkisolutionoffice.atlassian.net/browse/AU-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-537: add translation to thankyou -page

composer.lock
Created at time was in many incorrect formats, this version should fix it.
* AUdit log to 0.9.6
=> fix: AU-XX: Audit log version to 0.9.6

test/tests/09__form_kasko_ip_lisa.robot, test/tests/10__form_nuorlomaleir.robot, tools/make/project/robot.mk
Basic robot test templates for couple of grant forms.
Added two basic tests for grant forms.
* `make fresh`
[AU-946]: https://helsinkisolutionoffice.atlassian.net/browse/AU-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-982]: https://helsinkisolutionoffice.atlassian.net/browse/AU-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-946: robot test templates

public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Add new roles to persons responsible for operations
* `git checkout feature/AU-1278-new-roles`
* `make fresh`
[AU-1278]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1278: Add new roles to persons responsible for operations

conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/translations/sv.po
* Removed description from page 4 premise
* Fixed translations in page 4 premise
* `git checkout feature/AU-1291-taiteen-perusopetus`
* `make fresh`
[AU-1291]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1291: fix Taiteen perusopetus premise

conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml, conf/cmi/language/sv/webform.webform.kasko_ip_lisa.yml, conf/cmi/webform.webform.kasko_ip_lisa.yml
* Translated webform title
* Add laskuri to Lisäselvitys liitteistä
* Remove liite info text
* `git checkout feature/AU-XX-kasko-ip`
* `make fresh`
[AU-1300]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1301]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1302]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1300, AU-1301, AU-1302: fixes to Kasko IPLISA

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.nuorlomaleir.yml, conf/cmi/language/sv/webform.webform.nuorlomaleir.yml, conf/cmi/webform.webform.nuorlomaleir.yml
* [AU-1333](https://helsinkisolutionoffice.atlassian.net/browse/AU-1333): Fix title in grants metadata and conf
* [AU-1334](https://helsinkisolutionoffice.atlassian.net/browse/AU-1334): Fix grant years
* [AU-1335](https://helsinkisolutionoffice.atlassian.net/browse/AU-1335): Remove "hae vain yhtä avustusta kerrallaan" text
* [AU-1336](https://helsinkisolutionoffice.atlassian.net/browse/AU-1336): Change descriptions to tooltips'
* [AU-1337](https://helsinkisolutionoffice.atlassian.net/browse/AU-1337): Change attachment info
* `git checkout feature/AU-XX-leiriavustus`
* `make fresh`
[AU-1333]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> fix: AU-1333, AU-1334, AU-1335, AU-1336, AU-1337: fixes to leiriavustus

conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
* Fix section title in taiteen perusopetus
* `git checkout feature/AU-1331-perusopetus`
* `make fresh`
[AU-1331]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1331: fix section title in taiteen perusopetus

conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, public/themes/custom/hdbt_subtheme/translations/sv.po
* `git checkout feature/AU-1359-translations`
* `make fresh`
[AU-1359]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1359: add minor translations

public/modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php
Fix warnings in official component.
[AU-1356]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1356: Add check for officials role for printing

public/modules/custom/grants_oma_asiointi/src/Controller/ApplicationsListController.php, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiBlock.php
=> fix: AU-XX: Fix front page application search

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_projekti.yml
* Add extra info to kuva projekti budget page
* `git checkout feature/AU-1371-projekti`
* `make fresh`
[AU-1371]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1371: add extra info to kuva projekti

conf/cmi/language/en/webform.webform.liikunta_tapahtuma.yml, conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml, conf/cmi/webform.webform.liikunta_tapahtuma.yml
* Fix toiminnasta vastaava henkilö in liikunta tapahtuma
* `git checkout feature/AU-1357-tapahtuma`
* `make fresh`
[AU-1357]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1357: fix toiminnasta vastaava henkilö in liikunta tapahtuma

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaKehaDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php, public/modules/custom/grants_webform_summation_field/grants_webform_summation_field.module, public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* Avustukset summa calculation
* Incorrect mappings
* Crash as private person, when trying to access /muokkaa endpoint of submitted application
* `git checkout feature/AU-1404-total-amount-and-mapping-fixes`
* `make fresh`
[AU-1404]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1396]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1398]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> AU-1404: Fix avustukset_summa prepopulation / calculation and some mapping fixes

conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_handler/config/install/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaKehaDefinition.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaToimintaDefinition.php
* Fix typo in sentence
* `git checkout feature/AU-1196-fix-typo`
* `make fresh`
* [Link to other PR
](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/510)
[AU-1196]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1196: Typofix

conf/cmi/block.block.hdbt_subtheme_footertopnavigation.yml, conf/cmi/block.block.servicepageauthblock.yml
* Fix language in block labels
=> fix: AU-XX: fix language in block labels

public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaProjektiDefinition.php
2 fields were mixed, this fixes that.
[AU-1420]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1420: Swap field mappings

conf/cmi/language/en/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
* Add correct translations from excel
* `git checkout feature/AU-1253-nuorisotoiminta-translations`
* `make fresh`
[AU-1253]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1253: fix nuorisotoiminta translations

conf/cmi/webform.webform.kuva_projekti.yml, public/modules/custom/grants_premises/src/Element/PremisesComposite.php
* Edit premise requirements
* Edit field title
* `git checkout feature/AU-1416-kuva-otsikko`
* `make fresh`
[AU-1416]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1416: edit premise requirements

public/modules/custom/grants_metadata/grants_metadata.module
* Add default values to suppress warning messages during make fresh
* `git checkout feature/AU-1403-fix-warnings
* `make fresh`
[AU-1403]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1403: Add defaults to suppress warnings

public/modules/custom/grants_metadata/src/TypedData/Definition/OtherCompensationDefinition.php
Pilkku hyppi muissa avustuksissa
Konfiguroi webformdata extractor ko kentälle
* `git checkout feature/AU-1444-amount-bug`
* `make fresh`
Täytä hakemukselle muita avustustietoja. Lisää senteille jokin arvo. Tallenna ja mene uudestaan lomakkeelle. Numeroarvot eivät enää muutu.
[AU-1444]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1444: Handle amount conversion in other compensation composite

public/modules/custom/grants_menu/src/ForceMenuLinkService.php
This pull request implements a minor change to the `ForceMenuLinkService.php` service. Previously service page node menu items were always forced to be under the "Avustukset" section in the menu. The changes make it so that the menu items are only put under said section if a content editor forgets to add the node to the menu in the first place.
**Functionality before:**
- If a service page is not in the menu, then put it under the "Avustukset" section.
- If a service page is in the menu but under the wrong section, then force it to be under the "Avustukset" section.
**Functionality now:**
- If a service page is not in the menu, then put it under the "Avustukset" section.
* `git checkout fix/AU-1456-service-page-menu-fix`
* …
=> fix/AU-1456: Changes to the ForceMenuLinkService serivice

conf/cmi/language/en/webform.webform.nuorlomaleir.yml, conf/cmi/language/sv/webform.webform.nuorlomaleir.yml, conf/cmi/webform.webform.nuorlomaleir.yml
* Open leiriavustus excel link in new tab
* `git checkout feature/AU-1424-fixes`
* `make fresh`
[AU-1424]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1424: open leiriavustus excel link in new tab

conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_menu/src/ForceMenuLinkService.php, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaPerusDefinition.php, public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
* [AU-1247](https://helsinkisolutionoffice.atlassian.net/browse/AU-1247): Translations from excel to perusopetus
* [AU-1430](https://helsinkisolutionoffice.atlassian.net/browse/AU-1430): Change from 3 to 4 boxes
* [AU-1437](https://helsinkisolutionoffice.atlassian.net/browse/AU-1437): fix problems in premises component
* `git checkout feature/AU-1430-1437-1332-1247-kuva-fixes`
* `make fresh`
[AU-1247]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1430]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> fix: AU-1247, AU-1430, AU-1437 Kulttuuri taiteen perusopetus fixes

conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
* Translations fixed to be what needed.
* `git checkout feature/AU-1432-1434-translation-fixes-taiteen-perusopetus`
* `make fresh`
[AU-1432]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1434]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1432, AU-1434: translation fixes

conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml
* [AU-1482](https://helsinkisolutionoffice.atlassian.net/browse/AU-1482) Edit text in applied and granted grants
* [AU-1483](https://helsinkisolutionoffice.atlassian.net/browse/AU-1483) Edit text in applied grants field
* `git checkout feature/AU-1482-nuoriso`
* `make fresh`
[AU-1482]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1483]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1482, AU-1483: fix nuoriso projekti fields

conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml
* Add the rest of the nuorproj translations
* `git checkout feature/AU-1497-nuorproj-translations`
* `make fresh`
[AU-1497]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1497: add the rest of the nuorproj translations

conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_attachments/src/AttachmentHandler.php, public/modules/custom/grants_attachments/translations/sv.po, public/modules/custom/grants_handler/translations/sv.po
* Check out the ticket descriptions from the top.
* Everything except the name of the attachment on the display page of the sent form (half of AU-1537) has been solved here.
* `git checkout feature/AU-1538-1437-1532-1533-1534-1535-1536-1537-bulk-test-fixes`
* `make fresh`
[AU-1437]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1532]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1533]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> fix: AU-1437, AU-1532, AU-1533, AU-1534, AU-1535, AU-1536, AU-1537, AU-1538: Various fixes

conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml
* [AU-1522](https://helsinkisolutionoffice.atlassian.net/browse/AU-1522): NUORPROJ Muut menot -> Menot
* [AU-1524](https://helsinkisolutionoffice.atlassian.net/browse/AU-1524): NUORTOIMPALKENNAKKO Kaikki alla luetut -> Kaikki vaaditut
* [AU-1529](https://helsinkisolutionoffice.atlassian.net/browse/AU-1529): LIIKUNTATILANKAYTTO Liikuntaseura
* `git checkout feature/AU-1524-conf-changes`
* `make fresh`
[UHF-1522]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-1524]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> fix: AU-1522, AU-1524 AU-1529: conf content changes

public/modules/custom/grants_club_section/src/Element/ClubSectionComposite.php, public/modules/custom/grants_club_section/translations/fi.po, public/modules/custom/grants_club_section/translations/sv.po, public/modules/custom/grants_premises/src/Element/RentIncomeComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
* Added translations to liikunta toiminta- ja tilankäyttö composites
* `git checkout feature/AU-1530-tilankaytto-translations`
* `make fresh`
[AU-1530]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1530: toiminta- ja tilankäyttö composite translations

conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.nuorlomaleir.yml
* Reverted / Corrected attachment checkbox / required settings to match excel.
* `git checkout feature/AU-1552-fix-wrong-attachment-settings`
* `make fresh`
[AU-1552]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1552: Fix incorrect configurations made to all nuoriso forms

conf/cmi/webform.webform.kasko_ip_lisa.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_handler/config/install/webform.webform.kasko_ip_lisa.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_projekti.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_handler/config/install/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, public/modules/custom/grants_handler/config/install/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_handler/config/install/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_metadata/tests/modules/grants_metadata_test_webforms/config/install/webform.webform.kuva_projekti.yml
* Typofix
* `git checkout feature/AU-1473-grey-box-title-fix`
* `make fresh`
[AU-1473]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1473: typo fix for haettut

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
* fix kuva application names
* `git checkout feature/AU-1573-kulttuuri-nimet`
* `make fresh`
[AU-1573]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1573: fix kuva application names

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/en/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml, conf/cmi/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml
* Add translations to application names
* `git checkout feature/AU-1576-hakemusten-nimet`
* `make fresh`
[AU-1576]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1576: Add translations to application names

conf/cmi/language/en/webform.webform.kasko_ip_lisa.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/en/webform.webform.nuorlomaleir.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/language/sv/webform.webform.nuorlomaleir.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, conf/cmi/webform.webform.nuorlomaleir.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
* Fix attachment counter
* (added wrong ticket number to branch name sorry)
* `git checkout feature/AU-1576-testipalautteet`
* `make fresh`
[AU-1576]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1583]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1583: fix attachment counter

conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml
* add missing translation
* `git checkout feature/AU-1576-missing-translation`
* `make fresh`
[AU-1576]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1576: add missing translation

conf/cmi/language/en/views.view.content.yml, conf/cmi/language/sv/views.view.content.yml, conf/cmi/views.view.content.yml
Lisätty kaksi filtteriä sisältönäkymään
* `git checkout feature/AU-1581-more-filters`
* `make fresh`
Kirjaudu adminina ja testaa sisältönäkymän suodatuksia. 
[AU-1581]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1581: Add more filters for content view

public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php
* `git checkout feature/AU-1575-sv-error`
* `make fresh`
Täytä liikunnan tapahtumalomake ja tallenna se keskeneräisenä. Älä lisää liitettä vaan valitse toinen checkboxi. Katso hakemusta (osoite tyyppiä `https://hel-fi-drupal-grant-applications.docker.so/sv/hakemus/GRANTS-LOCAL-LIIKUNTATAPAHTUMA-314159265/katso`) ja vaihda kieleksi Ruotsi.
[AU-1575]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1575: Fix error in Swedish version of form preview

public/modules/custom/grants_attachments/translations/fi.po, public/modules/custom/grants_attachments/translations/sv.po
* Add translations to Upload OK -string
* `git checkout feature/AU-1596-translate`
* `make fresh`
[AU-1596]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1596: add translations

conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml
* Text fix to form
* `git checkout feature/AU-1605-question-fix-nuorproj`
* `make fresh`
[AU-1605]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1605: text fix to nuor proj

public/modules/custom/grants_attachments/grants_attachments.install, public/modules/custom/grants_attachments/src/AttachmentHandler.php, public/modules/custom/grants_attachments/src/Controller/GrantsAttachmentsController.php, public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php, public/modules/custom/grants_attachments/src/Plugin/WebformElement/GrantsAttachments.php, public/modules/custom/grants_attachments/translations/fi.po, public/modules/custom/grants_attachments/translations/sv.po, public/modules/custom/grants_front_banner/templates/grants-front-banner.html.twig, public/modules/custom/grants_front_banner/translations/fi.po, public/modules/custom/grants_front_banner/translations/sv.po, public/modules/custom/grants_metadata/grants_metadata.install, public/modules/custom/grants_metadata/grants_metadata.module, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/translations/fi.po, public/modules/custom/grants_metadata/translations/override/fi.po, public/modules/custom/grants_metadata/translations/sv.po
See https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/762
=> feat: AU-852: Translationcontext to all modules 3/X

public/modules/custom/grants_mandate/js/disable-mandate-submit.js, public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php, public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php, public/modules/custom/grants_mandate/translations/fi.po, public/modules/custom/grants_mandate/translations/sv.po, public/modules/custom/grants_oma_asiointi/src/Controller/ApplicationsListController.php, public/modules/custom/grants_oma_asiointi/src/Controller/GrantsOmaAsiointiController.php, public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiBlock.php, public/modules/custom/grants_oma_asiointi/src/Plugin/Derivative/DynamicLocalTasks.php, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-block.html.twig, public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-infoboxes.html.twig, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_oma_asiointi/translations/sv.po
See https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/762
=> feat: AU-852: Add translation context to all modules 4/X

public/modules/custom/grants_application_search/translations/fi.po, public/modules/custom/grants_attachments/translations/fi.po, public/modules/custom/grants_attachments/translations/sv.po, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po, public/modules/custom/grants_mandate/translations/fi.po, public/modules/custom/grants_metadata/translations/sv.po, public/modules/custom/grants_oma_asiointi/translations/fi.po, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* There were a few old translations lying around, and typos, and punctuation errors in the previous pull request
* `git checkout feature/AU-852-X-updates`
* `make fresh`
[AU-852]: https://helsinkisolutionoffice.atlassian.net/browse/AU-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-852: missing/false translations.

public/modules/custom/grants_metadata/src/AtvSchema.php
Käännösongelma tulostusnäkymässä
Kovakoodaa kentälle erityiskäsittely ATVSchema luokassa.
* `git checkout .feature/AU-1646-translation-issue`
* `make fresh`
Täytä lomake jossa on myönnettyjä avustuksia.
Tallenna, ja katsele tulostusnäkymää. Issuer name kääntyy oikein.
[AU-1646]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1646 Handle issuer name translation

public/modules/custom/grants_premises/translations/fi.po
* fix postcode error translation
* `git checkout feature/AU-1638-translation`
* `make fresh`
[AU-1638]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1638: fix postcode error translation

conf/cmi/language/en/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
* [AU-1315](https://helsinkisolutionoffice.atlassian.net/browse/AU-1315): General translations
* [AU-1640](https://helsinkisolutionoffice.atlassian.net/browse/AU-1640): New applicant type
* [AU-1641](https://helsinkisolutionoffice.atlassian.net/browse/AU-1641): Remove extra text
* [AU-1643](https://helsinkisolutionoffice.atlassian.net/browse/AU-1643): Bold text
* `git checkout feature/AU-1315-toimintatilankaytto`
* `make fresh`
[AU-1315]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1340]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> fix: AU-1315, AU-1640, AU-1641, AU-1643: Liikunta toiminta- ja tilankäyttö fixes and translations

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
* Change warning text
* `git checkout feature/AU-1661-change-warning-text`
* `make fresh`
[AU-1661]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1661: change error text

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* check if route exists in subtheme
* `git checkout feature/AU-1663-route-error`
* `make fresh`
[AU-1663]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1663: check if route exists in subtheme

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_projekti.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_handler/config/install/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_metadata/tests/modules/grants_metadata_test_webforms/config/install/webform.webform.kuva_projekti.yml
* Kuvataide conf value fixed to include comics
* `git checkout feature/AU-1679-conf`
* `make fresh`
[AU-1679]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1679: fix kuvataide value in conf

public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
* Trim whitespace from bank account
* `git checkout feature/AU-1669-iban`
* `make fresh`
[AU-1669]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1669: add trim to bank accounts

composer.json, composer.lock, conf/cmi/core.extension.yml, conf/cmi/raven.settings.yml
It seems that we've been missing some key components for error handling with missing Sentry installation. This adds that and Raven module to log drupal errors to Sentry.
* Add raven to composer
* install it + add config
* add sentry keys in pipeline running.
[AU-1712]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1712: Enable Sentry & Raven for better logging

.github/workflows/update-config.yml, docker/openshift/entrypoints/90-deploy.sh
Trying to figure out issues with configs & deployments.
[AU-1724]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1724: Fix configs

docker/openshift/entrypoints/20-deploy.sh
Sites stay in maintenance mode for unknown reasons. Here we try to find out what's going on.
* Try to log things to see what's happening.
[AU-1724]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-1724: Add debug things to see why deployments fail

public/themes/custom/hdbt_subtheme/translations/sv.po
This pull request implements Swedish translations to Open ID.
* `git checkout feature/AU-1655-open-id-swedish-translations`
* `make fresh`
- Review the translations.
- Run `drush locale:check; drush locale:update; drush cr `and check that nothing breaks.
[AU-1655]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1655: Swedish translations to Open ID

public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Use correct language in empty form print preview page.
* `git checkout feature/AU-1574-form-preview-translations`
* `make fresh`
[AU-1574]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1574: Handle composite field translations in empty form print preview

public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_metadata/src/AtvSchema.php
Käännä select kentässä valittu sisältö tulostusnäkymää varten.
Lisää käännös metatietoihin.
* `git checkout feature/AU-1659-select-value-translations-for-print-view`
* `make fresh`
Täytä lomake jossa on select kenttiä.
Tallenna ja tarkastele että arvot ovat kääntyneet.
[AU-1659]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1659: Translate select field values in print view

public/modules/custom/grants_metadata/src/AtvSchema.php
Yksikkötestit feilaavat.
Lisää parempi tarkastus arvon olemassaololle.
* `git checkout feature/AU-801-error-fix`
* Aja grants_metadatan yksikkötestit. Nyt ne menevät läpi ongelmitta. 
[AU-801]: https://helsinkisolutionoffice.atlassian.net/browse/AU-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-801: Fix error related to non-existent array keys

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.nuortoimpalkka.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_webform_summation_field/grants_webform_summation_field.module
* Form fixes
* Waiting for translations, thus draft.
* `git checkout feature/AU-1719-form-changes-for-states`
* `make fresh`
[AU-1719]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1719: Make things respond to states on NuorToimPalk form

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* check if is application period object
* `git checkout feature/AU-1757-fix-etsi-avustusta`
* `make fresh`
[AU-1757]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1757: check if application period is object

public/modules/custom/grants_applicant_info/src/ApplicantInfoService.php, public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/tests/data/kuva_projekti.unregistered.data.json, public/modules/custom/grants_metadata/tests/modules/grants_metadata_test_webforms/src/GrantsProfileServiceTest.php, public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php
Lisää ATVSchema testien kattavuutta. 
Testaa rekisteröimätöntä yhteisöä.
* `git checkout feature/AU-801-test-with-unregistered-community`
[AU-801]: https://helsinkisolutionoffice.atlassian.net/browse/AU-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: AU-801: Add tests for unregistered community

public/modules/custom/grants_handler/src/Plugin/WebformElement/BankAccountComposite.php, public/modules/custom/grants_metadata/src/AtvSchema.php
Näytä pankkitilin tiedot toimintaryhmälle hakemuksen katselutilassa.
Käsittele tilidata oikein kun se haetaan ATV:stä ja varmista että oikeat kentät näytetään.
* `git checkout feature/AU-1756-bank-account-fix`
* `make fresh`
=> fix: AU-1756: Show all account details in application view

public/modules/custom/grants_members/translations/fi.po, public/modules/custom/grants_members/translations/sv.po
* Fix translation on page 3 of nuortoimpalk
* `git checkout feature/AU-1774-nuorisopakkaus-langufix`
* `make fresh`
[AU-1774]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1774: remove context from contextless setLabel translation

conf/cmi/webform.webform.nuortoimpalkka.yml
* Added conditional required fields to NuorToimPalk form
* `git checkout feature/AU-1787-more-required-fields`
* `make fresh`
[AU-1787]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1787: add conditional required fields to nuortoimpalk

public/modules/custom/grants_orienteering_map/src/Element/OrienteeringMapComposite.php
* Added a dot.
* `make fresh`
[AU-1798]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1798: Fix error language

public/modules/custom/grants_handler/src/Controller/ApplicationController.php
Näytä tulostuksessa päiväykset kivassa muodossa loppukäyttäjälle
Käsittele päivämäärät ennen tulostusta
* `git checkout feature/AU-1699-dates-in-printing`
* `make fresh`
[AU-1699]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1699: Handle dates in print view

public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
unserialize <-> JSON::decode do not work together, if serialize is used, it needs to be decoded with unserialize.
* unserialize with JSON::decode
* `make fresh`
[AU-1832]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1832: Replcase unserialize with JSON::decode

public/modules/custom/grants_profile/src/GrantsProfileService.php, public/modules/custom/grants_profile/src/ProfileConnector.php
Uuid import
Call to helsinki profiii
* `git checkout feature/hotfix-uuid-import`
* `make fresh`
=> fix: Fix error related to grants profile rewrite

public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* New role
* `git checkout feature/AU-1825-new-role`
* `make fresh`
[AU-1825]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1825: New role for toiminnasta vastaavat henkilöt in profile

conf/cmi/language/en/webform.webform.kuva_projekti.yml
* Fixed page 5 en translations to match excel
* `git checkout feature/AU-1852-kuva-translations`
* `make fresh`
[AU-1852]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1852: fix kuva projekti page 5 en translations

public/modules/custom/grants_metadata/src/AtvSchema.php
Ehkäise vääränlaisen metadata päätyminen ATV:hen.
Eräät muuttujat pysyivät muuttumattomina foreach loopissa jolloin edellisen iteraatiokerran data päätyi vaikuttamaan seuraavaan iteraatioon tietyin edellytyksin. Tämä on on estetty.
* `git checkout feature/AU-1868-print-view-error`
* `make fresh`
[AU-1868]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1868 Prevent erroneous data ending in metadata

public/modules/.gitignore
Avoid accidentally committing test reports to repository.
=> test: Add test report files in gitignore

docker/openshift/notify.php
Trying to enable release based things in [Sentry](https://docs.sentry.io/platforms/php/configuration/releases/).
* Add Sentry calls to notify.php
[AU-1886]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1886: Add SENTRY release

conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
* Fixed translations in kuva kehittamisavustus
* `git checkout feature/AU-1869-kehittamisavustus-translations`
* `make fresh`
* IF NEEDED:
* Go to [Ignore](https://hel-fi-drupal-grant-applications.docker.so/fi/admin/config/development/configuration/ignore)
* Remove webform-line and save
* Run `drush cim` in shell
[AU-1869]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1869: fix kuva kehittamisavustus translations

public/modules/custom/grants_industries/grants_industries.module
* Site-install was failing and thus latest.sql didn't generate correctly.
=> fix: AU-XXX: Fix site install

public/modules/custom/grants_applicant_info/src/ApplicantInfoService.php
* Currently the logic is truthy in every case and causes weird issues with permission check etc (Cannot create or edit forms)
* `git checkout feature/AU-xxx-fix-applicant-info-if-statements`
* `make fresh`
=> fix: AU-XXX: Fix applicant info if statements

conf/cmi/language/en/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/en/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/en/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/en/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/en/webform.webform.ymparistopalvelut_yleisavustus.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml, conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/webform.webform.yleisavustushakemus.yml, conf/cmi/webform.webform.ymparistopalvelut_yleisavustus.yml
* Changed Kaupungilta saadut lainat ja takaukset characters 500 -> 5000
* Changed Kaupungilta saatu tiloihin liittyvä tuki characters 500 -> 5000
* `git checkout feature/AU-1867-characters`
* `make fresh`
[AU-1867]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1867: fix Kaupungilta saadut lainat ja takaukset characters

public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/tests/data/yleisavustushakemus.data.json, public/modules/custom/grants_metadata/tests/modules/grants_metadata_test_webforms/src/TypedData/Definition/FailedDataDefinition.php, public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php
Lisää testien code coveragea ATVScheman uudelleenkirjoitusta varten.
Lisää testicaset erikoistapauksille joita ei vielä käsitelty.
Lisää kommentit koodikohtiin joita ei testata.
* `git checkout feature/AU-1895-improve-test-code-coverage`
* Aja testit
* Tarkastele code coverage raporttia
[AU-1895]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: AU-1895: Add special test cases to improve code coverage in ATVSchema

public/modules/custom/grants_mandate/translations/fi.po, public/modules/custom/grants_mandate/translations/sv.po, public/modules/custom/grants_profile/translations/fi.po, public/modules/custom/grants_profile/translations/sv.po
* Fix new rekisteröitymätön yhteisö translations
* `git checkout feature/AU-1906-translations`
* `make fresh`
[AU-1906]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1906: Fix unregistered translations

azure-pipelines-test.yml
Added, batch: true, to avoid simultaneous runs of same pipeline azure-pipelines-test.yml
Same setting already present in azure-pipelines-prod.yml
=> Added, batch: true, to avoid simultaneous runs of same pipeline azure-pipelines-test.yml

conf/cmi/webform.webform.liikunta_suunnistuskartta_avustu.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
* confs were missing some opening and closing times.
* `git checkout feature/AU-1887-AU-1909-opening-time-changes`
* `make fresh`
[AU-1887]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1909]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1908]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1887, AU-1908: Change times to form confs

public/modules/custom/grants_handler/grants_handler.module
* Add redirect to grants admin login
* `git checkout feature/AU-1073-admin-redirect`
* `make fresh`
[AU-1037]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1037: add redirect to grants admin login

docker-compose.override.yml, e2e/package-lock.json, e2e/package.json, public/themes/custom/hdbt_subtheme/package-lock.json, public/themes/custom/hdbt_subtheme/package.json
* Merged all snyks and tested, required a further fix
* `git checkout feature/AU-TEST-SNYK-automatics`
* `make fresh`
=> fix: Automated snyk updates

public/modules/custom/grants_metadata/src/AtvSchema.php, public/modules/custom/grants_metadata/src/InputmaskHandler.php
* `make fresh`
https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1025
=> fix: AU-xxx: Add default empty array to method

composer.json
Aja phpcs aina samanlaisilla asetuksilla jotka vastaavat githubia
Päivitä komennot comoser.jsoniin
* `git checkout feature/AU-710-fix-composer-commands`
* `make shell`
* `composer phpcs-xxx`
[AU-710]: https://helsinkisolutionoffice.atlassian.net/browse/AU-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-710 Improve linting commands in composer.json

README.md, public/modules/custom/config/install/webform.webform.asukasosallisuus_pienavustushake.yml, public/modules/custom/config/install/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, public/modules/custom/config/install/webform.webform.grants_handler.yml, public/modules/custom/config/install/webform.webform.hyte_yleisavustus.yml, public/modules/custom/config/install/webform.webform.kasko_ip_lisa.yml, public/modules/custom/config/install/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, public/modules/custom/config/install/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, public/modules/custom/config/install/webform.webform.kaupunginkanslia_tyollisyysavust.yml, public/modules/custom/config/install/webform.webform.kuva_projekti.yml, public/modules/custom/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/config/install/webform.webform.liikunta_laitosavustushakemus.yml, public/modules/custom/config/install/webform.webform.liikunta_suunnistuskartta_avustu.yml, public/modules/custom/config/install/webform.webform.liikunta_tapahtuma.yml, public/modules/custom/config/install/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, public/modules/custom/config/install/webform.webform.liikunta_yleisavustushakemus.yml, public/modules/custom/config/install/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml, public/modules/custom/config/install/webform.webform.nuorisotoiminta_projektiavustush.yml, public/modules/custom/config/install/webform.webform.nuorlomaleir.yml, public/modules/custom/config/install/webform.webform.nuortoimpalkka.yml, public/modules/custom/config/install/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/config/install/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/config/install/webform.webform.ymparistopalvelut_yleisavustus.yml, public/modules/custom/grants_handler/grants_handler.info.yml, public/modules/custom/grants_handler/grants_handler.services.yml, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_industries/grants_industries.module
This pull request fixes the following error when performing a fresh Drupal-install: 
`The service "grants_handler.application_handler" has a dependency on a non-existent service "grants_attachments.attachment_handler`
* `git checkout feature/AU-1964-dependency-fix`
* `make fresh`
Run `drush si -y && drush cr && drush si --existing-config -y && drush cim -y && drush gwi --force` in your local development environment and check that the install goes through to the end.
[AU-1964]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1964: Fixing dependency error

conf/cmi/language/en/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/webform.webform.nuortoimpalkka.yml
* [AU-1956](https://helsinkisolutionoffice.atlassian.net/browse/AU-1956): Page 3 tooltips
* [AU-1968](https://helsinkisolutionoffice.atlassian.net/browse/AU-1968): Page 3 and 5 character counters
* [AU-1974](https://helsinkisolutionoffice.atlassian.net/browse/AU-1974): Page 4 text update
* `git checkout feature/AU-1968-nuorisotoimipalk`
* `make fresh`
* [Open application](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/nuortoimpalkka)
* Go to page 2 and fill Wage subsidy and check that you are applying for a rent grant
* Go to page 3 
* Check that "Young people’s participation times in the activities of the association" fields have tooltips
* Check that "Young people’s participation in …
=> fix: AU-1956, AU-1968, AU-1974: Small fixes to nuortoimpalk

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_handler/src/GrantsHandlerSubmissionStorage.php
Vähennä turhia kutsuja ATV moduuliin jotta koodin suoritus olisi nopeampaa.
- Luo uusi tapa ladata submission-objekti annetulla ATV datalla
- Käytä eri metodia webformin otsikon hakemiseen
- Välitä submission objekti application status tagin renderöintiä varten äläkä hae sitä erikseen.
* `git checkout feature/AU-1985-decrease-atv-calls`
* `make fresh`
=> feat: AU-1985: Decrease atv calls

public/modules/custom/grants_handler/src/EventSubscriber/ForceCompanyAuthorisationSubscriber.php
Vähennä ylimääräistä koodin ajoa ForceCompanyAuthorisationSubscriber-luokassa.
Selkiytä logiikkaa ForceCompanyAuthorisationSubscriber-luokassa jotta access kyselyitä tehdään vähemmän.
Käytä RedirectResponse-luokkaa sillä TrustedRedirectResponse on tarkoitettu ohjaamiseen Drupalin ulkopuolelle
* `git checkout feature/AU-1989-optimize-force-company-authorisation-subscriber`
* `make fresh`
[AU-1989]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1989: Optimize ForceCompanyAuthorisationSubscriber class

public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
* Currently Drupal is throwing white screen of death, when you try to print a sent application. 
* `git checkout feature/AU-1992-fix-print-error`
* `make fresh`
[AU-1992]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1992: Fix application print white screen error

conf/cmi/grants_metadata.settings.yml
This PR will set all recently published applications to production ignore.
[AU-1348]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> config: AU-1348, AU-1347, AU-1842, AU-1354, AU-1330, AU-1323, AU-1316: Publish applications

conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.hyte_yleisavustus.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml, conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml
* Add silent hyphens to long swedish words in form section headers.
* `git checkout feature/AU-1913-Undersodskategorier`
* `make fresh`
[AU-1913]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-1913: add - to swedish long words in forms

public/modules/custom/grants_handler/grants_handler.module, public/modules/custom/grants_handler/src/Controller/ApplicationController.php, public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
Tämä tuli esiin kun yritti mennä suljetulle lomakkeelle, jolle ei ollut palvelusivua. Tällöin myös lokiin tuli paljon virheitä.
* Varmista että palvelusivu on löytynyt, ennen sen käyttämistä
* Lisää virheilmoitus aiheesta
* Käännä virheilmoitus kun lomake ei ole auki.
* Lisää logiikkaa uuden lomakkeen luontitilanteeseen jotta loki ei täyty turhaan virheilmoituksista
* `git checkout feature/AU-2064-new-application-redirect-fix`
* `make fresh`
Käyttäjän voisi ohjata muuallekin mutta se että ylipäätään ohjaus tapahtuu tuotannossa on epätodennäköistä. Se vaatii sen että käyttäjällä on suora linkki lomakkeeseen jolle sisällönsyöttäjät eivät ole asettaneet palvelusivua.
Koodiparannukset vähentävät joka …
=> fix: AU-2064 Fix redirect to new application

e2e/tests/forms/registered_community_56.ts, e2e/utils/data/application/application_data_56.ts
* Test for LIIKUNTAYLEIS 56
* `git checkout feature/AU-959-tests-56`
* `make fresh`
[AU-959]: https://helsinkisolutionoffice.atlassian.net/browse/AU-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-959: tests for 56

e2e/tests/forms/registered_community_54.ts, e2e/utils/data/application/application_data_54.ts, e2e/utils/data/application/application_data_registered_community.ts
* Test for KANSLIATYO 54
* `git checkout feature/AU-1307-tests-54`
* `make fresh`
[AU-1307]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1307: tests for 54

e2e/tests/forms/registered_community_68.ts, e2e/utils/data/application/application_data_68.ts, e2e/utils/data/application/application_data_registered_community.ts
* Test for HYTEYLEIS 68
* `git checkout feature/AU-1841-tests-68`
* `make fresh`
[AU-1841]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1841: tests for 68

public/modules/custom/grants_handler/src/GrantsHandlerSubmissionStorage.php, public/modules/custom/grants_metadata/src/AtvSchema.php
* Move applicant_type parsing to documentContentToTypedData method
* As this webform field is filled progmatically it's mapping doesn't match the webform element. Conditional checks still require that this elements values is correct, otherwise preview pages will not show email/address fields if there is conditions for applicant_type
* `git checkout feature/AU-2089-fix-applicant_type`
* `make fresh`
Previously fixed in https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1070 but there has been some changes after that, which broke the fix.
[AU-2089]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> AU-2089: Applicant type to documentContentToTypedData method

README.md, e2e/.env.example, e2e/.gitignore, e2e/package-lock.json, e2e/package.json, e2e/playwright.config.ts
Ympäristömuuttujien käytön helpottaminen kehittäjille e2e-testeissä.
* Asenna dotenv paketti
* Laita paketti käyttöön
* Päivitä ohjeistus
* `git checkout feature/AU-2016-env-variables-in-e2e-tests`
* `make fresh`
* Tee .env tiedosto
[AU-2016]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2016 Env variables in e2e tests

composer.lock
update helsinki profiili
[AU-2146]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2146: Update helsinki profiili integration to 0.9.21

public/modules/custom/grants_profile/js/profile_dialog.js, public/modules/custom/grants_profile/translations/fi.po
* Fix attaching multiple event listeners
* Minor typo fix
* `git checkout feature/AU-2152-fix-multiple-event-listeners`
* `make fresh`
[AU-2152]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2152: Fix profile dialog event listeners attaching multiple times

conf/cmi/grants_metadata.settings.yml
* Change KEHA avustuslaji term
* `git checkout feature/AU-2200-keha-avustuslajit`
* `make fresh`
[AU-2200]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2200: change KEHA avustuslaji term

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_premises/src/Element/PremisesComposite.php, public/modules/custom/grants_premises/translations/fi.po, public/modules/custom/grants_premises/translations/sv.po
* Made changes to KUVA applications contents
* `git checkout feature/AU-2195-kuva-hakemukset`
* `make fresh`
[AU-2195]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2195: text changes in KUVA applications

.github/workflows/update-config.yml, composer.json, composer.lock
Automatic updates were broken in upstream changes. This PR fixes those in our codebase as well. Also move back to main branch for helfi_tools.
* helfi_tools was set to use main branch
* some updates for github & config files we brought over
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/213)
[AU-2234]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2234: Update helfi tools and update-platform configs

conf/cmi/webform.webform.kuva_toiminta.yml
* Change word on KUVA toiminta
* `git checkout feature/AU-2250-toiminta`
* `make fresh`
[AU-2250]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2250: change word on KUVA toiminta

composer.json, composer.lock
* Updated ATV module to apply fixes done there.
* `git checkout feature/AU-2214-fix-gdpr-endpoints`
* `make fresh`
[AU-2214]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2214: ATV module updato to fix gdpr endpoints

conf/cmi/grants_metadata.settings.yml, e2e/package-lock.json, e2e/package.json, e2e/playwright.config.ts, e2e/utils/data/application/application_data_48.ts, e2e/utils/data/application/application_data_52.ts, e2e/utils/data/application/application_data_58.ts, e2e/utils/data/application/application_data_63.ts, e2e/utils/data/application/application_data_69.ts, e2e/utils/deletion_helpers.ts, e2e/utils/form_helpers.ts
This pull request implements the possibility to add `dynamic multi-value` and `multi-value` item fields (e.g. `edit-vuokratun-tilan-tiedot-items-0-item-rentsum`) to a form variants (e.g. `missingValues`) `itemsToRemove` property.
Added the possibility to add `dynamic multi-value` and `multi-value` item fields to `itemsToRemove`. This required making changes `createFormData()` and the installation of the [lodash cloneDeep](https://lodash.com/docs/4.17.15#cloneDeep) library. 
The installation of the library was needed to prevent unintended side effects on the base form data when removing multi-value item fields from a form variant (such as mutations to the base form's multi-value fields). Basically, the `createFormData()` function was making `shallow copies` of the form data before, and now …
=> feat: AU-2226, E2E, Implemented the possibilit to remove multi-value items with the itemsToRemove property

public/modules/custom/grants_metadata/grants_metadata.module
* Changed the dropdown to disabled state and only show the possible parent webform if available (There is no need manually add these links).
* Added create new version link below the parent field-
* `git checkout AU-2206-parent-selection-and-duplicate-button`
* `make fresh`
[AU-2206]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2206: Change dropdown and add link to duplicate page

public/modules/custom/grants_admin_applications/grants_admin_applications.info.yml, public/modules/custom/grants_admin_applications/src/Form/AtvFormBase.php, public/modules/custom/grants_admin_applications/src/Form/ResendApplicationsForm.php, public/modules/custom/grants_admin_applications/translations/fi.po, public/modules/custom/grants_handler/src/ApplicationHandler.php, public/modules/custom/grants_handler/src/EventsService.php
* Save-id is now regenerated when resubmitting an application
* Added a way to resend application messages.
* `git checkout feature/AU-2268-message-resend`
* `make fresh`
[AU-2268]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2289: Add possibility to resend application messages

public/modules/custom/grants_admin_applications/src/Form/SubmittedApplicationsForm.php
* Added possibility to apply filters to filter applications by status and creation/update times in admin application listing
* `git checkout feature/AU-2290-document-search-params`
* `make fresh`
[AU-2290]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2290: Document status and date search parameters

e2e/README.md, e2e/playwright.config.ts
This pull request implements a `.readme` file with E2E test instructions. The file contains:
1. A general description of E2E tests with Playwright.
2. A description of the implemented tests.
3. A description of the .env file.
4. Instructions on running tests in a docker container.
5. Instructions on running tests on a local machine.
- `playwright.config.ts`: 
- Cleaned up the file.
- Added all tests files to the `project` section.
- Added `forms-all` to the project section. This allows us to run all the form tests with `make test-pw-p PROJECT=forms-all
`
Review the `.readme` file and the changes in the `playwright.config.ts` file.
[AU-2148]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> feat: AU-2275: E2E, Added a .readme file.

e2e/utils/data/profile_data_registered_community.ts, public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php
* Fix wrapper name in registered community profile tests
* `git checkout feature/AU-2324-profile-tests`
* `make fresh`
[AU-2324]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2324: fix profile tests

conf/cmi/language/en/webform.webform.yleisavustushakemus.yml, conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml
* Translate pattern error
* `git checkout feature/AU-2310-khyleis`
* `make fresh`
[AU-2310]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2310: translate pattern in khyleis

conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml
* Fixes to translations according to excel
* `git checkout feature/AU-2356-kuva-toiminta`
* `make fresh`
[AU-2356]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2356: kuva toiminta translations

postman/ATV.postman_collection.json, postman/YTJ.postman_collection.json, postman/Yrtti.postman_collection.json
Postman sharing is very limited in free version, so not all team members have access to shared stuff.
* Add most important collections to version control for importing.
[AU-1882]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-1882: Add Postman collections

public/modules/custom/grants_admin_applications/src/Form/DeleteApplicationsForm.php, public/modules/custom/grants_admin_applications/src/Form/ResendApplicationsForm.php, public/modules/custom/grants_admin_applications/src/Service/HandleDocumentsBatchService.php, public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
Fix PHPCS errors caused by autoformat in previous PR
[AU-2336]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AU-2336: Make PHPCS happy

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_projekti.yml
* Kuva projekti change in text
* `git checkout feature/AU-2458-kuva-projekti`
* `make fresh`
[AU-2458]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2458: kuva projekti change in text

conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, e2e/playwright.config.ts, e2e/tests/forms/registered_community_67.ts, e2e/utils/data/application/application_data_67.ts, e2e/utils/data/application/application_data_registered_community.ts
* Added tests for application 67
* `git checkout feature/AU-2404-tests-67`
* `make fresh`
[AU-2404]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2404: tests for 67

docker/openshift/crons/base.sh
* Enabled pubsub cron for environments.
* `git checkout feature/AU-2368-cron`
* `make fresh`
[AU-2368]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: AU-2368: Enable pubsub cron job

composer.lock
GDPR api moduulin toiminta
* Korjaa D10 yhteensopivuusongelma gdpr api moduulissa
* Korjaa moduulissa koodin tyyliasioita
* Tee moduulista uusi release
* Päivitä moduuli tässä projektissa
* `git checkout feature/AU-2487-request-stack`
* `make fresh`
=> fix: AU-2487: Update gdpr api module

conf/cmi/grants_handler.settings.yml, public/modules/custom/grants_handler/config/grants_handler.settings.yml
* Update status text
* `git checkout feature/AU-2493-status-text`
* `make fresh`
[AU-2493]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2493: update status text

public/modules/custom/grants_handler/templates/application-list.html.twig
* `git checkout feature/AU-2436-listjs`
* `make fresh`
[AU-2436]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2436: fix the listjs pagination on oma asiointi

public/modules/custom/grants_handler/grants_handler.services.yml, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php, public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAuthBlock.php, public/modules/custom/grants_handler/src/ServicePageBlockService.php, public/modules/custom/grants_handler/templates/grants-service-page-block.html.twig
This pull request implements logic changes to the `ServicePageAuthBlock` and `ServicePageAnonBlock` blocks. In addition to this, the code has been cleaned up by extracting lots of duplicate code to its own service, the `ServicePageBlockService`. The blocks should now work with the following logic:
- If a service page has not referenced a Webform, then neither of the blocks are displayed.
- If a service page does reference a Webform, but the application is not open, then a "This application is not open" message should be displayed to the user.
- If a service page does reference a Webform and the application is open, but the user has the wrong role, then a "Change your role" message should be displayed to the user.
- In other cases, a link to the Webform should be displayed.
Make sure your …
=> feat: AU-2488: Changes to service page blocks.

conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
* Remove extra label
* `git checkout feature/AU-2434-small-fix`
* `make fresh`
[AU-2434]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AU-2434: remove extra label

composer.json, composer.lock, phpunit.xml.dist
Päivitä moduulien koodit ajantasalle
* Päivitä omissa pullareissa päivitetyt koodit.
* `git checkout feature/AU-2513-update-modules`
* `make fresh`
[AU-2513]: https://helsinkisolutionoffice.atlassian.net/browse/AU-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: AU-2513, AU-1929: Update modules

public/modules/custom/grants_admin_applications/src/Form/DeleteApplicationsForm.php, public/modules/custom/grants_admin_applications/src/Service/HandleDocumentsBatchService.php
* Checked that coding standard tests are up to date and pass.
[UHF-9945]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9945: Fix phpcs errors

public/sites/default/staging.settings.php
* Enable js/css aggregation on staging env
* `git checkout feature/AU-xxx-staging-asset-preprocess`
* `make fresh`
=> config: Add preprocessing to staging js/css

composer.json, composer.lock, public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php, public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php, public/modules/custom/grants_profile/src/GrantsProfileService.php
Hups automaationa mergesin hyväksytyt. Mut täähän pitääki tehä relluks..
=> Revert "fix:  AU-2518: Profile form fixes"

composer.json, composer.lock
* Update autologout module.
* `git checkout UHF-10630-autologout`
* `make fresh`
[UHF-10630]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10630: Update autologout

public/modules/custom/grants_handler/templates/grants-handler-print-atv-document.html.twig
* Uncomment the printing script to make printing button work again
* `git checkout UHF-10650`
* `make fresh`
[UHF-10650]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10650: Fix printing on applications

.gitignore, conf/examples/esimerkki_72_SOTEPEYLEIS.json, conf/tietoliikennesanoma_schema.json
Documentation ticket, this adds new example & updated schema. New form will have it's own ticket & PR.
[UHF-10807]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: UHF-10807: Add example for new form + update schema

conf/examples/esimerkki_71_HYTEEDYLEIS.json, conf/tietoliikennesanoma_schema.json
Example for new form & schema update
[UHF-10806]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: UHF-10806: Example for form ID71 & schema updates

conf/cmi/language/en/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/language/sv/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml
Missing translations for erillishakemus
=> Uhf x more tranlations

conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.yleisavustushakemus.yml
Some STEA's were still remaining after the ticket had been finished. Let's remove those.
=> fix: UHF-XX: Remove some remaining STEAs..

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/language/fi/grants_metadata.settings.yml, conf/cmi/language/sv/grants_metadata.settings.yml, conf/cmi/language/sv/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml
=> UHF-10711: Form & translation fixes

conf/cmi/language/sv/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml
=> UHF-10711: Last(?) fixes..

composer.lock, conf/cmi/language/sv/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml
=> Uhf 10711 fixes 3

public/sites/default/all.settings.php
Allow login with high eIDAS levels of assurance (e.g. smart card.)
https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/eIDAS+Levels+of+Assurance
[UHF-10952]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10952: Allow login with high eIDAS levels of assurance

conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, e2e/utils/data/application/application_data_70.ts
* One fix to form #states & visibility.
* Update tests to pass
* `git checkout UHF-10711-fixes-4`
* `make fresh`
[UHF-10711]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10711: Last fix to form & test update

public/modules/custom/grants_club_section/translations/sv.po
Add missing translations.
[UHF-10883]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10883: Add missing translations

conf/cmi/webform.settings.yml, conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/webform.webform.grants_handler.yml, conf/cmi/webform.webform.liikunta_tapahtuma.yml
We had some incorrect settings for forms and default values for informing user about changes & how back button works.
This sets all forms to track user changes & sets the default value.
=> Set form_submit & form_submit_back values for forms & default values.

conf/cmi/language/en/webform.webform.sotepe_yleis.yml, conf/cmi/language/sv/webform.webform.sotepe_yleis.yml, conf/cmi/webform.webform.sotepe_yleis.yml
AC-testing text fixes.
[UHF-10456]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10456: Compensation purpose fixes

public/modules/custom/grants_handler/js/application-copy-dialog.js, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po, public/themes/custom/hdbt_subtheme/templates/webform/application-copy-dialog-content.html.twig
* Missing translations
* Fixed implementation.
* `make fresh`
[UHF-10903]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10903: Fix missing dialog translations.

conf/cmi/language/en/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/language/sv/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml
=> UHF-10711: Fixes per comments

e2e/utils/data/application/application_data_48.ts, e2e/utils/data/application/application_data_52.ts
* Uncommented previously failing tests.
* `git checkout UHF-10345`
* `make fresh`
[UHF-10345]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10345: Uncommented previously failing tests.

conf/cmi/grants_metadata.settings.yml, conf/cmi/language/en/webform.webform.hyteed_yleis.yml, conf/cmi/language/sv/webform.webform.hyteed_yleis.yml, conf/cmi/webform.webform.hyteed_yleis.yml, public/modules/custom/grants_metadata/src/Plugin/DataType/HyteedYleisData.php, public/modules/custom/grants_metadata/src/TypedData/Definition/HyteedyleisDefinition.php
Add new form according to spec.
* Add new form configs
* Add new `grants_metadata` objects
* `git checkout origin/UHF-10455`
* `make fresh`
* Open up new form: http://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/hyteed_yleis
* Follow the Suomi.fi process
* You are redirected out of the form after logging in, use the link again to get back to the form
* Fill in the form. Intermittently use the "Save as a draft" button and see if it works.
* Submit the form.
* Wait of the application status to update to "Received"
* Click on the "View application" button.
* Try sending some messages for good measure. 
* Verify that data matches what you tried to send.
[UHF-10455]: …
=> UHF-10455: Add new General grants for welfare and health promotion form

public/modules/custom/grants_handler/src/EventSubscriber/ForceCompanyAuthorisationSubscriber.php
* Use trim and rawurlencode to prevent possible infinite loop.
* `git checkout UHF-X_trim_requestUri`
* `make fresh`
=> UHF-X Trim requestUri

public/modules/custom/grants_handler/src/EventSubscriber/ForceCompanyAuthorisationSubscriber.php
Hotfix:
[Use trim and rawurlencode to prevent possible infinite loop.](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/commit/88c3a6bdd9a64b8a3e680bf0df1a0c775cd3b0c4)
=> UHF-X RequestUri Hotfix

conf/cmi/webform.webform.liikunta_tapahtuma.yml, conf/cmi/webform.webform.ymparistopalvelut_yleisavustus.yml
Fetched config changes from production
=> changes for release

public/modules/custom/grants_handler/src/ApplicationGetterService.php
=> Uhf 11127 hotfix

conf/cmi/language/sv/webform.webform.hyteed_yleis.yml, conf/cmi/language/sv/webform.webform.sotepe_yleis.yml, conf/cmi/webform.webform.hyteed_yleis.yml, conf/cmi/webform.webform.sotepe_yleis.yml
* Fix missing SV translations
* Remove STEA as an option
Small fixes to SOTEPE_YLEIS and HYTEED_YLEIS forms.
* `git checkout UHF-10455-fix`
* `make fresh`
[UHF-10455]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10455: Fixes to recently added forms

conf/cmi/grants_metadata.settings.yml, conf/cmi/webform.webform.hyteed_yleis.yml
=> Uhf xx add 68 settings

conf/cmi/language/en/webform.webform.kuva_toiminta.yml, conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.kuva_toiminta.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/config/install/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_handler/config/install/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, public/modules/custom/grants_test_base/modules/grants_test_webforms/config/install/webform.webform.kuva_toiminta.yml, public/modules/custom/grants_test_base/modules/grants_test_webforms/config/install/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
* Add 1000 character limit to "Other notable input" textarea on forms 47 and 49.
* `git checkout UHF-10593`
* `make fresh`
* Run `make shell` and inside the shell revert configuration for forms 47 and 49 `drush gwi 49 --force` and `drush gwi 47 --force` and finally you might want to run the `drush gwco` to open the application sice the gwi closes them for some reason.
[UHF-10593]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10593: Add 1000 character limit to two fields on two forms

conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/webform.webform.liikunta_suunnistuskartta_avustu.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.nuortoimpalkka.yml
* Run `drush gwia3`.
[UHF-11269]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11269: Run drush gwia3

conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml, conf/cmi/webform.webform.iakkaiden_kulttuuri_ja_liikunta.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml, conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.liikunta_laitosavustushakemus.yml, conf/cmi/webform.webform.liikunta_suunnistuskartta_avustu.yml, conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml, conf/cmi/webform.webform.liikunta_yleisavustushakemus.yml, conf/cmi/webform.webform.nuortoimpalkka.yml
[UHF-11269]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11269: Run drush gwia3 in main 

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php, public/modules/custom/grants_handler/translations/fi.po, public/modules/custom/grants_handler/translations/sv.po
Updated error message and translations.
* `git checkout UHf-11038`
* `make fresh`
- Open and try to edit an application which state is "käsittelyssä" or later 
- You should get updated error message
[UHF-11038]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> updated error message and translations

conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml
[UHF-11012]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11012: Run drush gwia3

conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, public/modules/custom/grants_handler/src/ApplicationUploaderService.php
Fix the empty element from the form.
Fix missing HANDLER_ATT_OK -event bug
=> UHF-X fixes

conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, public/modules/custom/grants_handler/src/ApplicationUploaderService.php
Hotfix the events-bug by commenting the bad code.
Remove the extra empty field element in cardinality unlimited field.
=> Uhf x events hotfix

composer.lock, conf/cmi/views.view.locked_content.yml
- Updated active configuration.
- Updated platform
=> Automatic update

conf/cmi/language/en/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml, conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml
quick changes mentioned on the ticket comments
=> UHF-10458: moved text under tooltip, fixed translation's field positions

public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
=> UHF-11457: this should get rid of the missing loggerfactory

e2e/utils/public_helpers.ts, public/modules/custom/grants_oma_asiointi/js/application-draft-list.js, public/themes/custom/hdbt_subtheme/templates/webform/webform-element-base-html--date.html.twig
* Fixed SonarQube issues.
[UHF-11503]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11503 Sonarqube issues

conf/cmi/core.extension.yml, conf/cmi/views.view.locked_content.yml, public/modules/custom/grants_config/config/rewrite/language/fi/views.view.content.yml, public/modules/custom/grants_config/config/rewrite/views.view.content.yml, public/modules/custom/grants_config/grants_config.info.yml
* Added grants config module and rewrites for views content configuration.
[UHF-11026]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11026 Config rewrites

conf/cmi/language/en/webform.webform.segregaation_ehkaisemisavustus.yml, conf/cmi/language/sv/webform.webform.segregaation_ehkaisemisavustus.yml, conf/cmi/webform.webform.segregaation_ehkaisemisavustus.yml, public/modules/custom/grants_metadata/src/TypedData/Definition/KuvaErillisDefinition.php
* Moved the fields on the KuvaErillisDefinition file to correct order
* Renamed some to get the desired order
* `git checkout UHF-11435_fixes`
* `make fresh`
* Run `make shell` and on the container run `drush grants-tools:webform-import`. This will import the new forms to the database.
* Exit the shell
* Run `make drush-uli` and login to the site.
[UHF-11435]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11435: Fixes for the Special youth activity grant for preventing segregation

conf/cmi/webform.webform.segregaation_ehkaisemisavustus.yml
* Metadata fixes
* `git checkout UHF-11435-metadata`
* `make fresh`
* Run `drush grants-tools:webform-import`
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1663
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1671
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1681
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1682
[UHF-11435]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11435: Fix metadata

public/modules/custom/grants_handler/js/grants-dialog.js, public/modules/custom/grants_profile/js/profile_dialog.js
Reverts City-of-Helsinki/hel-fi-drupal-grants#1678
=> Revert "UHF-11289: add new button to hakuprofiili page which allows user to go back"

conf/cmi/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml, conf/cmi/webform.webform.segregaation_ehkaisemisavustus.yml
[UHF-11505]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11505: Run drush gwia3

e2e/utils/field_swap_helpers.ts, e2e/utils/form_helpers.ts, public/modules/custom/grants_handler/templates/application-list-item.html.twig
* Added wrappers for the application number to extract the value in tests.
* Fixed tests after redirection change.
* `git checkout UHF-11631`
* `make fresh`
[UHF-11631]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11631 Tests for redirection changes

conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml
* Updated asukasosallisuus form.
[UHF-11555]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11555 Release

conf/cmi/language/en/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
Updated text & translations
* `git checkout UHF-11759`
* `make fresh`
- Run drush gwi --force
- Run drush cr
- Start filling [form id 49](https://hel-fi-drupal-grant-applications.docker.so/fi/tietoa-avustuksista/kulttuurin-avustukset/kulttuurin-kehittamisavustukset)
- Check that on page 5 has correct question visible (compare with files changed)
- Check translations too
- Check the [confluence documentation](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8851423233/Taide-+ja+kulttuuriavustukset+Kulttuurin+kehitt+misavustukset#Onko-yhteis%C3%B6ll%C3%A4-k%C3%A4yt%C3%B6ss%C3%A4-ymp%C3%A4rist%C3%B6vastuusuunnitelma-tai-vastaava-toimintamalli?-Mik%C3%A4-tai-millainen-mall …
=> UHF-11759: updated form-ID49 question

conf/cmi/language/en/webform.webform.kuva_projekti.yml, conf/cmi/language/sv/webform.webform.kuva_projekti.yml, conf/cmi/webform.webform.kuva_projekti.yml, public/modules/custom/grants_handler/config/install/webform.webform.kuva_projekti.yml
* Changed texts on the Finances step of the form ID48.
* `git checkout UHF-11757`
* Go to shell `make shell` and run `drush gwi --force` to import all changes to all forms.
* Next run `drush gwco` to open all forms.
[UHF-11757]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-11757]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11757: Add text changes for form ID48 Finances step

conf/cmi/language/en/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, conf/cmi/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/config/install/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_handler/config/install/webform.webform.taide_ja_kulttuuriavustukset_tai.yml, public/modules/custom/grants_test_base/modules/grants_test_webforms/config/install/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
* Update question about environmental sustainability of the form ID50.
* Update existing and add new help texts on the finances section of the form ID50.
* `git checkout UHF-11760`
* Go to shell `make shell` and run `drush gwi --force` to import all changes to all forms.
* Next run `drush gwco` to open all forms.
[UHF-11758]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-11758]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UHF-11760]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11760?atlOrigin=e …
=> UHF-11760: Text updates in the form ID50

conf/cmi/language/en/webform.webform.terveys_hyvinvointi_pienavustus.yml, conf/cmi/language/sv/webform.webform.terveys_hyvinvointi_pienavustus.yml, conf/cmi/webform.webform.terveys_hyvinvointi_pienavustus.yml
* Update one text on form ID 64
* `git checkout UHF-11935`
* Go to shell `make shell` and run `drush gwi --force` to import all changes to all forms.
* Next run `drush gwco` to open all forms.
- Go to the [application ](https://hel-fi-drupal-grant-applications.docker.so/fi/tietoa-avustuksista/muut-avustukset/uhf-11761-hyvinvoinnin-ja-terveyden-edistamisen-pienavustus)on page 2
- The text should be updated on all languages. (käyttötarkoitus intro text)
- Check that the [confluence page](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/KAN/pages/8831008926/Asukasosallisuus+pienavustushakemus#K%C3%A4ytt%C3%B6tarkoitus) is updated as stated in the [ticket …
=> UHF-11935: updated one text from form ID 64

conf/cmi/language/sv/webform.webform.kuva_toiminta.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml, conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
* Fixed swedish translations for forms
* `git checkout UHF-11899`
* `make fresh`
* Run `make shell` and update all forms with `drush gwi --force`
* Open all forms with `drush gwco`
* If the grant applications are not visible in the search, run `drush sapi-rt; drush sapi-c; drush sapi-i; drush cr`
[UHF-11899]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11899: Fixed swedish translations for forms

conf/examples/esimerkki_73_NUORLEIRI.json
* Added example data json for form ID73
no need to install
[UHF-12146]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-12146: Added example data for form id73

conf/cmi/language/en/webform.webform.nuorleiri.yml, conf/cmi/language/sv/webform.webform.nuorleiri.yml, conf/cmi/webform.webform.nuorleiri.yml, public/modules/custom/config/install/webform.webform.nuorleiri.yml, public/modules/custom/grants_handler/config/install/webform.webform.nuorleiri.yml, public/modules/custom/grants_test_base/modules/grants_test_webforms/config/install/webform.webform.nuorleiri.yml
* Updated form texts according to ticket
* `git checkout UHF-12099`
* `make fresh`
* Run `make shell`
*  run `drush gwi 73 --force` to update the form
*  run `drush gwco` to open all forms
[UHF-12099]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-12099: Updated form id 73 with new texts

.github/pull_request_template.md, conf/cmi/webform.webform.nuorlomaleir.yml, e2e/playwright.config.ts
* Archived the form ID65
* Removed form ID65 test runs from the e2e tests
* Make sure your instance is up and running latest version of dev-branch
* `git checkout dev && git pull origin dev`
* `make fresh`
* Switch to feature branch
* `git fetch && git checkout UHF-12276`
* Run clear caches.
[UHF-12276]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-12276: Archive the form ID65 and remove its test runs
